all-of-us/curation

data_steward/common.py, data_steward/gcs_utils.py, data_steward/test/unit_test/achilles_heel_test.py, data_steward/test/unit_test/achilles_test.py, data_steward/test/unit_test/validation_test.py, data_steward/validation/main.py
Validation main and tests work with INCLUDE_FILES now instead of CDM_FILES.
gcs_utils now has a check_results function that should be used before running Achilles and Heel.
=> Add include_files and results_check functionality

data_steward/tools/join_ehr_rdr.py
The destination table for join-queries in the script was set as destination_table_id=MAPPING_TABLE_ID.
It now uses 'table_name' which points to the cdm table being joined.
=> join script for ehr rdr bug fix

data_steward/gcs_utils.py, data_steward/test/unit_test/test_util.py, data_steward/test/unit_test/validation_test.py, data_steward/validation/main.py
* Add copy object functionality to gcs_utils
* Add copy object endpoint to validation
* Remove use of private DRC bucket
* Update prefix to: hpo_id / bucket_name
=> PD-1485 Copy files from HPO Buckets to Internal DRC Bucket

data_steward/bq_utils.py, data_steward/resources/fields/concept.json, data_steward/test/unit_test/bq_utils_test.py, data_steward/test/unit_test/ehr_merge_test.py, data_steward/test/unit_test/validation_test.py, data_steward/tools/import_rdr_omop.sh, data_steward/validation/ehr_merge.py
as clustered on it. (This currently requires the project to be whitelisted.)
Dropping RDR-specific observation table logic.
Changing concept date columns to be strings (as this is more convenient when exporting data to Cloud SQL later.)
=> Changing import_rdr_omop to set up any table with person_id 

data_steward/bq_utils.py, data_steward/test/unit_test/ehr_union_test.py, data_steward/validation/ehr_union.py
* Exclude from mapping and load logic any references to tables missing from input dataset
* Increase maximum results returned by bq_utils.list_tables (prod has >1000 tables)
=> Check whether tables exist when generating queries for EHR union

data_steward/deid/src/deid.py
Added support for a generated research_id to replace person_id. We use the people_seed table's (row_number() over() * 1000) for every person_id recorded that will serve as research_id
=> DC-161 Replace person_id with a generated research_id

data_steward/test/unit_test/export_test.py
@ksdkalluri this should get rid of those pesky memcache warnings. Please approve if this looks ok to merge.
=> Prevent warning messages generated by export test output

data_steward/deid/src/deid.py
This change alters the implicit "round()" performed by the cast to an explicit "ceil()" so that the result is a uniform [1,365] date_shift instead of the mostly uniform [0,365] date_shift.
=> Adjust date shift inverval

data_steward/resources/fields/observation_period.json, data_steward/tools/import_rdr_omop.sh
While loading the rdr data into bigquery, the observation_period
csv broke the script.  This updates the script to allow jagged
line csvs with trailing nullable fields for the observation_period
csv.  It moves the nullable timestamp field definitions to the end
of the json definition file and updates the command line as needed.
=> [DC-336]  Load rdr etl into bigquery

data_steward/resources.py
Fixes the EHR_Union error occurred due to the identity_match table.
=> [DC-426] Ignores identity_match_table from CDM_Tables

data_steward/deid/config/ids/config.json, data_steward/deid/config/ids/tables/observation.json, data_steward/deid/rules.py
This patch replaces if/else statements with CASE statements for generalizing the values of particular fields.
For the generalized "copy_to" feature, it ensures a generalized value is only copied if a generalization actually happens on the source field.  If a generalization doesn't
happen, the field that would be copied over instead retains its original value.
=> [DC-544]\[DC-513] fix generalization copies

data_steward/notebooks/bq.py, data_steward/notebooks/start.sh
* Add path separator for windows
* Add PROJECT_ID environment variable for google.datalab
* Fix paths added to PYTHONPATH (/c/path/) to (C:\\path)
=> Add 'git bash for windows' compatibility for notebooks/start.sh

data_steward/deid/aou.py, data_steward/deid/config/ids/config.json, data_steward/deid/config/ids/tables/observation.json, data_steward/deid/parser.py, data_steward/deid/press.py, data_steward/deid/rules.py, data_steward/test/unit_test/data_steward/deid/press_test.py
* Builds in the ability to run a DML statement to remove duplicate
records after performing a generalization on data with multiple
answer choices.
* Refactors how default rules are processed, making it easier to identify which rules
are manipulated and how.
* Allows easier where clause conditions and automatically incorporates fixes for
conditions on nullable columns.  This should allow the clause to be read
so that a duplicate drop clause can be created from the existing information.
* Adding query configuration dictionary to avoid possible SQL injection messages thrown by Codacy.
* Using bq_utils to get fields, instead of a query.
* This should allow multiple dml statements to be created and executed.
There will likely need to be some code around the rules as they run,
but the …
=> [DC-544] Add the ability to run DML statements on de-identified tables

data_steward/.gcloudignore, data_steward/app_base.yaml
* Set runtime to python37
* Remove obsolete directives: api_version, threadsafe and skip_files
* Add .gcloudignore file to replace skip_files directive
* Remove admin handler because multiple script keys not permitted,
still must set up handler for it
=> [DC-551] Update app_base.yaml and gcloudignore for GAE py3

.circleci/config.yml
Moving the apt-get update command to be part of the `Allow google cloud to be added as apt repo` .
It must also remain as part of the `Install google cloud sdk` command or that one fails.
=> [DC-597] CircleCI build environment failure

data_steward/constants/validation/participants/identity_match.py, data_steward/constants/validation/participants/readers.py, data_steward/test/unit_test/data_steward/validation/participants/readers_test.py, data_steward/validation/participants/identity_match.py, data_steward/validation/participants/readers.py
A fix for transforming float values whose field types are defined as date, datetime, or timestamp to a string.
Updates unit tests.
Adds a unit test to verify byte string conversions.
=> [DC-595] participant match datetime parsing failure

.gitignore, data_steward/tools/import_rdr_omop.sh, data_steward/tools/table_copy.sh
- Rename flags for clarity
- Include `-x` for script logging, no longer need to echo the exact command (adds risk of divergence)
- Add error checks for existence of the input RDR directory
- Remove requirement for `gcloud config set project xxx`
- Ignore virtualenv dir
=> [DC-598] Improve RDR import script

data_steward/cdr_cleaner/manual_cleaning_rules/clean_height_weight.py
Use `src_id` from `measurement_ext` to exclude RDR data from cleaning rule
=> [DC-616] Exclude Physical Measurements from height and weight cleaning rule

data_steward/bq_utils.py, data_steward/resources/achilles_analysis.csv, data_steward/resources/achilles_dml.sql, data_steward/resources/achilles_heel_dml.sql, data_steward/test/unit_test/achilles_heel_test.py, data_steward/test/unit_test/achilles_test.py, data_steward/validation/achilles.py, data_steward/validation/achilles_heel.py
Creates randomized tables so that achilles tests do not hit rate limits.
Also makes the following improvements:
- Initialize table achilles_analysis by loading from csv instead of bq VALUES
- Update queries in `achilles_dml.sql` and `achilles_heel_dml.sql` so that the output fields conform to table fields (name and type)
- Use `select *` instead of bq `insert into`, which still count towards the table load quota, but highlights issues which could hit table schema/metadata update quota. (This is probably the limit we keep hitting, which is 5 updates every 10 seconds)
=> [DC-621] Rate limit exceeded on Achilles test and Achilles heel test

.pylintrc
Add pylintrc file
* Disable all rules
* Enable only `unused-*`
=> [DC-550] Reconfiguration of Codacy for Python 3 migration

data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid.py
Updates race_concept_id to 3000000001 and race_source_value to "None Indicated" when a person selects  “Hispanic, Latino, or Spanish” as - ethnicity but has not selected anything else.
=> [DC-619] Update person table repopulation to address missing race responses

data_steward/init_env.sh
Unfortunately I don't see a good way of verifying this fix. I triggered this rerun with SSH and hacked in GH_USERNAME=circleci to confirm this will at least is the only issue:
https://circleci.com/gh/all-of-us/curation/863
CC @mark-velez
=> [DC-695] Provide fallback username on anonymous circle runs

data_steward/analytics/cdr_ops/data_loss_through_pipeline.py
Navigating through unioned -> combined -> deid
Visualizations include:
- Overall data loss for each table (on the aggregate level) in a dataframe
- Percentage of data lost for each site for each table (bar chart)
- Pie charts to show each site's contribution to the overall 'loss' for each table
=> [EDQ-379] Shows the loss of data through the pipeline

data_steward/constants/validation/main.py, data_steward/validation/main.py, tests/integration_tests/data_steward/validation/main_test.py, tests/unit_tests/data_steward/validation/main_test.py
Generate empty report if submission folder is named incorrectly
=> [DC-369] Enforce Submission Directory Naming Convention

data_steward/analytics/cdr_ops/ehr_demographics_by_site.py
Shows the site demographics for each site based on the person table. 
Subsequent analyses to report out relative over- or under-representation of each group for each table (e.g. drug_exposure table) relative to their representation in the person table (expressed as a percentage difference.)
Graphical representations included and output is produced.
Practical use cases right now are limited but could be potentially of use in future data quality iterations.
=> [EDQ-354] Site Demographics Notebook

.circleci/config.yml
Minor follow-ups to https://github.com/all-of-us/curation/pull/416 
1. Cache pip installs
This caches the virtualenv folder between runs, providing a starting point for `pip install`. You can see it in action here (~40s -> ~2s): 
Note: there seems to be a fair amount of variance in the time required to download the cache. 3s seems typical, but on this PR the unit tests restore_cache step took ~50s (about the same time as just running pip install).
2. Skip unit tests. These already run post-merge into develop, so there's no additional information gained by running them nightly.
=> [DC-636] Circle cleanup: cache pip installs, don't run unit tests nightly

data_steward/cdr_cleaner/args_parser.py, data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/clean_cdr_engine.py, data_steward/cdr_cleaner/cleaning_rules/base_cleaning_rule.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/base_cleaning_rule_test.py
* Setting up a base class for Cleaning Rules to Inherit from.
* Modifying the current rdr pipeline to accept class or function names.
* Setting the pipeline up to only accept instances of a BaseClass in the future.
* Allows the base class to store project_id, dataset_id, sandbox_dataset_id,
affected datasets, jira issue numbers, and a common language description of each rule.
* Updates the gather_<dataset>_queries functions to use a single helper module.
* Currently allows backwards compatability to work with existing function calls.
* Allows new rules to be added to a list of classes to call.  Removes a lot of boiler plate code.
* Updates the logging to add the logging handler to the root handler instead
the engine logger.
* Adds two new common command line parameters:  one for a sandbox …
=> [DC-718] Create Clean Rules Base Class to hold basic cleaning rule info

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression_test.py
* Contains an application of using the base class to instantiate a rule.
* Adds a unit test of the new cleaning rule.
* adds a cleaning rule to sandbox rows removed and then remove rows where
observation_source_concept_id IN ((43530490, 43528818, 43530333)
=> [DC-529] Remove irrelevant observation_source_concept_ids from the RDR Export

tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression_test.py
* modifying unit test module `curation/unit_tests/data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression_test.py` for a pylint fix
=> [DC-529]  pylint fix on test module

data_steward/analytics/tools/concept_success_rates_visualizations.py, data_steward/analytics/tools/data_after_death_visualizations.py, data_steward/analytics/tools/duplicates_visualizations.py, data_steward/analytics/tools/email_generator.py, data_steward/analytics/tools/end_dates_before_start_dates_visualizations.py, data_steward/analytics/tools/ingredient_usage_visualizations.py, data_steward/analytics/tools/measurement_integration_visualizations.py, data_steward/analytics/tools/route_concept_population_visualizations.py, data_steward/analytics/tools/unit_population_visualizations.py
* Rearranged the site names in the visualization notebooks to follow the (appropriate) alphabetical order with the two new sites in the pipeline
* Added a cell in the visualization notebooks to accommodate the (occasional) extra column in the aggregate_info sheet
* Updated the e-mail generator to be consistent with the new output file names
* Made it so the e-mail generator no longer has a bug when a site has a unit concept success rate of 100%
=> [EDQ-410] Minor updates to e-mail generator and visualization notebooks.

data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/hpo_class.py, data_steward/analytics/table_metrics/metrics_over_time/messages.py, data_steward/analytics/table_metrics/metrics_over_time/metrics_over_time.py, data_steward/analytics/table_metrics/weekly_scripts/erroneous_dates.py
* Includes a notebook that calculates the percentage of 'erroneous dates' for the following tables: condition_occurrence, procedure_occurrence, visit_occurrence, drug_exposure, measurement, observation. Erroneous dates are those that are prior to 1900 for the observation table and prior to 1980 for all of the other tables.
* Changed the metrics_over_time library to accommodate for this new metric (part of EDQ-425)
* Validated the output for the resulting metrics_over_time script
=> [EDQ-414] Create 'erroneous date' data quality metric notebook

data_steward/cdr_cleaner/clean_cdr.py
* adds missing ObservationSourceConceptIDRowSuppression class to RDR rules
* restores commented invalid_procedure_source.get_remove_invalid_procedure_source_queries function
* properly formats CleanMappingExtTables class as a tuple
* restores commented classes that cause sql listing failures.  comments are maintained to indicate changes are needed.
* adds comments above CleanMappingExtTables usage identifying why it breaks on going reporting capabilities.  this should be fixed in a separate PR.
* changes the name of the function the base classes use from `get_query_dictionary_list` to `get_query_specs`.
* formatting changes were introduced by yapf
=> [DC-756] Update RDR and Unioned_EHR cleaning rules lists

data_steward/analytics/cdr_ops/number_achilles_errors.py, data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/hpo_class.py, data_steward/analytics/table_metrics/metrics_over_time/messages.py, data_steward/analytics/table_metrics/metrics_over_time/organize_dataframes.py, data_steward/analytics/table_metrics/metrics_over_time/populate_dfs_with_aggregate_info.py, data_steward/analytics/table_metrics/metrics_over_time/unweighted_aggregate_metric_functions.py, data_steward/analytics/table_metrics/other_scripts/number_achilles_errors.py, data_steward/analytics/table_metrics/weekly_scripts/number_achilles_errors.py, data_steward/analytics/tools/visualizations/conformance/achilles_errors.py
* Develops notebooks (both in the weekly metrics and other metrics sections) that can calculate the number of relevant ACHILLES errors
* Integrate the new metric (which would be very similar to the drug_integration and ingredient_integration metrics) into the metrics_over_time script
* Create a visualization notebook for this new metric
* Ensures that unweighted aggregate metrics are included in 'table' dataframes
* Improves means of calculating 'averages' for 'aggregate' objects in instances where the number is not available
=> [EDQ-451] Create New Metric to Monitor ACHILLES Errors Over Time

tools/validate_commit_message.sh
- Check length of var to ensure not empty
=> [DC-787] CircleCI commit message check fails due to bug

data_steward/analytics/cdr_ops/systematic_scripts/height_weight_cleaning_rule_models.py
* Leverages the concept_ancestor table to ensure a robust picture of heights/weights
* Exclude participants who have conditions that may explain anomalous heights/weights
* Shows all of the measurement_as_value fields in a standardized unit
* Shows various metrics for the heights/weights (e.g. mean, median, stdev, etc.)
* Models the distribution of data when selecting certain percentages of the data
=> [EDQ-456] Notebook to Visualize Height and Weight Distributions

data_steward/analytics/table_metrics/combined_deid_scripts/concept_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/data_after_death.py, data_steward/analytics/table_metrics/combined_deid_scripts/date_datetime_disparity.py, data_steward/analytics/table_metrics/combined_deid_scripts/diabetes_completeness.py, data_steward/analytics/table_metrics/combined_deid_scripts/drug_integration_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/drug_route_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/duplicates.py, data_steward/analytics/table_metrics/combined_deid_scripts/end_before_begin.py, data_steward/analytics/table_metrics/combined_deid_scripts/erroneous_dates.py, data_steward/analytics/table_metrics/combined_deid_scripts/measurement_integration_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/measurement_units_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/number_achilles_errors.py, data_steward/analytics/table_metrics/combined_deid_scripts/person_id_foreign_key_notebook.py, data_steward/analytics/table_metrics/combined_deid_scripts/source_concept_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/visit_date_disparity.py, data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_dqm_objects.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/messages.py, data_steward/analytics/table_metrics/metrics_over_time/metrics_over_time.py, data_steward/analytics/table_metrics/metrics_over_time/unweighted_aggregate_metric_functions.py, data_steward/analytics/table_metrics/metrics_over_time/weighted_aggregate_metric_functions.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/data_after_death.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/duplicates.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/end_before_begin.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/visit_date_disparity.py, data_steward/analytics/tools/dq_issue_tracker/create_dq_issue_site_dfs.py
* Ensured consistency in the means of calculating error rates (reporting 'error rate' rather than a mix of 'error rate' and 'success rate')
* Implemented a temporary workaround for a bug within the duplicates notebook (regarding datetime casting)
* Uses 0 values instead of nan values in the metrics_over_time module
* Fixed the dictionaries and lists with respect to the constants file.
* Changed the means of generating the full site names in the combined/deid datasets
* Changed setup functions of the duplicates metric (relic of old setups)
=> [EDQ-462] Small Fixes in Data Quality Metrics Processes

data_steward/constants/bq_utils.py, data_steward/tools/table_copy.sh
Updated instances of table limits from 2,000 to 10,000 in `bq_utils.py` and `table_copy.sh`
=> [DC-825] Fix source of table_copy.sh issue copying clinical tables

data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py
Updated description in `clean_mapping.py`
=> [DC-879] Clean extension table mapping rule uses incorrect description

data_steward/analytics/cdr_ops/systematic_scripts/height_weight_cleaning_rule_models.py, data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_dqm_objects.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/messages.py, data_steward/analytics/table_metrics/metrics_over_time/metrics_over_time.py, data_steward/analytics/table_metrics/metrics_over_time/startup_functions.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/data_after_death.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/drug_integration_success_rate.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/duplicates.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/end_before_begin.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/unit_success_rate.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/visit_date_disparity.py, data_steward/analytics/tools/dq_issue_tracker/create_dq_issue_site_dfs.py, data_steward/analytics/tools/dq_issue_tracker/cross_reference_functions.py, data_steward/analytics/tools/dq_issue_tracker/dictionaries_and_lists.py, data_steward/analytics/tools/dq_issue_tracker/general_functions.py, data_steward/analytics/tools/email_generator/create_dqms.py, data_steward/analytics/tools/email_generator/dictionaries_and_lists.py, data_steward/analytics/tools/email_generator/email_generator.py, data_steward/analytics/tools/email_generator/functions_to_create_dqm_objects.py, data_steward/analytics/tools/email_generator/functions_to_create_hpo_objects.py, data_steward/analytics/tools/email_generator/messages.py, data_steward/analytics/tools/email_generator/startup_functions.py, data_steward/analytics/tools/visualizations/plausibility/end_dates_before_start_dates.py, data_steward/analytics/tools/visualizations/plausibility/erroneous_dates.py
* Fixed issue with understanding the distribution behind erroneous weights.
* Ensured all f-strings were present in the visualization notebooks.
* Got rid of target low information in metrics_over_time and email_generator - not needed now that all of the upstream report-outs are correct.
* Made small changes to data quality issue tracker. Issue mostly lied with the difference in calculation methods for some of the 'error metrics'.
* Variable changes for the updated unit success rate name.
=> [EDQ-498] Make Logic for Data Quality issue Reporting Consistent

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/base_cleaning_rule.py, data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py
- Updated `clean_ppi_numeric_fields_using_parameters.py` to use new base class `base_cleaning_rule.py` with DML statements changed to SQL SELECT statements
- Replaced `ppi_numeric_fields` with  `CleanPPINumericFieldsUsingparameters` class in `clean_cdr.py` 
- Created unit and integration tests `clean_ppi_numeric_fields_using_parameters_test.py`
=> [DC-827] Update Numeric Free Text CR to New Base Class

data_steward/analytics/cdr_ops/ad_hoc_analyses/mapping_in_entirety_issues.py
* Notebook contains information with respect to measurement_source_concept_ids/measurement_source_values that failed to map to the appropriate measurement_concept_ids/value_as_concept_ids.
* Notebook can be expanded in the future with additional concept_class_ids and/or concept relationships.
* As of right now, the findings indicate that 'incomplete' mappings are due to ETL issues confined to a small number of sites. Consequently, further explorations on this front can be deprioritzed in favor of system-wide issues.
=> [EDQ-355] Notebook for Incomplete Measurement Mappings

data_steward/analytics/table_metrics/combined_deid_scripts/visit_date_disparity.py, data_steward/analytics/table_metrics/metrics_over_time/aggregate_metric_classes.py, data_steward/analytics/table_metrics/metrics_over_time/create_aggregate_objects.py, data_steward/analytics/table_metrics/metrics_over_time/data_quality_metric_class.py, data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_dqm_objects.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/hpo_class.py, data_steward/analytics/table_metrics/metrics_over_time/metrics_over_time.py, data_steward/analytics/table_metrics/metrics_over_time/setup_dataframes.py, data_steward/analytics/table_metrics/metrics_over_time/startup_functions.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/visit_date_disparity.py, data_steward/analytics/tools/dq_issue_tracker/class_definitions.py, data_steward/analytics/tools/dq_issue_tracker/constants.py, data_steward/analytics/tools/dq_issue_tracker/create_dq_issue_site_dfs.py, data_steward/analytics/tools/dq_issue_tracker/cross_reference_functions.py, data_steward/analytics/tools/dq_issue_tracker/dictionaries_and_lists.py, data_steward/analytics/tools/dq_issue_tracker/general_functions.py, data_steward/analytics/tools/email_generator/constants.py, data_steward/analytics/tools/email_generator/create_dqms.py, data_steward/analytics/tools/email_generator/data_quality_metric_class.py, data_steward/analytics/tools/email_generator/dictionaries_and_lists.py, data_steward/analytics/tools/email_generator/email_generator.py, data_steward/analytics/tools/email_generator/functions_to_create_dqm_objects.py, data_steward/analytics/tools/email_generator/functions_to_create_hpo_objects.py, data_steward/analytics/tools/email_generator/hpo_class.py, data_steward/analytics/tools/email_generator/messages.py, data_steward/analytics/tools/email_generator/organize_relevant_dqms.py, data_steward/analytics/tools/email_generator/startup_functions.py, data_steward/analytics/tools/visualizations/conformance/visit_date_disparity.py
* Reworked the metrics_over_time module by implementing f-strings, leveraging a more robust 'constants' file, and adding visit_date_disparity metrics where applicable
* Reworked the dq_issue_tracker module by implementing f-strings, implementing a 'constants' file, and adding visit_date_disparity metrics where applicable
* Reworked the email_generator module by implementing f-strings, implementing a 'constants' file, and adding visit_date_disparity metrics where applicable
* Changed the column names for the two visit_date_disparity notebooks to ensure they more closely resemble the names of similar notebooks
* Added a visit_date_disparity visualization notebook.
=> [EDQ-513] Integrate the 'Visit Date Disparity' Metric into the Current Schema

data_steward/requirements.txt
Updated google-api-core version to 1.17.0
=> [DC-961] google-api-core causing ValidateAllHpoSites cron job to fail

.circleci/config.yml
* for any failure on develop or master, a slack alert will be generated.
=> [DC-967] add build failure alerts to slack alerts channel

data_steward/cdr_cleaner/cleaning_rules/drop_duplicate_ppi_questions_and_answers.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/drop_duplicate_ppi_questions_and_answers_test.py
* broke because it wasn't updated to the pythonic properties setting
* fixed it.
=> [DC-707] clean rules reporter

data_steward/resource_files/fields/lookup_tables/_deactivated_participants.json, data_steward/utils/participant_summary_requests.py, tests/integration_tests/data_steward/utils/participant_summary_requests_test.py
Modified `participant_summary_requests.py` module to change `suspension_time` to `deactivated_date` in order to utilize the queries in the `retract_deactivated_pids.py` module
=> [DC-1047] Change suspension_time to deactivated_date in _deactivated_participants table

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_past_deactivation_date.py, data_steward/resource_files/fields/lookup_tables/_deactivated_participants.json, data_steward/retraction/retract_deactivated_pids.py, data_steward/utils/participant_summary_requests.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/bigquery_tests_base.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_past_deactivation_date_test.py, tests/integration_tests/data_steward/utils/participant_summary_requests_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_past_deactivation_date_test.py, tests/unit_tests/data_steward/utils/participant_summary_requests_test.py
-  Created `remove_ehr_data_past_deactivation_date.py` module to utilize `retract_deactivated_pids.py` and `participant_summary_requests.py` modules to remove EHR data of deactivated participants past the date of deactivation
- Created unit and integration test modules to properly test `remove_ehr_data_past_deactivation_date`
- Modified `participant_summary_request.py` module to convert the `suspensionTime` (`deactivation_date`) field to be of type `DATE` instead of `TIMESTAMP`
=> [DC-686] Remove EHR data past date of deactivation for deactivated participants

data_steward/tools/generate_combined_dataset.sh
export VOCABULARY_DATASET variable for combined stage cleaning rule
* the populate_route_ids cleaning rule requires this environment variable to be set
=> [DC-1122] export VOCABULARY_DATASET variable for combined stage

.circleci/config.yml
Revert "[DC-997] Build conflicts due to nightly builds running on forks (#645)"
This reverts commit acaf19da which is associated with the issue
[DC-997]: https://precisionmedicineinitiative.atlassian.net/browse/DC-997
=> [DC-1142] integration tests not running

tests/unit_tests/data_steward/utils/pipeline_logging_test.py
* added datetime mocking to ensure slight changes in time won't result
in test failure in `test_logger_setup` and `test_generate_path` modules
* changed `logging_path` in `setUp` to ensure date matches the mocked date
=> [DC-1016] Pipeline Logging unit test intermittently fails

data_steward/validation/ehr_union.py
* [DC-1177] Remove long queries from log messages and use job_id
[DC-1177]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1177
=> [DC-1177] Logging error causes union jobs to fail

data_steward/cdr_cleaner/cleaning_rules/null_invalid_foreign_keys.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/null_invalid_foreign_keys_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/null_invalid_foreign_keys_test.py
* modified main module and unit test because cannot set python code destination object when running the `CREATE OR REPLACE` statement in the `SANDBOX_QUERY` queries
* created integration test to test functionality of main module
* in the integration test only the `person` and `procedure_occurrence` tables are cleaned as between those two all foreign key columns will be tested
* only the mapping tables used in the `INVALID_FOREIGN_KEY_QUERY` for `person` and `procedure_occurrence` are created and supplied with data
* the `get_affected_tables` function from main module is mocked as we do not need all the CDM tables to be iterate through for cleaning, only `person` and `procedure_occurrence`
=> [DC-1169] Integration Test for Invalid Foreign Keys CR

data_steward/constants/validation/main.py, data_steward/validation/main.py
* removed code creating /ParticipantValidation/SiteFiles endpoint handling in `/validation/main.py`
* removed `WRITE_SITE_VALIDATION_FILES` constant from `constants/validation/main.py`
* removed `write_sites-pii_validation_files()` function from `/validation/main.py`
=> [DC-1232] Assess Safety of Removing EHR Site Validation File Writer Endpoint

data_steward/utils/participant_summary_requests.py, tests/unit_tests/data_steward/utils/participant_summary_requests_test.py
* Created function `get_site_participant_information` which retrieves all the participants information using the columns listed in `FIELDS_OF_INTEREST_FOR_VALIDATION` 
** uses pagination and count to significantly speed up the time it takes to return records. Extremely helpful when using to get results from sites with a lot of participants as this no longer takes upwards of 10 minutes. Takes about 2 to retrieve 30k+ records.
* Created test function `test_get_site_participant_information`
=> [DC-1213] Use the Participant Summary API to retrieve fields of interest for participant validation

data_steward/cdr_cleaner/clean_cdr.py, tests/unit_tests/data_steward/cdr_cleaner/clean_cdr_test.py
Make clean_cdr() callable from other python modules.
=> [DC-1288] Allow calling clean_cdr stage from another python module

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/valid_death_dates.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/valid_death_dates_test.py
* modified `valid_death_dates.py`:
1. module inherits from `BaseCleaningRule`
2. created a sandbox query `SANDBOX_INVALID_DEATH_DATE_ROWS` to sandbox death date rows that occur before the start of the program or after the current date
* modified `cdr_cleaner.py` to use new class in import statement. Removed from all cleaning class lists except for `COMBINED_CLEANING_CLASSES`
* created `valid_death_dates_test.py` to test that the queries are created properly populated with the correct information
=> [DC-822] Update Death Date Validation CR to New Base Class & Correct Pipeline Step

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/drop_cope_duplicate_responses.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/drop_cope_duplicate_responses_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/drop_cope_duplicate_responses_test.py
* Adds Drop duplicate COPE response rows cleaning rule
* Adds Unit tests and integration tests
=> [DC-1146] Drop duplicate COPE response rows

data_steward/constants/cdr_cleaner/clean_cdr.py, data_steward/tools/create_tier.py, data_steward/utils/bq.py, tests/unit_tests/data_steward/tools/create_tier_test.py
* created `create_datasets` function in `create_tier.py` which does the following:
1. Verifies that the proper information is given (`client`, `name`, `input_dataset`, `tier`, `release_tag`, `deid_stage`) by throwing `RuntimeError`s if not
2. Constructs the names of the datasets from the given `name` parameter
3. Creates the dataset objects from the list of `dataset_ids`
4. Creates the dataset from the list of `dataset_objects`
5. Updates the labels/tags of the`backup_dataset_id`, `staging_dataset_id`, and `final_dataset_id` datasets to identify whether or not the particular dataset has been de-identified
6. Copies the tables from the `input_dataset` to the `backup_dataset_id`, and `staging_dataset_id` datasets
* created `test_create_datasets` function in `create_tier_test.py` which does …
=> [DC-1293] Create required intermediate and final datasets

data_steward/cdr_cleaner/cleaning_rules/base_cleaning_rule.py
* Added table_namer property which returns self._table_namer
* Added table_namer setter which sets table_namer to a default value
using kwargs if no value is given
Returns the table_namer if value is given
* Ensured existing cleaning rule tests passed as normal
=> [DC-1326] Add table namer property to base cleaning rule

data_steward/utils/sandbox.py, tests/unit_tests/data_steward/utils/sandbox_test.py
Creates an options clause for defining BigQuery table descriptions and labels.
=> [DC-1329] create sandbox utility options function

data_steward/analytics/cdr_ops/rdr_export_qc.py
* Added a check to rdr_export_qc notebook which checks id range in mapped tables.
=> [DC-294] Add checks on id range to RDR Export evaluation notebook

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map_test.py
* Created `questionnaire_response_id_map.py` module which:
1. Creates the `_deid_questionnaire_response_map` lookup table if it does not already exists which populates with the `questionnaire_response_id` column from the `observation` table and generates a random value for the `research_response_id` column.
2. Performs the `QRID` to `RID` mapping by replacing the `QRID` in the `observation` table with the `RID` found in the `_deid_questionnaire_response_map` lookup table.
* Unit test created to test the query generation in `questionnaire_response_id_map.py` module
=> [DC-1347] Create questionnaire_response_id mapping rule

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map.py, data_steward/constants/cdr_cleaner/clean_cdr.py, data_steward/tools/deid_runner.sh, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map_test.py
* Added a `REGISTERED_TIER_DEID_CLEANING_CLASSES` list
* Added `QRIDtoRID` cleaning rule to the
`REGISTERED_TIER_DEID_CLEANING_CLASSES` list
* Added the registered tier `DataStage` element
* Added the registered tier rules to the `DATA_STAGE_RULES_MAPPING`
dictionary
* Added the `REGISTERED_TIER_DEID` constant
* Updated to run registered tier cleaning rules before running deid
=> [DC-1349] Update registered tier to use questionnaire_response_id remapping cleaning rule.

data_steward/deid/aou.py, data_steward/deid/config/ids/config.json, data_steward/deid/config/ids/tables/observation.json
Removed original `questionnaire_response_id` remapping rule logic by
* Removing `create_questionnaire_mapping_table` and `map_questionnaire_response_ids` functions from `aou.py`
* Removing any calls to those functions above in `aou.py`
* Removing compute rules in `observation.json` and `config.json`
=> [DC-1350] Remove registered tier questionnaire_response_id remapping logic

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/manual_cleaning_rules/clean_smoking_ppi.py, data_steward/cdr_cleaner/manual_cleaning_rules/negative_ppi.py
This changes the run order of several cleaning rules in the RDR data
stage.  This will fix the issue that caused the smoking data to be
suppressed.
It adds comments to help identify some common expected rule running orders.
It removes some useless code from the manual cleaning rules that prevented
the rules from being run as standalone rules.  They ran fine as part of the
RDR list.
=> [DC-1394] Too much survey data being suppressed/cleaned

data_steward/cdr_cleaner/cleaning_rules/truncate_rdr_using_date.py, data_steward/tools/create_ehr_and_rdr_snapshot.sh, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/truncate_rdr_using_date_test.py
* updates the cleaning rule to parameterize the cutoff date
* updates the bash script to accept a truncation date parameter without requiring the parameter.
* if not provided, the cleaning rule defaults to using today's date as the truncation date
* default is implemented in the rule to take the business logic out of the bash script
* will default correctly if None is the argument value
* adding unit test to validate the date string
=> [DC-1431] parameterizing rdr cleaning rule truncation date

data_steward/cdr_cleaner/cleaning_rules/README.md, data_steward/tools/deid_runner.sh
* removed bash script invocation in `deid_runner`
* Updated `cleaning_rules/README.md` and removed mentions of `generate_ext_tables.py`
=> [DC-1354] Confirm removal of free standing generate_ext_tables python script

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/free_text_survey_response_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/free_text_survey_response_suppression_test.py
* created `free_text_survey_response_suppression.py` to sandbox and record suppress any records with a concept id associated with a free text value by extending the `AbstractBqLookupTableConceptSuppression` class
* added `FreeTextSurveyResponseSuppression` to pipeline
* integration test
=> [DC-1387] Free Text survey response record suppression

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/ehr_submission_data_cutoff.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/ehr_submission_data_cutoff_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/ehr_submission_data_cutoff_test.py
* created cleaning rule to sandbox and drop data in OMOP tables by:
** getting all OMOP tables except for person table for cleaning rule
optimization
** only getting the date and datetime fields from those OMOP tables
** sandbox and drop the records that fall after the cutoff date
* integration test
* unit test
* added cleaning rule to the pipeline
=> [DC-1445] Enforce Data cutoff of ehr submissions

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/prefer_not_to_answer_codes_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/prefer_not_to_answer_codes_suppression_test.py
* Suppresses any records in the `observation` table with an `observation_source_concept_id` as `903079`
* Integration test
* Added cleaning rule to the pipeline
=> [DC-542] PMI_PreferNotToAnswer appear as an observation_source_concept_id

data_steward/cdr_cleaner/cleaning_rules/remove_records_with_wrong_date.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_records_with_wrong_date_test.py
Fix Cutoff_date param in remove_records_with_wrong_date.py
=> [DC-1480] Remove records with wrong date fails due to cutoff_date param position

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/string_fields_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/string_fields_suppression_test.py
* Add missing StringFieldsSuppression class to clean_cdr.py
* Add 715711 to exclusion list
* Add integration test case for excluded concept_id
=> [DC-1494] StringFieldsSuppression class not in controlled tier cleaning class list

data_steward/tools/create_tier.py
* Updated `ADD_ETL_METADATA_QUERY` to have double brackets
* Updated the `dataset_id` in the rendering of `ADD_ETL_METADATA_QUERY`
so that it will use the STAGING dataset
* Updated the `field_value` variable name to match the one used in
`ADD_ETL_METADATA_QUERY`
=> [DC-1506] Use Double Brackets in Jinja Template

data_steward/tools/add_cdr_metadata.py, tests/unit_tests/data_steward/tools/add_cdr_metadata_test.py
In `add_cdr_metadata.py` module:
* Updated queries to use jinja template
* Updated/created doc strings for functions
* Added clarifying comments
* Updated query generation to use render instead of format
* Split `__name__ == '__main__'` to two functions to allow other module to call `add_cdr_metadata.py`
* Created `parser_cdr_metadata_args` and `main`
* `__name__ == '__main__'` only calls `main()` function now
In `add_cdr_metadata_test.py` module:
* Added variables to `setUp` function to be used in `test_parse_cdr_metadata_args` function
* Updated query generation to use render
* Fixed `actual_query` in `test_etl_metadata_query` and `test_copy_query` to not have extra carriage return
* Created `test_parser_cdr_metadata_args` function to:
* Test if incorrect parameters are given, …
=> [DC-1378] update add_cdr_metadata.py to be called from another modules

data_steward/cdr_cleaner/cleaning_rules/aggregate_zip_codes.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/aggregate_zip_codes_test.py
In `aggregate_zip_codes.py`
* Removed line in `MODIFY_ZIP_CODES_AND_STATES_QUERY` that sets the `value_source_value` to a state
* Removed commented out code
* Updated original issues list in doc string
In `aggregate_zip_codes_test.py`
* Removed commented out code
* Updated original issues list in doc string
* Updated `cleaned_values` list
=> [DC-1504] Aggregated Zip Codes Should Ignore value_source_value update

data_steward/cdr_cleaner/cleaning_rules/valid_death_dates.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/valid_death_dates_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/valid_death_dates_test.py
In `valid_death_dates.py` module:
* Fixed syntax error in `KEEP_VALID_DEATH_DATES_ROW` query
* Swapped order of list of returned queries
In `valid_death_dates_test.py` unit test:
* Swapped order of `expected_list` list
* integration test
=> [DC-1206] [DC-1486] Integration Test for Death Date Validation CR

data_steward/tools/create_tier.py, tests/unit_tests/data_steward/tools/create_tier_test.py
* Updated logic to update `qa_handoff_date` if base is in the deid_tier
* Created `test_qa_handoff_date_update` function to test changes in
create_tier.py
=> [DC-1511] Insert instead of Update is used to add cdr metadata

data_steward/cdr_cleaner/cleaning_rules/deid/repopulate_person_controlled_tier.py, data_steward/cdr_cleaner/cleaning_rules/deid/repopulate_person_using_observation.py, data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid_test.py
* removed the condition of having `ethnicity_concept_id = 38003563` in
both `repopulate_person_using_observation.py` and
`repopulate_person_post_deid.py` queries
* added clarifying comment to module doc strings explaining the change
=> [DC-1446] Re-map race_concept_id

data_steward/cdr_cleaner/cleaning_rules/remove_non_matching_participant.py, data_steward/tools/generate_combined_dataset.sh, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_non_matching_participant_test.py
* Return query dict rather than list for sandbox queries
* Make ehr_dataset_id, validation_dataset_id args required
* In generate_combined_dataset.sh add ehr_dataset param
=> [DC-1487] Fixes for remove_non_matching_participant

data_steward/resources.py
* This fixes issues when resources module is loaded in
environments whose default encoding is != UTF-8
=> [DC-1417] Specify UTF-8 encoding in cdm_schemas()

data_steward/cdr_cleaner/cleaning_rules/store_pid_rid_mappings.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/store_pid_rid_mappings_test.py
* fixes one bug in the cleaning rule
* mocks the hard coded PIPELINE_TABLES primary dataset reference
* makes sure existing values are not overwritten.
* makes sure new values are added along with random shift elements and partition dates
=> [DC-1542] integration test for storing pid/rid/shift mappings in primary table

data_steward/tools/add_hpo.py, tests/unit_tests/data_steward/tools/add_hpo_test.py
* Modified module to separate the generation of the site masking sandbox table and extension table creation in `generate_site_mappings_and_ext_tables.py` module
* Created `UPDATE_SITE_MASKING_QUERY` in `add_hpo.py` module
* Created `update_site_masking_table` function in `add_hpo.py` module to create the unique site masking and update the `site_maskings` table in `pipeline_tables` dataset
* Modified the `main` function in `add_hpo.py` module to update the site masking table when updating the lookup tables
* Created `test_update_site_masking_table` to test the functionality in the `add_hpo.update_site_masking_table` function
=> [DC-1501] Create a unique site mapping when a new site is on boarded

data_steward/constants/validation/main.py
* Updated missing consent language in `main.py`
=> [DC-1147] Clarify missing consent language in the results.html file

data_steward/tools/recreate_person.py, tests/integration_tests/data_steward/tools/recreate_person_test.py
* Added `pipeline_logging`
* Updated `ADD_COLUMNS_QUERY` to add `sex_at_birth_*` columns
* Updated `UPDATE_PERSON_QUERY` to set `sex_at_birth_*` columns
* Updated unit test to test new functionality in `recreate_person.py`
=> [DC-1581] Copy sex_at_birth_* columns at output time

data_steward/utils/participant_summary_requests.py, tests/integration_tests/data_steward/utils/participant_summary_requests_test.py, tests/unit_tests/data_steward/utils/participant_summary_requests_test.py
* [DC-1588] Use client library for storing participant data instead of pd_gbq
[DC-1588]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1588
=> [DC-1588] Update participant summary test to use bq client library

data_steward/tools/generate_ext_tables.py
* Updated the `get_mapping_table_ids` function to use bq.list_tables as
bq_utils.list_tables is being deprecated
=> [DC-1606] Modify `get_mapping_table_ids` Function In `generate_ext_tables`

data_steward/cdr_cleaner/clean_cdr.py, data_steward/tools/generate_unioned_ehr_dataset.sh
Remove staging_sandbox creation and update its usages with unioned_ehr_sandbox
* move ehr_submission_data_cutoff to top of the unioned_ehr cleaning_rules
=> [DC-1646] Remove staging_sandbox creation and update its usages with unioned_ehr_sandbox

data_steward/retraction/retract_deactivated_pids.py, data_steward/retraction/retract_utils.py
Fix the retract utils script works with staging dataset and add a condition on fields that are missing end_datetime
=> [DC-1478] Remove deactivated participants script fails for tables without datetime fields

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/drop_participants_without_ppi_or_ehr.py, data_steward/cdr_cleaner/cleaning_rules/drop_rows_for_missing_persons.py, data_steward/cdr_cleaner/cleaning_rules/person_id_validator.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/drop_participants_without_ppi_or_ehr_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/person_id_validator_test.py
* [DC-706] Separate out queries for missing basics and missing ehr data
* [DC-706] Consider all pid tables for deletion
* [DC-706] Sandbox person rows before deleting
* [DC-706] Use dict and add back basics constant
[DC-706]: https://precisionmedicineinitiative.atlassian.net/browse/DC-706
[DC-706]: https://precisionmedicineinitiative.atlassian.net/browse/DC-706
[DC-706]: https://precisionmedicineinitiative.atlassian.net/browse/DC-706
[DC-706]: https://precisionmedicineinitiative.atlassian.net/browse/DC-706
=> [DC-706] Modify parameters of cleaning rule from DC-584

data_steward/cdr_cleaner/cleaning_rules/ehr_submission_data_cutoff.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/ehr_submission_data_cutoff_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/ehr_submission_data_cutoff_test.py
Fix submission cutoff date comparison by using '1900-01-01' for null values
=> [DC-1479] EHR data cutoff invalid query for tables without datetime fields

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/update_invalid_zip_codes.py, data_steward/common.py, data_steward/resource_files/schemas/pipeline_tables/zip3_lookup.json, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/update_invalid_zip_codes_test.py
* Added `zip3_lookup` table constant to `common.py`
* Created `update_invalid_zip_codes.py` module to update any zip codes that are less than 5 digits and/or don't match a value in the `zip3_lookup` view.
* Created `update_invalid_zip_codes_test.py` module to test functionality of the main module
* Created a schema file for `zip3_lookup` table which will only be used for the integration test module since it is actually a view in the pipeline tables dataset
* Added CR to `RDR_CLEANING_RULES` list
=> [DC-1633] Create cleaning rule to update invalid ZIP entries

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_height_weight_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/birth_information_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/cope_survey_response_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/explicit_identifier_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/geolocation_concept_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/motor_vehicle_accident_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/organ_transplant_concept_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/repopulate_person_controlled_tier_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/drop_cope_duplicate_responses_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/free_text_survey_response_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/identifying_field_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/negative_ages_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/replace_standard_id_in_domain_tables_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/unit_normalization_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/valid_death_dates_test.py
* removes unnecessary table drops and recreations.  all tables are created with defined schemas by base class.
* utilizes `cls.fq_table_names` as intended to create/delete tables from base class.
* removes superfluous copy function in favor of existing client object copy function.
* removes creating new client objects in tests when the base client object is already available.
* removes redundant test teardowns that are overwriting the same definition in the base class.
=> [DC-1663] Fix bad test smells

data_steward/cdr_cleaner/cleaning_rules/drop_zero_concept_ids.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/drop_zero_concept_ids_test.py
* [DC-1661] Exclude death table
[DC-1661]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1661
=> [DC-1661] Exclude death table from cleaning rule to drop zero concept ids

data_steward/cdr_cleaner/cleaning_rules/valid_death_dates.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/valid_death_dates_test.py
excluded records that have death before any ppi records.
=> [DC-1643] ValidDeathDates should remove death_dates occurring before any PPI response

data_steward/cdr_cleaner/clean_cdr.py
Remove repeated cleaning rules and reorder the cleaning rules to follow the classification
=> [DC-1742] Remove Duplicate rule instances in RT clean list

data_steward/cdr_cleaner/cleaning_rules/deid/registered_cope_survey_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/registered_cope_survey_suppression_test.py
* removes the concepts from the list of suppressions
* updates the integration test to make sure the removal worked
=> [DC-1747] removing suppression of cope concepts in registered tier

data_steward/cdr_cleaner/cleaning_rules/deid/registered_cope_survey_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/registered_cope_survey_suppression_test.py
* suppresses concepts 715724 and 715725 since all pertinent data is removed "null all string fields" rule
* adds test cases to cleaning rule integration test
=> [DC-1745] suppress useless cope concepts in registered tier

data_steward/cdr_cleaner/cleaning_rules/generalize_state_by_population.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/generalize_state_by_population_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/generalize_state_by_population_test.py
* limit the update statement to only impact state participant survey records
* update unit test to validate it only updates records where observation_source_concept_id = 1585249
=> [DC-1748] fix state generalization by population rule

data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters.py
* [DC-1738] Update jinja comments with correct tickets
[DC-1738]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1738
=> [DC-1738] Comments in `clean_ppi_numeric_fields_using_parameters.py` SQL are backward

.circleci/config.yml, data_steward/init_env.sh
* is not the optimal update, but just trying to get circleci back up before the dockerized version is ready.
* changes to a new image
* uses the python orb to set up the virtual environment
* installs google-cloud-sdk directly
* uses the orb to set up caching and removes the current environment caching mechanism
* is intended to be overriden by DC-1820 PR
* will still fail due to linting errors to be resolved in DC-1839 PR
=> [DC-1811] circleci limited update

data_steward/gcloud/gcs/__init__.py, tests/integration_tests/data_steward/gcloud/gcs_client_test.py, tests/unit_tests/data_steward/gcloud/gcs/gcs_test.py
A helper function called empty_bucket() has been created.  Any additional kwargs that may be supplied list_blob() are passed along for deletion as well (e.g.  To empty the bucket starting at a given prefix: `StorageClient.empty_bucket('bucket', prefix='prefix')`).
This work includes integration and unit tests.
=> [DC-1970] Define empty_bucket(name: str) helper method for gcloud.gcs.StorageClient()

data_steward/validation/participants/writers.py, tests/unit_tests/data_steward/validation/participants/writers_test.py
1. Updated write_to_result_table(project, dataset, site, match_values) found in    data_steward/validation/participants/writers.py to incorperate gcloud.gcs.StorageClient()
2. Updated test_write_to_result_table_error and test_write_to_result_table to reflect the changes made to write_to_result_table(project, dataset, site, match_values).
=> [DC-1967] Updated write_to_result_table to incorperate gcloud.gcs.StorageClient()

tests/integration_tests/data_steward/retraction/retract_data_gcs_test.py
replaced google.cloud.storage with StorageClient, removed _empty_bucket() helper method and replaced it with the new empty_bucket() helper method, and replaced string concatenation with f-string.
=> [DC-1975] replaced google.cloud.storage with StorageClient

tests/integration_tests/data_steward/validation/ehr_union_test.py
Bug fix for ehr_union integration test.
=> [DC-2006] `ehr_union_test.py` helper function `_load_datasets()` does not load from RDR_PATH

tests/integration_tests/data_steward/bq_utils_test.py
The following functions have been updated to utilize the new StorageClient and its functionality.
test_load_csv()
test_load_cdm_csv()
test_query_result()
test_load_ehr_observation()
=> [DC-1969] Update tests.integration_tests.bq_utils_tests to use gcloud.gcs.StorageClient()

tests/integration_tests/data_steward/tools/combine_ehr_rdr_test.py
Update the following method:
@staticmethod
def _upload_file_to_bucket(bucket, dataset_id, path, table):
and replace any calls to test_util.empty_bucket()
to use gcloud.gcs.StorageClient()
=> [DC-1971] update combine_ehr_rdr_test.py to use gcloud.gcs.StorageClient()

data_steward/gcloud/gcs/__init__.py, data_steward/gcs_utils.py
This function may best be served as a method in StorageClient().  In every case, it relates to a bucket, and bucket functionality is now in StorageClient().  Having this method defined in that class may prove to increase readability and other human factors.  The change is also subtle.  This task does not include removing gcs_utils.get_drc_bucket(...) but instead helps the GCS migration.  If accepted, a new ticket will target replacing existing calls with this new method.
=> [DC-2019] Migrate gcs_utils.get_drc_bucket() to StorageClient()

tests/integration_tests/data_steward/validation/achilles_heel_test.py, tests/integration_tests/data_steward/validation/achilles_test.py, tests/integration_tests/data_steward/validation/ehr_union_test.py, tests/integration_tests/data_steward/validation/main_test.py
Currently, integration test files achilles_heel_test.py, achilles_test.py, ehr_union_test.py, and main_test.py include calls to test_utils.py to empty buckets or have self/re-defined helpers.  Remove and replace calls using test_util.py and helpers with ones to the new StorageClient() instead.
=> [DC-1982] Remove and update calls to test_utils.empty_bucket() in tests

data_steward/validation/app_errors.py, tests/unit_tests/data_steward/validation/app_errors_test.py
* GCP monitoring is configured to monitor for warnings or higher in the application
* should remove redundant messaging from the application now.
* update the unit tests to expect alert removal
=> [DC-2051] removing slack messaging for exceptions

data_steward/admin/admin_api.py, data_steward/admin/key_rotation.py, tests/run_tests.sh, tests/unit_tests/data_steward/admin/admin_api_test.py
* remove ability to send messages from admin api to slack channel
* use f-strings to match rest of code base conventions
* update the unit test to expect log messages instead of slack post messages
* update the test runner script to run a test(s) based on a test filename pattern instead of a filepath.  (adds back a functionality that was removed by a previous commit.)
=> [DC-2054] remove slack notifications from admin api

tests/integration_tests/data_steward/bq_utils_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/unit_normalization_test.py, tests/integration_tests/data_steward/gcs_utils_test.py, tests/integration_tests/data_steward/metrics/required_labs_test.py, tests/integration_tests/data_steward/tools/top_heel_errors_test.py, tests/test_util.py
DC-2053 targets the last remaining "empty_bucket(...)" calls outside of `gcs_utils`.  In fact, before this PR, there were no calls to gcs_utils at all -- the function was already deleted.  However,`test_util.empty_bucket(...)` remained, and some hidden functions still existed.  This PR removes the last of empty_bucket(...) calls outside of `StorageClient.empty_bucket(...)`.  Hooray 🎉.
Diligence is required here because testing their replacements is tricky at best; they were used in tests themselves.  So care was taken to ensure their replacement matched the existing call.  The `StorageClient.empty_bucket(...)` (the replacement) is already used in tests, and has been thoroughly unit- and integration-test tested.
=> [DC-2053] Remove last remaing empty_bucket() calls found in tests

data_steward/validation/main.py
gcs_utils.get_metadata() call in validation/main.py was replaced with StorageClient.get_blob_metadata(). gcs_utils.get_metadata() is used only once in the curation project.
=> [DC-2057] Replace gcs_utils.get_metadata() calls with StorageClient.get_blob_metadata()

data_steward/cdr_cleaner/cleaning_rules/deid/generalize_cope_insurance_answers.py, data_steward/tools/delete_stale_test_datasets.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/generalize_cope_insurance_answers_test.py
In addition to what the title says, I added sandbox creation SQL and test for `GeneralizeCopeInsuranceAnswers`, as discussed in the ticket comments: https://precisionmedicineinitiative.atlassian.net/browse/DC-1935?focusedCommentId=106158
=> [DC-1935] Add the list of sandbox table names to the `GeneralizeCopeInsuranceAnswers` cleaning rule

data_steward/gcs_utils.py, tests/integration_tests/data_steward/gcs_utils_test.py, tests/integration_tests/data_steward/validation/main_test.py, tests/test_util.py
- Replaces test_util.read_cloud_file(bucket, name) call with get_blob(blob_name).download_as_text() from StorageClient() in tests/integration_tests/data_steward/validation/main_test.py.
- Removes read_cloud_file(bucket, name) function in tests/test_util.py. No longer needed or used.
- Removes get_object(bucket, name,as_text=True) function in data_steward/gcs_utils.py. No longer needed or used.
- Removes test_get_object() method in tests/integration_tests/data_steward/gcs_utils_test.py. No longer needed.
- Removes gcs_utils import in tests/test_utils.py. No longer needed or used.
=> [DC-2038] Remove gcs_utils.get_object(...) and test_utils.read_cloud_file(...)

data_steward/validation/app_errors.py, data_steward/validation/main.py, tests/unit_tests/data_steward/gcloud/gcs/gcs_test.py, tests/unit_tests/data_steward/validation/main_test.py
- Replaces `gcs_utils.get_hpo_bucket(hpo_id)` method calls in ` _upload_achilles_files(…)` and `process_hpo(...)` with `StorageClient().get_hpo_bucket(hpo_id)` in data_steward/validation/main.py.
- Replaces `gcs_utils.upload_object(...)` in `_upload_achilles_files(...)` from data_steward/validation/main.py.'
- Updates` test_unset_bucket(...) `and relocates it from tests/unit_tests/data_steward/validation/main_test.py to tests/unit_tests/data_steward/gcloud/gcs/gcs_test.py.
- Updates `test_validate_all_hpos_exception(...)` and `test_process_hpo_ignore_dirs(...)` in tests/unit_tests/data_steward/validation/main_test.py.
- Adds `self.message = msg` in `class BucketNotSet(RuntimeError)` from data_steward/validation/app_errors.py.
=> [DC-2075] Replace gcs_utils.get_hpo_bucket(hpo_id) calls with StorageClient().get_hpo_bucket(hpo_id)

tests/integration_tests/data_steward/tools/top_heel_errors_test.py
- Previous test method used gcs_utils to get a string and then used the string to create a bucket.  This change uses the string directly to create a bucket, eliminating the intermediate step and removing gcs_utils from the file entirely.
=> [DC-2084] Refactor test to use buckets directly and phase out gcs_utils

data_steward/tools/consolidated_reports/get_all_achilles_reports.py, data_steward/tools/consolidated_reports/get_all_results_html.py, data_steward/tools/consolidated_reports/main.py, data_steward/tools/consolidated_reports/query_reports.py
Replaces `gcs_utils.get_hpo_bucket(hpo_id)` calls in data_steward/tools/consolidated_reports/query_reports.py, data_steward/tools/consolidated_reports/get_all_results_html.py, and data_steward/tools/consolidated_reports/main.py with `StorageClient().get_hpo_bucket(hpo_id)`.
=> [DC-2070] Replace gcs_utils.get_drc_bucket(hpo_id) calls in query_reports.py

tests/integration_tests/data_steward/validation/achilles_test.py
Remove use of strings in favor of buckets.  Empty_bucket() accepts a string or bucket, and the get_bucket() call is no longer needed.
=> [DC-2077] Modernize integration tests in achilles_test to use GCS

data_steward/validation/main.py, tests/integration_tests/data_steward/validation/export_test.py
- Replaces `gcs_utils.get_hpo_bucket(hpo_id)` method calls in save_datasources_json(…), upload_string_to_gcs(…), and run_export(…) with `StorageClient().get_hpo_bucket(hpo_id)` in data_steward/validation/main.py.
- Replaces `gcs_utils.upload_object()` calls with StorageClient.Blob.upload_from_file() in the same functions mentioned above.
- Replaces `gcs_utils.get_hpo_bucket(hpo_id)` method calls in test_run_export_with_target_bucket_and_datasource_id(...) with `StorageClient().get_hpo_bucket(hpo_id)` in tests/integration_tests/data_steward/validation/export_test.py.
=> [DC-2069] Replace gcs_utils in main.save_datasources_json()

data_steward/retraction/retract_data_gcs.py, tests/integration_tests/data_steward/retraction/retract_data_gcs_test.py
*Removes `gcs_utils` from tests/integration_tests/data_steward/retraction/retract_data_gcs_test.py.
*Implements the new `StorageClient` in data_steward/retraction/retract_data_gcs.py
=> [DC-2083] Modernize integration tests in retract_data_gcs_test.py

data_steward/bq_utils.py, data_steward/constants/validation/main.py, data_steward/validation/main.py, tests/integration_tests/data_steward/bq_utils_test.py, tests/integration_tests/data_steward/validation/achilles_test.py, tests/integration_tests/data_steward/validation/main_test.py, tests/unit_tests/data_steward/validation/app_errors_test.py, tests/unit_tests/data_steward/validation/main_test.py
- The integration tests in main_test.py use gcs_utils in several places. These tests require updates.
- Sections of these tests (and the code under test) rely on strings of date and times.  These are then converted to `datetime` objects later on.  The new client returns these dates and times as `datetime` objects directly.  However, these objects supply time zone-aware objects (UTC). In the past these `datetime` objects were time zone naive, so keeping compatibility required time zone information stripped out.
=> [DC-2086] Modernize integration tests in main_test to use GCS

data_steward/constants/validation/participants/validate.py, data_steward/validation/participants/validate.py, tests/integration_tests/data_steward/validation/participants/validate_test.py
Regarding `tests/integration_tests/data_steward/validation/participants/validate_test.py`:
[14](https://github.com/all-of-us/curation/pull/1142/files#diff-7f674a2a861ab3b7729a706943248dc33339696ca61e2be79c6383e6fbd507ffR270) and [17](https://github.com/all-of-us/curation/pull/1142/files#diff-7f674a2a861ab3b7729a706943248dc33339696ca61e2be79c6383e6fbd507ffR273) are the new test cases for street 1 & 2 combined comparison. The rest of the updates in the test file are not directly related to this 1 & 2 combined comparison: I reorganized them so that I do not need to create new test records.
=> [DC-2131] Add street 1 & 2 combined comparison to DRC street address comparison

data_steward/ci/test_buckets.py, data_steward/tools/load_archived_submission.py, data_steward/tools/load_vocab.py, tests/integration_tests/data_steward/tools/load_vocab_test.py
*Uses `StorageClient` to create new storage client instances in data_steward/tools/load_vacob.py and tests/integration_tests/data_steward/tools/load_vocab_test.py by replacing `storage.Client` calls and function parameters with `StorageClient`
=> [DC-2170] Use StorageClient to create client instances

data_steward/gcloud/bq/__init__.py, data_steward/requirements.txt, tests/integration_tests/data_steward/gcloud/bq_client_test.py, tests/unit_tests/data_steward/gcloud/bq/bq_test.py
Defines location and package for our extended class to live, data_steward/gcloud/bq.
Adds OpenTelemetry package requirements to data_steward/requirements.txt.
Adds OpenTelemetry functionality inside the constructor of the `BigQueryClient`.
Adds `BQC` integration test in tests/integration_tests/data_steward/gcloud/bq_client_test.py.
Adds `BQC` unit test in tests/unit_tests/data_steward/gcloud/bq.
=> [DC-1599] [BigQuery] Define BigQuery client

data_steward/cdr_cleaner/cleaning_rules/covid_ehr_vaccine_concept_suppression.py, data_steward/init_env.sh, docker/develop/scripts/funcs.sh, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/covid_ehr_vaccine_concept_suppression_test.py
[DC-2120] update covid_ehr_vaccine_concept_suppression.py to allow COVID-19 vaccines added 1 year before cutoff_date
* Updated integration tests
* Update vocabulary dataset in init_env.sh
[DC-2120]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2120] Allow covid EHR drug info to remain in the Registered Tier CDR

data_steward/cdr_cleaner/cleaning_rules/covid_ehr_vaccine_concept_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/covid_ehr_vaccine_concept_suppression_test.py
The main logic was already updated with DC-2120. This update is mainly for updating the test cases to confirm the suppression is still working as expected.
Through the testing, we found the following. I included the fix for that in this PR.
https://precisionmedicineinitiative.atlassian.net/browse/DC-2120?focusedCommentId=112285
=> [DC-2140] Confirm removal of covid EHR drug info from the Registered Tier CDR

tests/integration_tests/data_steward/cdr_cleaner/clean_cdr_engine_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/bigquery_tests_base.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/generalize_state_by_population_test.py, tests/integration_tests/data_steward/metrics/required_labs_test.py, tests/integration_tests/data_steward/retraction/retract_data_bq_test.py, tests/integration_tests/data_steward/retraction/retract_deactivated_pids_test.py, tests/integration_tests/data_steward/tools/delete_stale_test_datasets_test.py, tests/integration_tests/data_steward/tools/fitbit/generate_fitbit_dataset_test.py, tests/integration_tests/data_steward/tools/generate_ehr_upload_pids_test.py, tests/integration_tests/data_steward/tools/recreate_person_test.py, tests/integration_tests/data_steward/utils/sandbox_test.py, tests/integration_tests/data_steward/validation/ehr_union_test.py
- Implements the new BigQueryClient by replacing bq.get_client(...) calls in tests/integration_tests.
- Excludes: 
tests/integration_tests/data_steward/validation/participants/create_update_drc_id_match_table_test.py.
tests/integration_tests/data_steward/validation/participants/validate_test.py.
tests/integration_tests/data_steward/validation/participants/store_participant_summary_results_test.py
=> [DC-2185] Replace bq.get_client(...) calls in integration tests

data_steward/tools/create_rdr_snapshot.py, data_steward/tools/fitbit/generate_fitbit_dataset.py, data_steward/tools/import_rdr_omop.py, data_steward/tools/load_archived_submission.py, data_steward/tools/load_vocab.py
Implements the new BigQueryClient by replacing bq.get_client(...) calls in data_steward/tools folder files:
- data_steward/tools/fitbit/generate_fitbit_dataset.py
- data_steward/tools/import_rdr_omop.py
- data_steward/tools/create_rdr_snapshot.py
- data_steward/tools/load_archived_submission.py
- data_steward/tools/load_vocab.py
=> [DC-2249] Replace bq.get_client(...) calls in data_steward/tools

data_steward/tools/add_hpo.py, data_steward/tools/clean_project_datasets.py, data_steward/tools/copy_dataset_to_output_prod.py, data_steward/tools/recreate_person.py, data_steward/tools/snapshot_by_query.py, tests/integration_tests/data_steward/tools/recreate_person_test.py, tests/unit_tests/data_steward/tools/add_hpo_test.py, tests/unit_tests/data_steward/tools/snapshot_by_query_test.py
Implements the new `BigQueryClient` by replacing `bq.get_client(...)` calls in data_steward/tools folder files:
- data_steward/tools/add_hpo.py
- data_steward/tools/clean_project_datasets.py
- data_steward/tools/copy_dataset_to_output_prod.py
- data_steward/tools/recreate_person.py
- data_steward/tools/snapshot_by_query_test.py
- Associated tests
=> [DC-2247] Replace bq.get_client(...) calls in data_steward/tools

data_steward/tools/create_tier.py, data_steward/tools/delete_stale_test_datasets.py, data_steward/tools/generate_ehr_upload_pids.py, data_steward/tools/migrate_cdm52_to_cdm531.py, data_steward/tools/recreate_cope_concepts.py, data_steward/tools/run_deid.py, data_steward/tools/snapshot_by_query.py, data_steward/validation/participants/snapshot_validation_dataset.py, tests/integration_tests/data_steward/tools/delete_stale_test_datasets_test.py, tests/integration_tests/data_steward/validation/participants/validate_test.py, tests/test_util.py, tests/unit_tests/data_steward/tools/create_tier_test.py, tests/unit_tests/data_steward/tools/delete_stale_test_datasets_test.py, tests/unit_tests/data_steward/tools/migrate_cdm52_to_cdm531_test.py
Implements the new BigQueryClient by replacing bq.get_client(...) calls in data_steward/tools folder files:
- data_steward/tools/create_tier.py
- data_steward/tools/delete_stale_test_datasets.py
- data_steward/tools/generate_ehr_upload_pids.py
- data_steward/tools/migrate_cdm52_to_cdm531.py
- data_steward/tools/recreate_cope_concepts.py
- data_steward/tools/run_deid.py
- data_steward/tools/snapshot_by_query.py
data_steward/validation/participants/snapshot_validation_dataset.py
Associated tests
=> [DC-2250] Replace bq.get_client(...) calls in data_steward/tools

data_steward/cdr_cleaner/cleaning_rules/identifying_field_suppression.py, data_steward/cdr_cleaner/cleaning_rules/ppi_branching.py, tests/unit_tests/data_steward/cdr_cleaner/args_parser_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/base_cleaning_rule_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/ppi_branching_test.py, tests/unit_tests/data_steward/cdr_cleaner/reporter_test.py
Replaces all bq.get_table_schema(...) calls with BigQueryClient.get_table_schema(...) in data_steward/cdr_cleaner/clearning_rules folder files and associated unit tests.
=> [DC-2172] Replace bq.get_table_schema(...) calls in data_steward/cdr_cleaner/clearning_rules

data_steward/tools/fitbit/generate_fitbit_dataset.py, data_steward/tools/import_rdr_omop.py, data_steward/tools/load_archived_submission.py, data_steward/tools/load_vocab.py, tests/integration_tests/data_steward/tools/combine_ehr_rdr_test.py, tests/integration_tests/data_steward/tools/load_vocab_test.py, tests/unit_tests/data_steward/tools/exclude_site_submission_test.py, tests/unit_tests/data_steward/tools/generate_ehr_upload_pids_test.py
Replaces all `bq.get_table_schema(...)` calls with `BigQueryClient.get_table_schema(...)` in data_steward/tools folder files and associated unit tests.
=> [DC-2216] Replace bq.get_table_schema(...) calls in data_steward/tools

data_steward/analytics/cdr_ops/rdr_export_qc.py, data_steward/cdr_cleaner/cleaning_rules/backfill_pmi_skip_codes.py
`data_steward/cdr_cleaner/cleaning_rules/backfill_pmi_skip_codes.py` ... Only the linting for the SQL statement is updated. No change in the logic.
=> [DC-2254] Refactor qrid check in RDR export notebook

data_steward/gcloud/bq/__init__.py, data_steward/utils/bq.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/motor_vehicle_accident_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/domain_alignment_test.py, tests/unit_tests/data_steward/gcloud/bq/bq_test.py
- Relocates `to_scalar(...)`, `get_table_count(...)`, `list_tables(...)`, and `copy_datasets(...)` helper functions from data_steward/utils/bq.py to be methods of the new `BigQueryClient`.
=> [DC-2188] Relocate bq.py helper functions

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/drop_participants_without_ppi_or_ehr.py, data_steward/cdr_cleaner/cleaning_rules/drop_rows_for_missing_persons.py
* [DC-2351] Update order of CR and add depends_on
[DC-2351]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2351] Change order of `DropParticipantsWithoutPPI` cleaning rule

data_steward/gcloud/bq/__init__.py, data_steward/tools/copy_dataset_to_output_prod.py, data_steward/tools/create_tier.py, data_steward/tools/fitbit/generate_fitbit_dataset.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/motor_vehicle_accident_suppression_test.py, tests/unit_tests/data_steward/gcloud/bq/bq_test.py, tests/unit_tests/data_steward/tools/create_tier_test.py
- Replaces all `bq.copy_datasets(...)` calls with `BigQueryClient.copy_dataset(...)` in data_steward/tools folder.
- Updates associated tests.
=> [DC-2315] Replace bq.copy_datasets(...) calls in data_steward/tools

data_steward/cdr_cleaner/cleaning_rules/ppi_branching.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/explicit_identifier_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/motor_vehicle_accident_suppression_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/ppi_branching_test.py
- Replaces all `bq.dataset_columns_query(...)`  calls by invoking the function using the new `BigQueryClient()`.
- Updates associated tests.
=> [DC-2318] Replace bq.get_create_or_replace_table_ddl(...) calls in cleaning_rules folder

data_steward/tools/add_hpo.py, tests/unit_tests/data_steward/tools/add_hpo_test.py
- I ran the updated script for DC2409 and confirmed that `site_maskings` is updated as expected.
- I added the exceptions for clarity.
- I updated the insert logic since `pipeline_tables_sandbox` does not exist in our dataset.
- I updated the playbook to specify what we need to do in each step.
- Please see the comment section in the JIRA ticket DC2410 for details.
=> [DC-2410] Fix the error that prevents generation of a `pipeline_tables.site_masking` record

data_steward/cdr_cleaner/cleaning_rules/drop_participants_without_ppi_or_ehr.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/drop_participants_without_ppi_or_ehr_test.py
=> [DC-2480] [P0] Remove `DropParticipantsWithoutPPI` from the RT and CT cleaning lists #2

tests/integration_tests/data_steward/tools/delete_stale_test_buckets_test.py, tests/integration_tests/data_steward/tools/delete_stale_test_datasets_test.py
- Removed the `assert` for labels: the logic looks at the real datasets/buckets in the test environment. And the tests do not have full control over what labels are attached to each of the datasets/buckets. I am removing those `assert` statements altogether.
- The logic is tested in the unit tests, so this change does not affect code coverage.
=> [DC-2128] Integration test bug fix

data_steward/cdr_cleaner/clean_cdr_engine.py, data_steward/cdr_cleaner/cleaning_rules/deid/fitbit_pid_rid_map.py, data_steward/cdr_cleaner/cleaning_rules/deid/pid_rid_map.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/bigquery_tests_base.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/ct_pid_rid_map_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/fitbit_pid_rid_map_test.py
- To enable `table_namer`, I needed to change the order of the arguments and make `mapping_dataset_id` and `mapping_table_id` kwarg. This is because `infer_rule` assumes the fourth argument to be `table_namer` -> https://github.com/all-of-us/curation/blob/develop/data_steward/cdr_cleaner/clean_cdr_engine.py#L218
=> [DC-2467] The fitbit `PIDtoRID` rule does not sandbox data

data_steward/cdr_cleaner/cleaning_rules/unit_normalization.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/unit_normalization_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/unit_normalization_test.py
* solves issues with the 5.3 upgrade by changing the write_truncate query to an update query
* adds a record that should be loaded but not modified by the integration test
* fixes any schema issues caused by this rule's use of write truncate
=> [DC-2454] update the unit normalization rule

data_steward/cdr_cleaner/cleaning_rules/deid/repopulate_person_controlled_tier.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/repopulate_person_controlled_tier_test.py
On top of adding more test cases to the integration test, I tested the updated logic is working against the DEID data from the past. Please see the JIRA ticket's comment section.
=> [DC-2273] [P1] `ethnicity_source_concept_id` and `ethnicity_source_value` values are not broken down in controlled tier

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report8_household_state_genera.py, data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py
-  `cdr_deid_qa_report8_household_state_genera.py` has lots of changes because of `pylint`, but the only notable change is removing [this comment](https://github.com/all-of-us/curation/pull/1330/files#diff-bfc8a31439776b1f1be946f98df34a8a06a6911ecced825491ce2c1029d33b1cL82) that will be no longer relevant after this PR
- `observation_id=122` is added to cover the updated logic in the integration test.
=> [DC-2475] Account for text answers when assigning the invalid code for '1333023'.

data_steward/gcloud/bq/__init__.py, data_steward/tools/create_tier.py, data_steward/tools/fitbit/generate_fitbit_dataset.py, tests/unit_tests/data_steward/gcloud/bq/bq_test.py, tests/unit_tests/data_steward/tools/create_tier_test.py
This was the branch that updated the `bq.copy_dataset` calls: #1212
=> [DC-2458] Update gcloud/bq/__init__.py copy_dataset to expect project as part of input_dataset and output_dataset parameters

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/create_expected_ct_list.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/create_expected_ct_list_test.py
* store curation's expected CT participant list in the rdr sandbox after all the RDR cleaning rules have executed
* intended to help automate the generation of this list for the genomics team
* can be used to identify errors earlier, when lists at combined or CT data stages drop expected participants according to this table
=> [DC-2595] store expected ct list in rdr sandbox dataset

data_steward/resource_files/schemas/rdr/questionnaire_response_additional_info.json
This adds an additional RDR schema, questionnaire_additional_info
=> [DC-2624] Add `questionnaire_response_additional_info` table schema to rdr schema files

data_steward/deid/aou.py
The reason why it is safe to de-duplicate `_mapping_person_src_hpos`:
- `_mapping_person_src_hpos` is referenced only here in the whole DEID process -> [link to the code](https://github.com/all-of-us/curation/blob/develop/data_steward/deid/config/ids/config.json#L39)
- In the SQL above, `_mapping_person_src_hpos` is used in a `SELECT DISTINCT` statement. This DISTINCT statement returns the same result with or without `_mapping_person_src_hpos` having duplicates.
Notes:
- `_mapping_person_src_hpos` is created to deid `observation` table -> [link to the code](https://github.com/all-of-us/curation/blob/develop/data_steward/deid/aou.py#L265)
- Also, see the comment in the JIRA ticket for what I did for debugging/testing.
=> [DC-2376] De-duplicate records in _mapping_person_src_hpos

data_steward/cdr_cleaner/cleaning_rules/truncate_rdr_using_date.py
* [DC-2630] Update truncate_rdr_using_date for survey conduct
[DC-2630]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2630] Update truncate_rdr_using_date cleaning rule to include the survey_conduct table

data_steward/cdr_cleaner/cleaning_rules/negative_ages.py
* [DC-2633] Update negative_ages for survey conduct
[DC-2633]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2633] Update negative_ages cleaning rule to include the survey_conduct table

data_steward/cdr_cleaner/cleaning_rules/remove_participants_under_18years.py
* [DC-2632] Update remove_participants_under_18years with CATI tables
[DC-2632]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2632] Update remove_participant_under_18years cleaning rule to include the survey_conduct table

data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables_test.py
**1. `data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables.py`:**
- No logic update is necessary because it gets the list of mapping tables in the dataset and creates ext tables for them. -> As long as `_mapping_survey_conduct` exists, `survey_conduct_ext` will be created with this CR.
- Updated the docstring for `get_table_fields_str()` so it better represents what it does.
- Removed the local constants and use the constants from `common` instead.
**2. `tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables_test.py` and
3. `tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables_test.py`:**
- Added test cases for `survery_conduct` to make sure this CR works with it as expected.
=> [DC-2628] Update generate_ext_tables.py for survey_conduct_ext

data_steward/analytics/cdr_ops/rdr_export_qc.py
* [DC-2640] Add rdr cutoff check
[DC-2640]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2640] Add a check to the RDR QA notebook to verify the date cut off applies to the survey_conduct table

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv
- `COOK_COUNTY` is missing, so I included it as well. I double-checked there is no other HPO site missing from the list.
=> [DC-2695] Add UnityPoint Health to pipeline

data_steward/analytics/cdr_ops/rdr_export_qc.py
- Closed [the old PR](https://github.com/all-of-us/curation/pull/1392) without merging since there was a merge conflict with [DC-2640](https://github.com/all-of-us/curation/pull/1395) and solving the conflict got a little messy
- In addition to the original update, I also updated `query = JINJA_ENV.from_string("""~~~` statement from DC-2640 since it had some grammatical errors.
=> [DC-2641] #2 Verify whether or not all COPE surveys have one ID in the concept ID field

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/populate_survey_conduct_ext.py, data_steward/common.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/populate_survey_conduct_ext_test.py
- See the comment in the JIRA ticket for DC-2627. This new cleaning rule assumes `survey_conduct_ext` and `questionnaire_response_additional_info` can be joined on `survey_conduct_id = questionnaire_response_id`.
=> [DC-2627] Create a cleaning rule that will populate the `survey_conduct_ext` table

data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map_test.py
- Updated docstrings to better represent what this CR does.
- Refactored the mapping query to handle both `observation` and `survey_conduct`.
- Added sandbox and delete queries for `survey_conduct`.
- Added the test case for `survey_conduct` in the integration test.
- Updated the test case for `observation` so it is easier to understand.
=> [DC-2637] Update questionnaire_response_id_map cleaning rule to include the survey_conduct table

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/monkeypox_concept_suppression.py, data_steward/resource_files/cdr_cleaner/monkeypox_concept_suppression/monkeypox_concepts.csv, data_steward/resources.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/monkeypox_concept_suppression_test.py
- I ended up building from `BaseCleaningRule` instead of extending `AbstractBqLookupTableConceptSuppression` since the one-year holdout condition would make the script more complicated with `AbstractBqLookupTableConceptSuppression`.
=> [DC-2711] Suppress Monkeypox Data from Registered Tier Only for One-Year

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/date_unshift_cope_responses.py, data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map.py, data_steward/cdr_cleaner/cleaning_rules/deid/survey_version_info.py, data_steward/cdr_cleaner/cleaning_rules/populate_survey_conduct_ext.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/survey_version_info_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/populate_survey_conduct_ext_test.py
* shuffling the generation table creation, population, and remapping cleaning rules
* removes sandbox and delete queries (and their tests) specific to the survey_conduct table
* changes the survey_version_info query from a create or replace statement to an update statement
* updates tests impacted by the changes
=> [DC-2730] remap survey_conduct_ext table foreign key values

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/truncate_fitbit_data_test.py
- [DC-2731](https://github.com/all-of-us/curation/pull/1412/files) updated the values in `FITBIT_DATE_TABLES`. This change added a few new sandbox tables to the cleaning rule.
- The integration test failed because it used positional arguments for specifying `fq_sandbox_table_name`. The newly added sandbox tables changed the positions in the list.
- This PR updates the logic so that the test uses the correct `fq_sandbox_table_name` regardless of the position of the sandbox table in the list.
=> [DC-2737] Update truncate fitbit cleaning rule test to accommodate new list of sandbox tables

.circleci/config.yml
- Yapf corrected the indentation line 9-20. I confirmed that the `.yml` file works with no problem with the updated indentation. Please see the comment section of the JIRA ticket DC-2776.
=> [DC-2776] Serialize CircleCi nightly workflow

data_steward/constants/tools/create_combined_backup_dataset.py, data_steward/tools/create_combined_backup_dataset.py, data_steward/tools/create_combined_dataset.py, tests/unit_tests/data_steward/tools/create_combined_backup_dataset_test.py
`create_combined_backup_dataset.py`:
- The EHR consent table will be created in the combined sandbox dataset, not the combined backup dataset.
- The parameter name `combined_dataset` is updated to `combined_backup` for clarity. Docstrings are also updated accordingly.
`create_combined_dataset.py`:
- `create_datasets()` is updated to `create_dataset()` so it can be used in `create_combined_backup_dataset.py` to create the sandbox dataset.
=> [DC-2757] Update creation of `_ehr_consent` table to a sandbox dataset

data_steward/common.py, data_steward/retraction/retract_data_bq.py, data_steward/retraction/retract_data_gcs.py, data_steward/retraction/retract_utils.py, data_steward/retraction/run_retraction.py, data_steward/validation/main.py, tests/integration_tests/data_steward/retraction/retract_data_bq_test.py, tests/integration_tests/data_steward/retraction/retract_data_gcs_test.py, tests/unit_tests/data_steward/retraction/retract_utils_test.py
*See the comment in DC-2904 for how we can run these updated scripts.*
--
`run_retraction.py`
- Updated `create_lookup_table()` so it can accept `if not exists` condition for the `create table` statement.
- Updated comments and docstrings to the latest.
`retract_data_gcs.py`
- No update is needed.
`retract_data_bq.py`
- Updated so it also works for the datasets that are NOT `COMBINED`, `DEID`, and `FITBIT`.
- Rewrote some of the functions for simplicity.
`retract_utils.py`
- Removed [this condition](https://github.com/all-of-us/curation/pull/1455/files#diff-7d103e313f336b657fc1480eb54049d0c49533fd1b0bfb2611db42bab5b6f108L122) that was omitting `sandbox` datasets no matter what. `retract_utils_test.py` is updated accordingly.
`retract_data_bq_test.py`
- Added test cases for each dataset …
=> [DC-2904] Update retraction scripts for EHR, RDR, and UNIONED EHR datasets

data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py, data_steward/resources.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_mapping_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/clean_mapping_test.py
- For EHR datasets, the `table_id` was overwritten to a wrong value.
- I fixed the logic. I added test cases to ensure the update is working as expected.
- I updated `fields_for()` in `resources.py` so it can work for `unioned_ehr_xyz` tables in EHR datasets.
=> [DC-3007] Update clean_mapping cleaning rule to correctly handle EHR datasets

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/free_text_survey_response_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/free_text_survey_response_suppression_test.py
* Update FreeTextSurveyResponseSuppression to suppress case-insensitive free text concept codes
* Add FreeTextSurveyResponseSuppression to registered tier cleaning classes
* Update integration tests to cover case-insensitive concept codes
=> [DC-2799] Update cleaning rule for case-insensitive free text suppression

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_base_qa_report1.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_clean_qa_report1.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report11_covid_concept_no_suppression.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report12_extra.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report1_generalization_rule.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report2_row_suppression.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report3_col_suppression.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report4_dateshift.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report5_row_suppression_icd.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report6_fitdata.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report7_cope_survey.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report8_household_state_genera.py
1 changed the format by using JINJA_ENV and impersonation
2 main changes include the following
1) DC-2374, DC-2373, these two were basically same, 
The rule has changed and now we are including COVID concepts. Update the notebook to include the latest rule, based on The latest list is COPE - All Surveys Privacy Rules, which I put into curation_sandbox.temp_cope_privacy_rules
as seen in cdr_deid_qa_report7_cope_survey.py
2)  DC-2377, DC-2785
changes can be seen in the cdr_deid_qa_report8_household_state_genera.py (query5.1, 5.2)
and  cdr_deid_qa_report10_extra.py, 
3) DC-2391
Remove 4b sandbox._site_mappings from cdr_deid_qa_report10_extra.py
4)DC-2372
cdr_deid_qa_report3_col_suppression.py has this check 13 Verify the NOTE_NLP table is suppressed.
=> [DST-347] Update rt_cdr_qc notebooks

data_steward/analytics/cdr_ops/incremental_load_qc.py, data_steward/cdr_cleaner/manual_cleaning_rules/remediate_basics.py, data_steward/tools/run_basics_remediation.py, tests/integration_tests/data_steward/cdr_cleaner/manual_cleaning_rules/remediate_basics_test.py
I am fixing the scripts based on the execution from 2/14.
- Updated `insert` statements in the main hotfix script so it will also insert new records. (It was inserting only records that had corresponding records in the source dataset.) 
- Introduced `exclude_lookup_table` and `exclude_lookup_dataset` to achieve the above.
- Added a new test case, `test_no_exclusion,` to test whether the above is working as expected.
- Added a new test case (`person_id==3`) to test whether new participants are correctly inserted into the output.
- Deleted `QC 2-2` from the QC notebook as we saw yesterday the check was meaningless.
NOTE: `person_ext` tables' state-related columns can be `NULL` if the participants are new since the incremental dataset. …
=> [DC-3063] Update insert statements/ Update QC notebook

data_steward/retraction/run_retraction.py, data_steward/tools/copy_dataset_to_output_prod.py, data_steward/tools/run_basics_remediation.py
I searched our code base for any `release_tag` modifiers such as regex substitution, slicing, indexing, or modifiers such as upper() that would cause an error.  Fortunately, Lauren's [commit](https://github.com/all-of-us/curation/pull/1457/commits/415d719c3735ba5139c430119390eea599fff09f) already handled most of the cases, so the only contribution I could make was updating a single case check.
Other than that, I made a nitpick change to two unused variables.  By convention, `_` is often used.
=> [DC-3065] Update scripts to handle two-digit release (2022q4r10) correctly

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/survey_version_info.py, data_steward/cdr_cleaner/cleaning_rules/populate_survey_conduct_ext.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/bigquery_tests_base.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/survey_version_info_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/populate_route_ids_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/populate_survey_conduct_ext_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid_test.py
Note: I also moved the currently commented `SurveyConductDateShiftRule` rule from the original data stages to the combined date stage. If this needs to remain in the original stages, request a change.
=> [DC-2749] Add COPESurveyVersionTask to combined cleaning classes to run at the end of all other cleaning classes.

data_steward/cdr_cleaner/manual_cleaning_rules/remediate_basics.py
- The RT deid dataset has partitioned tables. With partitioned tables, we need to specify column names for DMLs, because those have a `_PARTITIONTIME` column, and `SELECT *` is too ambiguous in such a case. 
- The solution is to specify columns in the DDLs. This change will not break the DDLs for non-partitioned tables.
=> [DC-3064] Add column names for partitioned tables

data_steward/gcloud/bq/__init__.py, data_steward/tools/create_rdr_snapshot.py, tests/unit_tests/data_steward/gcloud/bq/bq_test.py
`data_steward/tools/create_rdr_snapshot.py` is not taking full advantage of the tools at its disposal via the `gcloud/bq/__init__.py` functionality.  Instead, this script defines `copy_raw_rdr_tables` to copy the contents of one dataset to another.   This PR deletes the `copy_raw_rdr_tables(...)` function and replaces the call with our implementation in the BigQueryClient, removing code duplication.
However, when `copy_raw_rdr_tables` created each table, it used a job_config (`CopyJobConfig`) to make each table with a specified write disposition which was later passed to the core copy_table method.  An optional parameter now facilitates this functionality.  If none is provided, a default is created.
This PR adds a feature to add labels `table_id`, `copy_from`, and `copy_to` to the copied …
=> [DC-3014] Use `bq.copy_dataset` in `create_rdr_snapshot` instead of `copy_raw_rdr_dataset`

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/backfill_survey_records.py, data_steward/cdr_cleaner/cleaning_rules/backfill_the_basics.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/backfill_the_basics_test.py
- Creating the abstract class `AbstractBackfillSurveyRecords` for the backfill.
- `BackfillTheBasics` and its test are also included in this PR as the pilot case for using the abstract class.
- `BackfillTheBasics` does not use the arg `additional_backfill_conditions`. It will be used when implementing the backfill for the Overall Health survey (`DC-3099`)
- The original cleaning rule used to add `1000000000000` for the newly assigned `observation_ids`. ([BackfillPmiSkipCodes](https://github.com/all-of-us/curation/blob/develop/data_steward/cdr_cleaner/cleaning_rules/backfill_pmi_skip_codes.py#L84)). With `AbstractBackfillSurveyRecords`, new `observation_ids` are created based on the max `observation_id` in `observation`. ([link](https://github.com/all-of-us/curation/pull/1522/files#diff-181 …
=> [DC-3096] [DC-3097] Abstract class for backfill/ Backfill CR for "The Basics"

data_steward/cdr_cleaner/clean_cdr.py, tests/unit_tests/data_steward/cdr_cleaner/clean_cdr_test.py
In data_steward/cdr_cleaner/clean_cdr.py, the function _get_kwargs will fail with an error when it encounters an = operator with key value usage.  This PR fixes the issue and updates a unit test.
=> [DC-3042] ` _get_kwargs` needs to be refactored to accept `=` key/value pairs in `clean_cdr.py`

data_steward/resource_files/schemas/aou_custom/aou_death.json
Except for `aou_death_id`, `src_id`, and `primary_death_record`, the definition is copied from `death.json`.
=> [DC-3130] Add aou_death.json

data_steward/validation/ehr_union.py, tests/integration_tests/data_steward/validation/ehr_union_test.py
- `AOU_DEATH` creation will be handled in `DC-3134.`
- This PR is to suppress the `DEATH` table.
=> [DC-3193] Stop DEATH creation in Unioned EHR

data_steward/cdr_cleaner/cleaning_rules/clean_by_birth_year.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_by_birth_year_test.py
- No change was needed in the logic. I updated the docstring for `setup_rule()` to add more background.
- This cleaning rule runs both on `RDR` and `Unioned_EHR` data tiers. `RDR` data tier does not have an `AOU_DEATH` table, so changing the default `affected_tables` to include `AOU_DEATH` is not a good idea. `setup_rule()` updates affected_tables to the correct list of the tables anyway.
- `SURVEY_CONDUCT` is not included in the default affected_tables for the same reason.
=> [DC-3128] Update `CleanByBirthYear` to include `aou_death`

data_steward/resource_files/scheduled_queries/monitor_nonprod_person_id_violation.txt
- I already updated the scheduled query in our BigQuery. This PR is to update the SQL file to date
- [This trailing comma](https://github.com/all-of-us/curation/pull/1559/files#diff-550818130a2e109e2f2ba6262b720d614d8c39cad4a387fe0948e8b81f2e2a66R75) was grammatically incorrect but it was working without a problem it seems.
=> [DC-3197] Update prod ID violation check CRON job to ignore views

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death_test.py
Because `primary_death_record` can change in each data stage, I added this CR to the following, in addition to `COMBINED_CLEANING_CLASSES`.
- `REGISTERED_TIER_DEID_CLEAN_CLEANING_CLASSES`
- `CONTROLLED_TIER_DEID_CLEAN_CLEANING_CLASSES`
=> [DC-3261] Update `NoDataAfterDeath` to use primary death record, not the earliest death record

data_steward/cdr_cleaner/cleaning_rules/negative_ages.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/negative_ages_test.py
- The cleaning rule can handle the null `death_date` without an update.
=> [DC-3324] Update `NegativeAges` to handle aou_death's NULL death_date

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/suppress_year_of_birth_records_test.py
- The cleaning rule can handle the null `death_date` without an update.
=> [DC-3326] Update `YearOfBirthRecordsSuppression` to handle aou_death's NULL death_date

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_consistency_test.py
- The cleaning rule can handle the null `death_date` without an update.
=> [DC-3322] Update `EnsureDateDatetimeConsistency` to handle aou_death's NULL death_date

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/remove_participant_data_past_deactivation_date_test.py
- The cleaning rule can handle the null `death_date` without an update.
=> [DC-3325] Update `RemoveParticipantDataPastDeactivationDate` to handle aou_death's NULL death_date

data_steward/cdr_cleaner/cleaning_rules/valid_death_dates.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/valid_death_dates_test.py
- The cleaning rule can handle the null death_date without an update.
=> [DC-3323] Update `ValidDeathDates` to handle aou_death's NULL death_date

data_steward/admin/key_rotation.py
=> [DC-3349] Update the key rotation service to rotate keys more frequently than 180 days

data_steward/analytics/cdr_ops/clean_rdr_export_qc.py, data_steward/analytics/cdr_ops/raw_rdr_export_qc.py
- Pylint also updated some formats where it is not directly related.
=> [DC-3413] Update `raw_rdr_export_qc.py` and `clean_rdr_export_qc.py` to run QC on `aou_death`, not `death`

data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death_test.py
- Also updated `table_namer` so it can be referenced correctly
- Also updated `depends_on` to the right value
- Technically, `survey_end_date` is `nullable`, but the column is never `NULL` as defined in the PRD for `survey_conduct`. https://github.com/all-of-us/curation/blob/develop/data_steward/resource_files/schemas/cdm/clinical/survey_conduct.json#L36
=> [DC-3235] Add `survey_conduct` to `NoDataAfterDeath` cleaning rule

data_steward/cdr_cleaner/cleaning_rules/drop_extreme_measurements.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/drop_extreme_measurements_test.py
- Updated the CR's SQL to process in-person vs self-reported PM.
- Cleaned up the main script for readability
- Reorganized the test cases to represent self-report vs in-person PM
=> [DC-3379] Update `DropExtremeMeasurements` to handle self-reported PM

data_steward/constants/tools/create_combined_backup_dataset.py, data_steward/tools/create_combined_backup_dataset.py, data_steward/validation/ehr_union.py
I used different `create_table()` for EHR union and Combined.
- For EHR union, I used `bq_utils.create_standard_table()`, following other CDM tables creation in EHR union. I had to use it because (1) the destination table name needs the prefix `unioned_ehr_`, and (2) this process runs every night and we need the `drop_existing=True` capability when it runs. `bq_utils.create_standard_table()` creates a partitioned table as a result, and it is not a problem since all the other CDM tables are partitioned at this stage. 
- For Combined, I used `client.create_tables()` as it does not require special consideration like EHR union.
For testing, the existing integration tests can cover these updates. No update was needed.
=> [DC-3401] Use `BigQueryClient.create_tables()` instead of `CREATE TABLE` for `aou_death` creation

data_steward/cdr_cleaner/clean_cdr.py
Background:
We apply this suppression in the controlled tier cleaning stage with the help of a cleaning rule. To stop suppressing these records and expand race/ethnicity subcategories, we would need to remove the cleaning rule from the controlled tier cleaning classes.
Scope:
- ~Remove the data_steward/cdr_cleaner/cleaning_rules/race_ethnicity_record_suppression.py cleaning rule from the repo.~
- ~Remove integration test - tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/race_ethnicity_record_suppression_test.py from the repo.~
- ~Remove~ disable the RaceEthnicityRecordSuppression from [CONTROLLED_TIER_CLEANING_CLASSES](https://github.com/all-of-us/curation/blob/4c3006a766cfe7c66d2cd8a67b153be99fbdd2c7/data_steward/cdr_cleaner/clean_cdr.py#L344C4-L344C4) in …
=> [DC-3436] Remove `race_ethnicity_record_suppression.py` to stop suppressing race/ethnicity sub categories

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_part2.py
We are removing the suppression of race/ethnicity subcategories and recreating the person from observation. We would need to add a check in our QC notebooks to verify that no subcategories are being displayed in the person table.
Add a check in controlled_tier_qc to verify that race/ethnicity subcategories don’t exist in the person table.
A check is added to controlled_tier_qc part 2
Check fails if subcategories are identified in the person table.
=> [DC-3440] Add a check in controlled_tier_qc to verify only higher level race/ethnicity is being shown in person after deid

data_steward/tools/generate_unioned_ehr_dataset.sh, data_steward/validation/ehr_union.py, tests/integration_tests/data_steward/validation/ehr_union_test.py, tests/unit_tests/data_steward/validation/ehr_union_test.py
Dear reviewer,
- See the comment section of the JIRA ticket DC-3455 for findings from the investigation.
- `generate_unioned_ehr_dataset.sh` ... I removed `--sync false` from the command that copies mapping tables. `--sync false` is still there in the commands before it, but having it in sync mode here will give the preceding commands ample time to finish copying. Making it in sync mode will make the execution longer but the impact is acceptable (~10 minutes).
=> [DC-3455] Update Unioned EHR process to have mapping tables as expected

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_part2.py
Scope:
Even though we are opening up the scope to expand the subcategories of race and ethnicity to be allowed in the controlled tier, we still need to suppress free text responses for race/ethnicity questions. The free text suppression is handled in a cleaning rule, which is not being modified in this story.
Add a check in controlled_tier_qc to verify that race/ethnicity subcategories exist in the observation table.
Added check should summarise the existence of the subcategories, not display everything.
We can use the logic in the [cleaning rule](https://precisionmedicineinitiative.atlassian.net/browse/DC-3436) that will be dropped to identify the race/ethnicity records.
‘AIA: tribe’ does not have 'text' in the string but needs to be suppressed.
Acceptance Criteria:
A check is added to …
=> [DC-3439]  verify free text responses for race/ethnicity are suppressed

data_steward/analytics/cdr_ops/report_runner.py, tests/unit_tests/data_steward/analytics/cdr_ops/report_runner_test.py
Users with Windows machines have reported issues when trying to use the report_runner.py module to run some of the analytics reports.  They resolved their issues locally by applying the ‘utf-8’ encoding.
This PR addresses this issue by adding the optional kwarg parameter `encoding` and specifies a value of `utf-8`.  The complete additions are found in this [commit](https://github.com/all-of-us/curation/commit/ab3884f7cf600e9d61b092e5a49aa1a686b520bf), with this first being [whitespace](https://github.com/all-of-us/curation/pull/1782/commits/b745b364af7a9c198a7601a224f2ddff2fff3648) removal.
=> [DC-2758] Add encoding specification to `report_runner.py`

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report8_household_state_genera.py, data_steward/cdr_cleaner/cleaning_rules/deid/conflicting_hpo_state_generalization.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/conflicting_hpo_state_generalization_test.py
Dear reviewer,
- Please take a look at the comment section of the JIRA ticket DC-3504 for the context.
- The changes in the unrelated sections of `cdr_deid_qa_report8_household_state_genera.py` are made by Pylint.
- For `cdr_deid_qa_report8_household_state_genera.py`, I removed the parameter `pid_threshold` because it was not used anywhere.
- I updated the test cases in `conflicting_hpo_state_generalization_test.py` as a part of the investigation.
=> [DC-3504] `ConflictingHpoStateGeneralize` QC notebook update and test cases update

data_steward/analytics/cdr_ops/combined.py
In the combined.py notebook, it is necessary to add a verification step to ensure that all EHR records are removed for duplicated accounts with conflicting statuses. This check should analyze the data from all CDM/clinical tables. A failure message with a list of these items should be added if any PIDs still exist.
=> [DC-3435] Add check in combined.py to verify no participant in the pdr_ehr_dup_report list have EHR data

data_steward/cdr_cleaner/cleaning_rules/create_person_ext_table.py, data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables.py, data_steward/tools/create_combined_backup_dataset.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables_test.py
Updates made to ensure person_ext is created, populated, and kept at CT base.
=> [DC-3605] [DC-3600] Exclude 'person_ext' from being removed by cleaning Rule

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_base_qa_report1.py
Description:
Participants answer multiple-choice insurance questions on multiple surveys.  One of the available insurance selections is “Indian Health Services” (or a variant).  This option does not necessarily identify a participant as a self-identifying AI/AN participant.  This check ensures this data is indeed removed via this check.
See related ticket [DC-3597](https://precisionmedicineinitiative.atlassian.net/browse/DC-3597)
Note: some partial re-formatting occurred, resulting in 5 superfluous diff's.
[DC-3597]: https://precisionmedicineinitiative.atlassian.net/browse/DC-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-3611] Update QC notebook for Indian Health Services responses generalization CR

data_steward/analytics/cdr_ops/raw_rdr_export_qc.py
Raw rdr notebook update for Aou_death.
=> [DC-3648] Ignore death table from QC check and use AOU Death

data_steward/analytics/cdr_ops/combined.py, data_steward/analytics/cdr_ops/ehr_union_qc.py
updated QC notebook for ehr_union and moved 1 check to combined.
=> [DC-3645] Update Union QC notebook with fixes for column name and moving notes check

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_part2.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py
This PR remove the portion of checks where wear_consent participants must have primary consent.
[Ticket](https://precisionmedicineinitiative.atlassian.net/browse/DC-3635)
[Investigation](https://precisionmedicineinitiative.atlassian.net/browse/DC-3626)
=> [DC-3635] Remove portion of query checking primary consent

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report7_cope_survey.py
**Background:**
"The issue with the `procedure_occurence` covid vaccine concepts failing due to 'being suppressed in RT' is caused by the vocabulary `domain_id`'s for the associated Standard concepts which populate `procedure_concept_id` (failing column) being 'Drug' in the combined stage. These records are not actually suppressed they get moved to the Drug table by a combined CR."
**This PR:**
Updated to look for concepts that are being suppressed in the deid stage. 
- If they existed at combined stage, they should still be in deid.
- If they did not exist in combined stage, they should not be expected to exist in died.
See Jira issue [DC-3631](https://precisionmedicineinitiative.atlassian.net/browse/DC-3631) for the complete description and scope
See Jira issue …
=> [DC-3631] Update cope_survey to reduce false positive results due to concept domains

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_clean_qa_report1.py
DC-1661 removed the death(currently aou_death) table from the affected tables of drop_zero_concept_ids. However, the notebook check regarding this issue was not removed.
This PR removes the check
See [DC-3673](https://precisionmedicineinitiative.atlassian.net/browse/DC-3673), the ticket
See [DC-1661](https://precisionmedicineinitiative.atlassian.net/browse/DC-1661), ticket excluding death table in RT.
Note:
variable `df1` is renamed to `result` for better clarity and context
variable `df` is renamed to `summary` for better clarity and context
These are mostly in two separate commits should the reviewer want to revert the names `df` and/or `df1` for convenience.
[DC-3673]: https://precisionmedicineinitiative.atlassian.net/browse/DC-3673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> [DC-3673] Remove notebook check regarding cause_source_concept_id for aou_death

data_steward/analytics/cdr_ops/ad_hoc_analyses/cdr_person_id.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/cohort_testing.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/coverage.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/deid_race.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/ehr_demographics_by_site.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/ehr_ops_row_counts.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/generalized_dupes.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/identify_required_labs.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/list_tables_with_duplicate_domain_ids.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/person_gender_sex.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/pop_retract.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/sex_gender_540.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/site_mapping.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/standard_concepts_cdr_389.py, data_steward/analytics/cdr_ops/systematic_scripts/data_loss_through_pipeline.py, data_steward/analytics/cdr_ops/systematic_scripts/date_disparity_with_respect_to_visit.py, data_steward/analytics/cdr_ops/systematic_scripts/ehr_data_quality_dashboard_testing.py, data_steward/analytics/cdr_ops/systematic_scripts/notes_volume_distribution.py, data_steward/validation/metrics/required_labs.py, tests/integration_tests/data_steward/retraction/retract_data_gcs_test.py, tests/integration_tests/data_steward/validation/export_test.py
This PR removes several superfluous `bq_utils` imports.  It removes 22 import statements where they are no longer needed.  Since some files contain trailing whitespace, it may be hard to determine the actual, important change.
Luckily, most import statements occur at the beginning of each file; therefore, one may need to `check only the first few lines!` to see a removal using diff.
=> [DC-3632] Remove irrelevant bq_utils import statements

data_steward/cdr_cleaner/cleaning_rules/deid/concept_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/recent_concept_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/cancer_concept_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/missing_concept_record_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/section_participation_concept_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/vehicular_accident_concept_suppression_test.py
updated concept suppression integration env cleanup.
=> [DC-3233] `AbstractBqLookupTableConceptSuppression` is leaving a dirty integration test environment

data_steward/analytics/cdr_ops/cross_ct_rt/output_prod_publish_qc.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_base_qa_report1.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_clean_qa_report1.py, data_steward/cdr_cleaner/cleaning_rules/create_person_ext_table.py, data_steward/resource_files/schemas/extension_tables/person_ext.json, data_steward/tools/recreate_person.py
* [DC-3793] Update self_reported_population to self_reported_category
[DC-3793]: https://precisionmedicineinitiative.atlassian.net/browse/DC-3793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-3793] Update self_reported_population to self_reported_category
