all-of-us/curation

data_steward/bq_utils.py, data_steward/test/test_data/bq_errors_bad_person.csv
The following errors are fixed now : 
1. export_test timesout and returns empty result. Fixed by increasing timeout to 60 seconds.
2. bigquery error response was changed. expected errors.csv changed accordingly.
=> Fixed tests

circle.yml, data_steward/bq_utils.py, data_steward/common.py, data_steward/test/unit_test/export_test.py, data_steward/test/unit_test/test_util.py, data_steward/test/unit_test/validation_test.py, data_steward/validation/main.py
The validation is now done on the latest folders every day. This is done via a folder_prefix argument given to most functions. The tests have been updated accordingly.
=> Feature branch/folder specific validation

circle.yml, data_steward/bq_utils.py, data_steward/common.py, data_steward/test/unit_test/export_test.py, data_steward/test/unit_test/test_util.py, data_steward/test/unit_test/validation_test.py, data_steward/validation/main.py
Added use of folders and changed Circle test data set.
=> Merge use of folders to Master

data_steward/app_base.yaml, data_steward/generate_cron_yaml.sh
-  app_base has secure: always for all endpoints
-  cron.yaml now generates copy endpoints also
-  change schedules of cron
=> [DC-94] Update app.yaml file to enforce always: secure

data_steward/app_base.yaml, data_steward/generate_cron_yaml.sh
-  `app_base.yaml` has `secure: always` for all endpoints
-  `cron.yaml` generates copy endpoints
=> [PD-1567] Update app.yaml file to enforce always: secure

data_steward/bq_utils.py
* Retry http requests with 50x response status (see https://goo.gl/b9Ydm5)
* This should alleviate many failed builds
Notes
* This presupposes that all internal errors generated via API calls are worth retrying
* 40x errors are not retried and likely should **not** be anyway
=> Retry execution of all bq jobs that result in internal error

data_steward/common.py
required tables now only includes person.
=> Change required files

data_steward/bq_utils.py, data_steward/generate_cron_yaml.sh, data_steward/test/unit_test/bq_utils_test.py, data_steward/test/unit_test/ehr_merge_test.py, data_steward/validation/achilles.py, data_steward/validation/achilles_heel.py, data_steward/validation/ehr_merge.py, data_steward/validation/main.py
Change cron schedule for ValidateAllHpoFiles in generate_app_yaml.sh
=> [DC-103] set validate-all cron jobs to run every 3 hours 

data_steward/resources/curation_report/css/chart.css
@mark-velez - Please review this pull request.. Thanks, Mark!!!
=> chart.css modfied to reduce the size of legend, axis text and labels.

data_steward/test/test_data/bq_errors_bad_person.csv, data_steward/test/test_data/empty_warnings.csv, data_steward/test/unit_test/test_util.py, data_steward/test/unit_test/validation_test.py, data_steward/validation/main.py
A new test corresponding to this feature also included!
=> [DC-119] PII files yield "Unknown file" warning

data_steward/common.py, data_steward/resources.py, data_steward/vocabulary.py
* Must resolve any regressions
* Refactor wherever we create all tables to use a wrapper func
=> [DC-156] Use schema files to create tables

data_steward/resources/fields/observation.json, data_steward/test/unit_test/combine_ehr_rdr_test.py, data_steward/tools/combine_ehr_rdr.py
Thes PR has the new ehr_person_move_to_observation function and it's test.
=> [DC-109] Store EHR person data in observation table

data_steward/bq_utils.py, data_steward/test/unit_test/bq_utils_test.py, data_steward/test/unit_test/combine_ehr_rdr_test.py, data_steward/test/unit_test/ehr_union_test.py, data_steward/test/unit_test/test_util.py, data_steward/validation/ehr_union.py
* Fixes [DC-170] EHR union excludes tables even though they have data
=> Page results of listing tables in BigQuery API

data_steward/ci/setup.sh, data_steward/test/unit_test/achilles_heel_test.py, data_steward/test/unit_test/achilles_test.py, data_steward/validation/ehr_union.py
This fixes the resources exceeded during query execution and also the tests failing issue.
=> [DC-118]- Resources exceeded during query execution

data_steward/run_curation_pipeline.sh
[DC-178] Create script to automate curation pipeline - error fix
=> Fixes the de-id venv error.

data_steward/test/unit_test/retract_data_test.py, data_steward/tools/retract_data.py
Add script to retract data from a specific folder or all folders in a bucket
=> [DC-278] Data Retraction

data_steward/common.py, data_steward/test/unit_test/validation_test.py, data_steward/validation/main.py
Add test and allow file ignore using string
=> [DC-254] Curation report showing as unknown in warnings.csv

data_steward/test/unit_test/combine_ehr_rdr_test.py, data_steward/tools/combine_ehr_rdr.py
Filter query in move_ehr_person_to_observation() based on consent, add test
=> [DC-332] [P3]Combine does not filter Observation based on consent

data_steward/dev_requirements.txt, data_steward/tools/top_heel_errors.py, data_steward/tools/top_heel_errors.sh
This patch applies pylint changes to the python file.
Creates a dev_requirements file to load pylint and
coverage.  They are not needed in production, so do
not belong in the production requirements file.  The name
in the bash script usage line is updated to match the name
of the script.  Once environment variables are set, the
option to set the exit on an error is turned off.  Script indicates
if the file is created.
=> [DC-355] fix errors related to top_heel_errors report

data_steward/bq_utils.py, data_steward/common.py, data_steward/resources.py, data_steward/resources/fields/participant_match.json, data_steward/test/test_data/five_person_results.html, data_steward/test/test_data/person_only_results.html
=> [DC-358] Add participant_match.json to specify schema, include it as pii file

data_steward/resources/fields/participant_match.json, data_steward/test/test_data/five_persons/fact_relationship.csv, data_steward/test/test_data/nyc_five_person/fact_relationship.csv, data_steward/test/unit_test/ehr_union_test.py, data_steward/validation/ehr_union.py
Fixes Fact_Relationship null error and Participant_Match load error.
=> [DC-387] Fix Fact Relationship Null error.

data_steward/ci/setup.sh, data_steward/common.py, data_steward/test/test_data/five_person_results.html, data_steward/test/test_data/five_person_results_achilles_error.html, data_steward/test/unit_test/test_util.py, data_steward/test/unit_test/validation_test.py, data_steward/validation/main.py
Retries once and skips if it fails again
=> [DC-401] Skip adding achilles to results.html if it fails due to rate limits

data_steward/README.md, data_steward/bq_utils.py, data_steward/cleaners/clean_cdr.py, data_steward/constants/bq_utils.py, data_steward/constants/cleaners/combined.py, data_steward/constants/cleaners/combined_deid.py, data_steward/constants/cleaners/ehr.py, data_steward/constants/cleaners/rdr.py, data_steward/constants/cleaners/unioned.py
Initial CDR cleaner package set up.
Will be modified as needed.
Includes code to remove annoying memcache warning message.
=> [DC-407] Initial cleaner package

data_steward/cleaners/clean_cdr.py, data_steward/cleaners/clean_cdr_engine.py, data_steward/cleaners/clean_rule_4.py, data_steward/cleaners/id_deduplicate.py, data_steward/constants/cleaners/clean_cdr.py, data_steward/constants/cleaners/combined.py, data_steward/constants/cleaners/combined_deid.py, data_steward/constants/cleaners/ehr.py, data_steward/constants/cleaners/rdr.py, data_steward/constants/cleaners/unioned.py
Refactors Cleaner package and adds cleaning rule 4
=> [DC-390] ID Columns in each domain should be unique

data_steward/spec/_data/hpo.csv
=> [DC-409] Add in additional sites in pipeline

data_steward/bq_utils.py, data_steward/cleaners/clean_cdr.py, data_steward/cleaners/clean_cdr_engine.py, data_steward/cleaners/id_deduplicate.py, data_steward/cleaners/null_invalid_foreign_keys.py, data_steward/constants/bq_utils.py, data_steward/constants/cleaners/clean_cdr.py
Adds a rule (cleaning_rule_1) which generates queries to nullify invalid foreign keys.
=> [DC-388] Invalid foreign keys will be nulled out and the remainder of the row persists.

data_steward/cleaners/clean_cdr.py, data_steward/cleaners/clean_years.py, data_steward/cleaners/id_deduplicate.py, data_steward/cleaners/null_invalid_foreign_keys.py
Add cleaning rule to remove all data if year of birth > 2019 or < 1800
=> [DC-392] Year of birth should not be in the future or before 1800

data_steward/cleaners/clean_cdr.py, data_steward/cleaners/clean_years.py, data_steward/cleaners/id_deduplicate.py, data_steward/cleaners/negative_ages.py, data_steward/cleaners/null_invalid_foreign_keys.py
Add negative ages cleaning rule, clean up parser args
=> [DC-393] Remove participant data if age is below 0 or too high

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/id_deduplicate.py, data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death.py, data_steward/cleaners/no_data_30_days_after_death.py
* Adds Clean rule to remove data points 30 days after the death date.
* refactored other cleaning rules.
=> [DC-404] Ensure no Date or DTTM data point has a value > 30 days from the death date

data_steward/tools/import_rdr_omop.sh
* Adds functionality create all the CDM tables after creating dataset.
* Loads RDR csv files in to created CDM tables.
=> [DC-435] Creates all CDM tables in RDR load process

data_steward/tools/generate_combined_dataset.sh, data_steward/tools/generate_unioned_ehr_dataset.sh
* Modifies generate_combined_dataset.sh to fix the dataset name
* Modifies generate_unioned_dataset.sh to remove unintentionally added tables.
=> Fixes Minor pipeline issues 

data_steward/generate_cron_yaml.sh
Add timezone info in generate cron file, refactor
=> Updates cron jobs

data_steward/tools/create_ehr_snapshot.sh, data_steward/tools/generate_combined_dataset.sh, data_steward/tools/run_achilles_report.sh, data_steward/tools/run_curation_pipeline.sh, data_steward/tools/run_deid.sh
Removes remove venv line from pipeline scripts.
=> Fix ehr snapshot name in pipeline.

data_steward/bq_utils.py, data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/clean_years.py, data_steward/cdr_cleaner/cleaning_rules/drug_refills_days_supply.py, data_steward/cdr_cleaner/cleaning_rules/negative_ages.py, data_steward/cdr_cleaner/cleaning_rules/null_invalid_foreign_keys.py, data_steward/cdr_cleaner/cleaning_rules/temporal_consistency.py, data_steward/cdr_cleaner/cleaning_rules/valid_death_dates.py, data_steward/common.py
Add cleaning rule for drug refills/days supply, refactor other rules
=> [DC-403] Days supply and number of refills for a drug should not be too high

data_steward/tools/fix_rdr_data.py, data_steward/tools/import_rdr_omop.sh
Adds functionality to fix PMI_Skip and PPI vocab update during RDR load process.
=> [DC-420] Backfill PMI Skip Codes in rdr survey data

data_steward/bq_utils.py, data_steward/test/unit_test/data_steward/tools/retract_data_bq_test.py, data_steward/tools/retract_data_bq.py
Add module for retracting data from BQ datasets
=> [DC-456] Delete non-aou participants data from datasets

data_steward/generate_cron_yaml.sh, data_steward/resources.py, data_steward/tools/retract_data_bq.py, data_steward/validation/main.py
* Move cron declaration from retract_pids file to main
* Make generate_cron_yaml.sh OSX friendly
=> Minor fix for retract ids cron job

data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death.py, data_steward/tools/consolidated_reports/get_all_achilles_reports.py, data_steward/tools/consolidated_reports/get_all_results_html.py, data_steward/tools/generate_combined_dataset.sh
Minor fixes
> Adds Try blocks to open files in consolidated script.
> Renames HTML files and adds HPO_it to it.
> Adds base to combined dataset name.
=> Minor bug fixes

data_steward/analytics/tools/concept_success_rates_visualizations.ipynb, data_steward/analytics/tools/duplicates_visualizations.ipynb, data_steward/analytics/tools/metrics_over_time.py
* Adds script to convert excel files
* Adds visualization Notebooks
=> Adds Visualization Notebooks

data_steward/analytics/table_metrics/metrics_over_time.py, data_steward/analytics/tools/concept_success_rates_visualizations.ipynb, data_steward/analytics/tools/duplicates_visualizations.ipynb, data_steward/analytics/tools/email-generator.py, data_steward/analytics/tools/great_job.txt, data_steward/analytics/tools/introduction.txt, data_steward/analytics/tools/nonsensical_dates_visualizations.ipynb
* Nonsensical dates visualization.
* Added simple email generator script.
=> Fixed bugs in metrics_over_time.

data_steward/tools/fix_rdr_data.py, data_steward/tools/import_rdr_omop.sh
* changed the order of query execution in fix_rdr_data
=> Reformat and fixes the script paths in import_rdr_omop

data_steward/deid/aou.py, data_steward/deid/parser.py, data_steward/deid/press.py, data_steward/deid/rules.py, data_steward/run_deid.py
Runs de-id for only these specific tables.
=> DC-496  deid bug

data_steward/cdr_cleaner/cleaning_rules/domain_alignment.py, data_steward/cdr_cleaner/cleaning_rules/field_mapping.py, data_steward/test/unit_test/data_steward/cdr_cleaner/cleaning_rules/domain_alignment_test.py, data_steward/test/unit_test/data_steward/cdr_cleaner/cleaning_rules/field_mapping_test.py
Fixed the bug to populate 0 into the required field for the redirected records where the values cannot be mapped
=> Fixed the bug to populate 0 into the required field for the redirected records where the values cannot be mapped

data_steward/resources/aou_general/concept.csv
Converted file to CSV file format and added two new concepts to address [DC-498]
[DC-498]: https://precisionmedicineinitiative.atlassian.net/browse/DC-498
=> New Custom Concepts  [DC-498]

data_steward/resources/aou_general/concept.csv
=> update concept.csv with new concept generalization codes

data_steward/deid/config/ids/config.json, data_steward/deid/config/ids/tables/observation.json, data_steward/tools/run_deid.py
Last minute deid generalization tweaks.
=> De id generalizations

data_steward/resources/aou_general/concept.csv, data_steward/tools/load_vocab.sh
=> fix concept.csv white spaces

data_steward/deid/config/ids/config.json, data_steward/tools/run_deid.py
=> fix config path in run_deid.py

data_steward/deid/config/ids/config.json
Requirements were updated and this needs to update.
=> Sex at birth generalization fix

data_steward/deid/config/ids/config.json
uses new requirements in lieu of old requirements
=> Deid orientation config update

data_steward/tools/fix_rdr_data.py
=> change value_as_concept_id from 0 to PMI_SKIP concept_id in fix_rdr_data.py

data_steward/analytics/cdr_ops/notebooks/curation_dashboard.py
=> Save pivoted dataset comparison dataframes to csv files

data_steward/analytics/cdr_ops/notebooks/bq.py, data_steward/analytics/cdr_ops/notebooks/cdr_person_id.py, data_steward/analytics/cdr_ops/notebooks/ehr_operations.py
@cukarthik just fyi this is the notebook that shows sites with invalid person_ids and tries to map ehr files with rdr data
=> Add notebook to validate person_ids submitted by sites

data_steward/tools/create_snapshot_dataset_with_schemas.py, data_steward/tools/run_cleaning_rules.sh, data_steward/tools/snapshot_by_query.py
Add script to create snapshot dataset using query.
[ci skip]
=> Add script to run cleaning rules and snapshot cleaned dataset.

data_steward/deid/aou.py
Creates a mapping table.  Mapping will be done manually for the time being.
=> [DC-518]  create questionnaire_response_id mappings

data_steward/deid/config/ids/config.json, data_steward/deid/config/ids/tables/observation.json, data_steward/deid/rules.py
Removing the copy_to that caused problems in value_as_concept_id.
Using a case statement to generalize race and ethnicity.
Adding ability to add sql directly for generalizations.  This was done for speed and should be refactored later.
=> [DC-534] HLS race/ethnicity deid generalization fix

data_steward/analytics/cdr_ops/site_mapping.py
=> Add notebook to compare site mapping tables in combined vs deid

data_steward/cdr_cleaner/clean_cdr.py
=> Remove unused cleaning rules from de_identified step.

data_steward/analytics/cdr_ops/deid_diff_gender_sex.py, data_steward/notebooks/README.md, data_steward/notebooks/render.py, data_steward/notebooks/requirements.txt, data_steward/notebooks/start.sh
* Add qgrid notebook extension
* Add SANDBOX to parameters
=> Add distribution tables to notebook deid_diff_gender_sex

data_steward/tools/table_copy.sh
=> Make target app id explicit

data_steward/analytics/cdr_ops/pop_retract.py, data_steward/notebooks/requirements.txt
Determines number of records per table to be retracted and compares
expected vs actual counts
=> Add pop_retract notebook [ci skip]

data_steward/cdr_cleaner/clean_cdr.py, data_steward/constants/cdr_cleaner/clean_cdr.py
=> Make clean_cdr modular.

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/backfill_pmi_skip_codes.py, data_steward/tools/fix_rdr_data.py, data_steward/tools/import_rdr_omop.sh
=> Add backfill PMI_SKIP codes to cleaning rules module.

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/maps_to_value_ppi_vocab_update.py, data_steward/tools/fix_rdr_data.py
=> Move maps to value vocab update to cdr_clean package.

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters.py, data_steward/tools/fix_rdr_data.py
=> Move clean ppi numeric values to cdr_clean package.

data_steward/cdr_cleaner/cleaning_rules/backfill_pmi_skip_codes.py, data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters.py, data_steward/tools/import_rdr_omop.sh
=> Fix clean_ppi_numeric_fields query format.

data_steward/analytics/table_metrics/metrics_over_time.py
* population of the 'unit' field for select measurements
* population of the 'route' field in the drug exposure table
* proportion of excepted drug ingredients observed
* proportion of expected measurements observed
Increases readability of code
Fixes bugs
=> Adds the following data quality metrics:

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/manual_cleaning_rules/negative_ppi.py
* Add rule to update specific negative ppi answers to skip
=> [DC-536] Set -1 on slider PPI question to PMI_Skip for PPI Data

data_steward/resources/hpo.csv
=> [DC-470] Add in new site (LSUHSC-NO) into pipeline for data processing

data_steward/app_base.yaml, data_steward/main.py
* Update app_base.yaml
* Remove login key (deprecated)
* Add `script: auto` to route requests to the app
* Add data_steward/main.py which is needed for `script: auto` to work
=> Update deployment for GAE gen 2 (py3)

data_steward/tools/import_rdr_omop.sh
=> Removes quotes to make bq load work as expected

data_steward/deid/config/ids/config.json, data_steward/deid/rules.py
Implements a generalization when a person's gender does not match their sex_at_birth.
Updates the generalize method in rules to use safe dictionary accesses.
=> Gender, Sex_At_Birth generalization rule

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/round_ppi_values_to_nearest_integer.py
=> [DC-538] Round PPI numeric values to the nearest integer.

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid.py
=> [DC-516] Repopulates person table after de-id.

data_steward/bq_utils.py, data_steward/test/unit_test/data_steward/tools/retract_data_bq_test.py, data_steward/test/unit_test/data_steward/tools/retract_data_gcs_test.py, data_steward/tools/retract_data_bq.py, data_steward/tools/retract_data_gcs.py, data_steward/validation/main.py
* Convert single quoted strings to triple quoted strings for queries
* Use bq table containing person_ids and research_ids instead of file
* Rename queries to RETRACT_*
* Add sandbox dataset and person/research_id toggle, fix tests
=> [DC-556] Retract data bq improvements

data_steward/analytics/table_metrics/Tzable_Metrics_part_6.py
=> Add table_metrics notebook 6

data_steward/validation/main.py
=> Add root level logging

data_steward/analytics/table_metrics/Table_Metrics_part_5.py, data_steward/analytics/table_metrics/Table_Metrics_part_6.py
=> Updates table_metrics notebook 5, 6

data_steward/deid/aou.py
=> Fix path and dataset_name in aou.py

data_steward/cdr_cleaner/manual_cleaning_rules/clean_height_weight.py
* Add function to collect queries
* Remove site specific rule
* Add notes to check for the distribution for each unit for measurement_concept_id 3025315, and steps to correct in case of discrepancies
=> [DC-542] Add cleaning rule to normalize height/weight data

data_steward/test/unit_test/data_steward/validation/participants/readers_test.py
The unit test is decorated as an expectedFailure.  When the
bug is fixed, the test will write out as '(unexpected_successes=1)'.
The expectedFailure decorator should be removed then.
=> [DC-595] Participant match datetime bug

data_steward/curation_logging/curation_gae_handler.py, data_steward/test/unit_test/data_steward/curation_logging/gcp_stackdriver_logger_test.py
*  added the first test for logging
* fixed the unit test after merging the bug fixing PR for the logging
* initialize the logging service client globally
* initalized gcp_stackdriver_logger in advance and set it as a parameter in the GCPLoggingHandler [ci skip]
* removed the line for setting the logging level to INFO [ci skip]
* added the header for curation_gae_handler [ci skip]
* refactored the unit test gcP_stackdriver_logger_test.pyt
* removed the space character in the gcp_logging link in the header comment; added a comment to the assertEqual to explain why _buffer_size is 0
* fixed the header comment
=> Feature/py3 logging (#327)

data_steward/cdr_cleaner/manual_cleaning_rules/remove_operational_pii_fields.py, data_steward/test/unit_test/data_steward/cdr_cleaner/manual_cleaning_rules/remove_operational_pii_fields_test.py
=> [DC-588] Fix unresolved module_name in remove_operational_pii_fields cleaning rule

data_steward/analytics/cdr_ops/conformance.py, data_steward/analytics/cdr_ops/coverage.py, data_steward/analytics/cdr_ops/curation_dashboard.py, data_steward/analytics/cdr_ops/deid_race.py, data_steward/analytics/cdr_ops/ehr_operations.py, data_steward/analytics/cdr_ops/list_tables_with_duplicate_domain_ids.py, data_steward/analytics/table_metrics/Table_Metrics_part_1.py, data_steward/analytics/table_metrics/Table_Metrics_part_2.py, data_steward/analytics/table_metrics/Table_Metrics_part_3.py, data_steward/analytics/table_metrics/Table_Metrics_part_4.py, data_steward/analytics/table_metrics/Table_Metrics_part_5.py, data_steward/analytics/table_metrics/Table_Metrics_part_6.py, data_steward/analytics/tools/concept_success_rates_visualizations.py, data_steward/analytics/tools/data_after_death_visualizations.py, data_steward/analytics/tools/duplicates_visualizations.py, data_steward/analytics/tools/email_generator.py, data_steward/analytics/tools/end_dates_before_start_dates_visualizations.py, data_steward/analytics/tools/ingredient_usage_visualizations.py, data_steward/analytics/tools/measurement_integration_visualizations.py, data_steward/analytics/tools/route_concept_population_visualizations.py, data_steward/analytics/tools/unit_population_visualizations.py, data_steward/notebooks/README.md, data_steward/notebooks/bq.py, data_steward/notebooks/requirements.txt, data_steward/notebooks/start.sh
=> Fix jupytext notebook load error.

data_steward/cdr_cleaner/manual_cleaning_rules/clean_height_weight.py
Fix wrongly added height variables to weight
=> [DC-631] Height/weight cleaning rule has "height" instead of "weight" in code

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/update_family_history_qa_codes.py, data_steward/test/unit_test/data_steward/cdr_cleaner/cleaning_rules/update_family_history_qa_codes_test.py
Update Family Medical History questions and answers where there is data still encoded with the old question and answer codes
=> [DC-564] Update old Family Medical History question/answer codes to the new codes

data_steward/resources/hpo.csv
Adds saou_uab_hunt and saou_uab_selma to hpo.csv file
=> DC-632 add two new sites

data_steward/cdr_cleaner/cleaning_rules/drop_multiple_measurements.py
Change delete query to use correct syntax.
=> [DC-659] fix query syntax for rdr cleaning

data_steward/cdr_cleaner/cleaning_rules/maps_to_value_ppi_vocab_update.py
=> [DC-658] Fix maps_to_value_ppi_vocab_update query

data_steward/bq_utils.py, data_steward/tools/retract_data_bq.py, data_steward/tools/retract_data_gcs.py, data_steward/validation/main.py, tests/integration_tests/data_steward/tools/retract_data_bq_test.py, tests/integration_tests/data_steward/tools/retract_data_gcs_test.py, tests/test_util.py, tests/unit_tests/data_steward/tools/retract_data_bq_test.py
Add release dataset regex, allow retraction from other projects
=> [DC-635] Update retraction to increase scope and target release datasets

data_steward/dev_requirements.txt, data_steward/resources/templates/hpo_report.html, data_steward/tools/combine_ehr_rdr.py, tests/integration_tests/data_steward/tools/combine_ehr_rdr_test.py, tests/integration_tests/data_steward/validation/ehr_union_test.py, tests/integration_tests/data_steward/validation/main_test.py
Fixed issue where RDR dataset naming is checked for all tests
=> [DC-682] Fix RDR dataset id error in tests

data_steward/analytics/cdr_ops/coverage.py, data_steward/analytics/cdr_ops/curation_dashboard.py, data_steward/analytics/cdr_ops/list_tables_with_duplicate_domain_ids.py
=> [DC-688] Fix datalab.bigquery python3 error

data_steward/bq_utils.py, data_steward/tools/retract_data_bq.py, data_steward/tools/retract_data_gcs.py, data_steward/validation/main.py, tests/integration_tests/data_steward/tools/retract_data_bq_test.py, tests/unit_tests/data_steward/tools/retract_data_bq_test.py
Disable output project if unspecified
=> [DC-687] Disable retraction from output project

data_steward/tools/snapshot_by_query.py, tests/unit_tests/data_steward/tools/snapshot_by_query_test.py
=> [DC-671] Uses the table definition to cast the column type while copying the tables

data_steward/tools/retract_data_bq.py
Add retraction for person from rdr and ehr in combined
=> [DC-692] Remove data from person table if retracting from EHR and RDR

data_steward/tools/retract_data_bq.py
Add observation_period to retraction list
=> [DC-705] Add observation_period to list of tables to retract from

data_steward/analytics/cdr_ops/records_per_capita_analysis.py, data_steward/analytics/tools/email_generator.py
* Creates Notebook for Records Per Capita for Each Table/Site Combination
* Streamline the e-mail generator script to cut down on the amount of text and change the resource links.
=> [EDQ-383] [EDQ-385] Records Per Capita and E-mail Generator

data_steward/cdr_cleaner/cleaning_rules/base_cleaning_rule.py, data_steward/cdr_cleaner/cleaning_rules/remove_aian_participants.py, data_steward/tools/add_hpo.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_aian_participants_test.py
=> [DC-441] Fix lint issues after updated pylint checks

data_steward/analytics/cdr_ops/cdr_person_id.py, data_steward/analytics/cdr_ops/cohort_testing.py, data_steward/analytics/cdr_ops/coverage.py, data_steward/analytics/cdr_ops/curation_dashboard.py, data_steward/analytics/cdr_ops/data_loss_through_pipeline.py, data_steward/analytics/cdr_ops/deid_diff_gender_sex.py, data_steward/analytics/cdr_ops/deid_race.py, data_steward/analytics/cdr_ops/ehr_data_quality_dashboard_testing.py, data_steward/analytics/cdr_ops/ehr_demographics_by_site.py, data_steward/analytics/cdr_ops/ehr_operations.py, data_steward/analytics/cdr_ops/foreign_key_gaps.py, data_steward/analytics/cdr_ops/generalized_dupes.py, data_steward/analytics/cdr_ops/identify_required_labs.py, data_steward/analytics/cdr_ops/list_tables_with_duplicate_domain_ids.py, data_steward/analytics/cdr_ops/notes_volume_distribution.py, data_steward/analytics/cdr_ops/outlier_testing.py, data_steward/analytics/cdr_ops/person_gender_sex.py, data_steward/analytics/cdr_ops/pop_retract.py, data_steward/analytics/cdr_ops/sex_gender_540.py, data_steward/analytics/cdr_ops/site_mapping.py, data_steward/analytics/cdr_ops/standard_concepts_cdr_389.py, data_steward/analytics/cdr_ops/unit_standardization.py, data_steward/bq_utils.py, data_steward/cdr_cleaner/cleaning_rules/remove_aian_participants.py, data_steward/cdr_cleaner/cleaning_rules/sandbox_and_remove_pids.py, data_steward/cdr_cleaner/manual_cleaning_rules/ac67_rm_invalid_subquestions.py, data_steward/utils/bq.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_aian_participants_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/sandbox_and_remove_pids_test.py
=> [DC-735] Create a utility wrapper for the BigQuery's python client library

data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid.py, data_steward/resources/fields/person.json, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid_test.py, tests/test_data/five_persons/person.csv, tests/test_data/nyc_five_person/person.csv, tests/test_data/pitt_five_person/person.csv, tests/unit_tests/data_steward/tools/snapshot_by_query_test.py
Sending for initial feedback, will add tests after confirming this is directionally correct.
So far: manually verified SQL works via BQ UI.
CC @mark-velez
=> [DC-565] Repopulate person table gender and sex-at-birth post-deid

data_steward/analytics/table_metrics/other_scripts/drug_route_success_rate.py, data_steward/analytics/table_metrics/other_scripts/measurement_units_success_rate.py, data_steward/analytics/table_metrics/weekly_scripts/drug_route_success_rate.py, data_steward/analytics/table_metrics/weekly_scripts/measurement_units_success_rate.py
* No major changes - just to ensure consistency for metrics
=> [EDQ-409] Change the means of calculating 'total rows' for units and routes

data_steward/analytics/table_metrics/metrics_over_time.py
* Fixed the load_files function; FileNotFound error now displays unique message properly.
* Now using the correct interpreter for troubleshooting.
* Improved the valid_cols_total function to ensure that all of the tables without underscores are also logged. Ensures that the 'total' metric on percentage-based metrics is calculated properly.
* Verified for options A, B, and C. Both table and HPO sheets were tested and manually verified.
* Tested and verified option E (for both table and HPO). Assuming D has a similar implementation.
* Started to investigate the errors in the 'G' path of generation. F and G warrant changes to the analytics report script.
* Verified for H -> A and H -> B. This includes the aggregate df for site sheets.
* Tested both pathways for I. Validated including the …
=> [EDQ-399] Refactored and validated the m_o_t script for the new metrics

data_steward/tools/run_achilles_and_export.py, data_steward/tools/run_achilles_report.sh, data_steward/validation/export.py, tests/integration_tests/data_steward/validation/export_test.py
=> [DC-651] Fix Hx usage of environment variable BUCKET_NAME_NYC=test-bucket

data_steward/analytics/table_metrics/other_scripts/concept_success_rate.py, data_steward/analytics/table_metrics/other_scripts/data_after_death.py, data_steward/analytics/table_metrics/other_scripts/diabetes_completeness.py, data_steward/analytics/table_metrics/other_scripts/drug_integration_success_rate.py, data_steward/analytics/table_metrics/other_scripts/drug_route_success_rate.py, data_steward/analytics/table_metrics/other_scripts/duplicates.py, data_steward/analytics/table_metrics/other_scripts/end_before_begin.py, data_steward/analytics/table_metrics/other_scripts/measurement_integration_success_rate.py, data_steward/analytics/table_metrics/other_scripts/measurement_units_success_rate.py, data_steward/analytics/table_metrics/other_scripts/source_concept_success_rate.py
* Specifically removed RDR from all of the queries
* Changed fillna to '0' (rather than 'No Data')
* Verified outputs using a combined dataset as a sample
=> [EDQ-407] Prevented 'RDR' from Populating; Changed 'No Data' Values to '0'

data_steward/analytics/table_metrics/metrics_over_time.py, data_steward/analytics/table_metrics/other_scripts/visit_date_disparity.py, data_steward/analytics/table_metrics/weekly_scripts/visit_date_disparity.py
* Changed it so the dataset is imported from the notebooks module - never explicitly written in.
   * Finished with the procedure, observation, measurement, drug, and condition table queries and calculations.   
   * Successfully merged all of the dataframes and outputted to a CSV   
* Created a valid 'other scripts' version of the date disparity check. Essentially removed the unioned_ehr prefixes.
* Made appropriate changes to m_o_t notebook and verified on all 6 fronts.
=> [EDQ-417][EDQ-419] 'Visit Date Disparity' notebooks and changes

.gitignore, data_steward/analytics/tools/dq_issue_tracker/class_definitions.py, data_steward/analytics/tools/dq_issue_tracker/create_dq_issue_site_dfs.py, data_steward/analytics/tools/dq_issue_tracker/cross_reference_functions.py, data_steward/analytics/tools/dq_issue_tracker/dictionaries_and_lists.py, data_steward/analytics/tools/dq_issue_tracker/general_functions.py
Package is intended to create unique dashboards that detail all of the current data quality issues for the sites. The main script in this file should ultimately generate Excel files that can easily be distributed to an online project management platform.
=> [EDQ-427] Python package to create a 'Data Quality Issue' dashboard

data_steward/resources/fields/cdr_metadata.json, data_steward/tools/add_cdr_metadata.py, data_steward/tools/deid_runner.sh, data_steward/tools/generate_combined_dataset.sh, data_steward/tools/run_curation_pipeline.sh, tests/unit_tests/data_steward/tools/add_cdr_metadata_test.py
=> [DC-347] Populate cdr_metadata table with cdr generation metadata

.gitignore, data_steward/analytics/table_metrics/metrics_over_time/aggregate_metric_classes.py, data_steward/analytics/table_metrics/metrics_over_time/auxillary_aggregate_functions.py, data_steward/analytics/table_metrics/metrics_over_time/create_aggregate_objects.py, data_steward/analytics/table_metrics/metrics_over_time/data_quality_metric_class.py, data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_dqm_objects.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/hpo_class.py, data_steward/analytics/table_metrics/metrics_over_time/messages.py, data_steward/analytics/table_metrics/metrics_over_time/metrics_over_time.py, data_steward/analytics/table_metrics/metrics_over_time/organize_dataframes.py, data_steward/analytics/table_metrics/metrics_over_time/populate_dfs_with_aggregate_info.py, data_steward/analytics/table_metrics/metrics_over_time/setup_dataframes.py, data_steward/analytics/table_metrics/metrics_over_time/startup_functions.py, data_steward/analytics/table_metrics/metrics_over_time/unweighted_aggregate_metric_functions.py, data_steward/analytics/table_metrics/metrics_over_time/weighted_aggregate_metric_functions.py
Fairly extensive ticket - see the 'create_library_for_mot' branch on my GitHub to see the full commit history.
=> [EDQ-431] Refactored the 'metrics_over_time' script to work as a Python package

data_steward/tools/run_achilles_and_export.py, data_steward/validation/export.py, data_steward/validation/main.py, tests/integration_tests/data_steward/validation/export_test.py, tests/unit_tests/data_steward/validation/main_test.py
Improve run_export for exporting Achilles results for HPOs and datasets
Fixed test cases
=> [DC-742] Improve run_export for exporting Achilles results for HPOs and datasets

data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/hpo_class.py, data_steward/analytics/table_metrics/metrics_over_time/messages.py, data_steward/analytics/table_metrics/weekly_scripts/date_datetime_disparity.py
* Includes a notebook that calculates the percentage of 'date/datetime disagreements' for the following tables: condition_occurrence, procedure_occurrence, visit_occurrence, drug_exposure, measurement, observation
* Changed the metrics_over_time library to accommodate for this new metric (part of EDQ-425)
* Validated the output for the resulting metrics_over_time script
=> [EDQ-413] Create 'date/datetime disparity' data quality metric notebook

data_steward/deid/aou.py, data_steward/deid/parser.py, data_steward/deid/press.py, data_steward/tools/run_deid.py, tests/unit_tests/data_steward/deid/parser_test.py, tests/unit_tests/data_steward/tools/run_deid_test.py
Modified existing code in run_deid.py, aou.py, press.py, parser.py, and run_deid_test.py. Created unittest, parser_test.py, to test changes made in parser.py module.
=> [DC-744] Updated deid script to drop 'combined' in output dataset ID

data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/hpo_class.py, data_steward/analytics/table_metrics/metrics_over_time/messages.py, data_steward/analytics/table_metrics/metrics_over_time/metrics_over_time.py, data_steward/analytics/table_metrics/other_scripts/concept_success_rate.py, data_steward/analytics/table_metrics/other_scripts/data_after_death.py, data_steward/analytics/table_metrics/other_scripts/date_datetime_disparity.py, data_steward/analytics/table_metrics/other_scripts/diabetes_completeness.py, data_steward/analytics/table_metrics/other_scripts/drug_integration_success_rate.py, data_steward/analytics/table_metrics/other_scripts/drug_route_success_rate.py, data_steward/analytics/table_metrics/other_scripts/duplicates.py, data_steward/analytics/table_metrics/other_scripts/end_before_begin.py, data_steward/analytics/table_metrics/other_scripts/erroneous_dates.py, data_steward/analytics/table_metrics/other_scripts/measurement_integration_success_rate.py, data_steward/analytics/table_metrics/other_scripts/measurement_units_success_rate.py, data_steward/analytics/table_metrics/other_scripts/person_id_foreign_key_notebook.py, data_steward/analytics/table_metrics/other_scripts/source_concept_success_rate.py, data_steward/analytics/table_metrics/other_scripts/visit_date_disparity.py, data_steward/analytics/table_metrics/weekly_scripts/duplicates.py, data_steward/analytics/table_metrics/weekly_scripts/person_id_foreign_key_notebook.py
* Includes a notebook that calculates the percentage of missing/invalid 'person_id' fields for the following tables: condition_occurrence, procedure_occurrence, visit_occurrence, drug_exposure, measurement, observation.
* Changed the metrics_over_time library to accommodate for this new metric (part of EDQ-425)
* Validated the output for the resulting metrics_over_time script
* Modified the 'non-weekly' scripts that produce the data quality metrics. Modifications typically involved removing the `unioned_ehr` prefix and intentionally excluding RDR from the output. This allows for 'apples-to-apples' comparisons of data quality over time.
=> [EDQ-418][EDQ-433] Created 'foreign key' notebook. Modified retrospective scripts.

.circleci/config.yml, .githooks/pre-push, .githooks/prepare-commit-msg, tools/validate_commit_message.sh, tools/validate_pr_title.sh
- Add blank files for hook
- Add pre-push file and change to prepare-commit-msg
- Propagate exit code in pre-push
- Remove spaces in regex
- Simplify rev-list expression
- Explicitly define develop
=> [DC-759] Require commit message titles to contain a jira issue number

data_steward/README.md, data_steward/notebooks/start.sh, data_steward/tools/consolidated_reports/run_consolidated_report.sh, data_steward/tools/create_ehr_and_rdr_snapshot.sh, data_steward/tools/deid_runner.sh, data_steward/tools/generate_combined_dataset.sh, data_steward/tools/generate_unioned_ehr_dataset.sh, data_steward/tools/import_rdr_omop.sh, data_steward/tools/load_vocab.sh, data_steward/tools/run_achilles_report.sh, data_steward/tools/run_cleaning_rules.sh, data_steward/tools/top_heel_errors.sh
* removed virtual environment creation and deactivation from supporting scripts
* updated README.md with how to create and install to your virtualenv using virtualenv
=> [DC-750] Remove virtualenv setup/activation/teardown from shell scripts

data_steward/tools/deid_runner.sh, data_steward/tools/generate_combined_dataset.sh
=> [DC-765] Update pipeline scripts to follow new naming conventions

data_steward/analytics/tools/dq_issue_tracker/class_definitions.py, data_steward/analytics/tools/dq_issue_tracker/create_dq_issue_site_dfs.py, data_steward/analytics/tools/dq_issue_tracker/cross_reference_functions.py, data_steward/analytics/tools/dq_issue_tracker/dictionaries_and_lists.py, data_steward/analytics/tools/dq_issue_tracker/general_functions.py, data_steward/analytics/tools/email_generator/dictionaries_and_lists.py, data_steward/analytics/tools/email_generator/email_generator.py, data_steward/analytics/tools/email_generator/functions_to_create_dqm_objects.py, data_steward/analytics/tools/email_generator/messages.py, data_steward/analytics/tools/visualizations/completeness/ingredient_usage_visualizations.py, data_steward/analytics/tools/visualizations/completeness/measurement_integration_visualizations.py, data_steward/analytics/tools/visualizations/conformance/concept_success_rate.py, data_steward/analytics/tools/visualizations/conformance/date_datetime_disparity.py, data_steward/analytics/tools/visualizations/conformance/person_id_failure_rate.py, data_steward/analytics/tools/visualizations/conformance/route_concept_populations.py, data_steward/analytics/tools/visualizations/conformance/unit_concept_populations.py, data_steward/analytics/tools/visualizations/plausibility/data_after_death_visualizations.py, data_steward/analytics/tools/visualizations/plausibility/duplicates.py, data_steward/analytics/tools/visualizations/plausibility/end_dates_before_start_dates.py, data_steward/analytics/tools/visualizations/plausibility/erroneous_dates.py
* Implemented the three new NIH metrics into the dictionaries and other sources
* Also includes improvements to the visualizations scripts (e.g. pre-determined scales, matplotlib inline)
* Also modest improvements to the e-mail generator (more informative messages, typo fixes, etc.)
=> [EDQ-437] Modified the 'Data Quality Tabs' Script to Include New Metrics

data_steward/constants/retraction/create_deid_map.py, data_steward/retraction/create_deid_map.py, tests/unit_tests/data_steward/retraction/create_deid_map_test.py
=> [DC-764] Build a tool to create _deid_map for all combined datasets

data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py
Updated clean_mapping.py description
=> [DC-762] Update clean_mapping.py cleaning rule description

data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_consistency.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/bigquery_tests_base.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_consistency_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_test.py
* refactors multiple base class functions into a single base class function
* updates the existing unit test to use the base class function
* some refactors to use common test variables and values
* add tests for all tables modified by the ensure_date_datetime_consistency module
* improved assertion error messages
* removed useless parameters from ensure_date_daetetime_consistency unit test function
* updated default_test function signature in rdr_observation_source_concept_id_suppression_test module
=> [DC-761] Create a base integration cleaning class for rules that modify data

data_steward/analytics/cdr_ops/coverage.py, data_steward/analytics/cdr_ops/data_loss_through_pipeline.py, data_steward/analytics/cdr_ops/ehr_data_quality_dashboard_testing.py, data_steward/analytics/cdr_ops/ehr_demographics_by_site.py, data_steward/analytics/cdr_ops/foreign_key_gaps.py, data_steward/analytics/cdr_ops/notes_volume_distribution.py, data_steward/analytics/cdr_ops/outlier_testing.py, data_steward/analytics/cdr_ops/records_per_capita_analysis.py, data_steward/analytics/tools/email_generator/messages.py, data_steward/analytics/tools/visualizations/completeness/ingredient_usage_visualizations.py, data_steward/analytics/tools/visualizations/completeness/measurement_integration_visualizations.py, data_steward/analytics/tools/visualizations/conformance/concept_success_rate.py, data_steward/analytics/tools/visualizations/conformance/date_datetime_disparity.py, data_steward/analytics/tools/visualizations/conformance/person_id_failure_rate.py, data_steward/analytics/tools/visualizations/conformance/route_concept_populations.py, data_steward/analytics/tools/visualizations/conformance/unit_concept_populations.py, data_steward/analytics/tools/visualizations/plausibility/data_after_death_visualizations.py, data_steward/analytics/tools/visualizations/plausibility/duplicates.py, data_steward/analytics/tools/visualizations/plausibility/end_dates_before_start_dates.py, data_steward/analytics/tools/visualizations/plausibility/erroneous_dates.py
* Also includes minor updates with respect to documentation and annotation
* Created consistency between scripts created by Noah in the CDR Ops Folder and the scripts in the 'table_metrics' folder
=> [EDQ-449] Updated BigQuery Usage in CDR Ops Folder

data_steward/requirements.txt
[DC-790] Fix missing libraries in requirements.txt
[DC-790]: https://precisionmedicineinitiative.atlassian.net/browse/DC-790
=> [DC-790] Fix missing libraries in requirements.txt

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi.py, data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression.py, data_steward/requirements.txt, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi_test.py
Create `null_concept_ids_for_numeric_ppi.py` and integration and unit tests `null_concept_ids_for_numeric_ppi_test.py`
=> [DC-703] Add cleaning rule from DC-537 to the pipeline

data_steward/tools/run_achilles_and_export.py, data_steward/validation/export.py
Add unioned_ehr to whitelist, where it can be prepended to the Achilles tables.
=> [DC-866] Fix union_ehr failing to save achilles_heel_results

data_steward/analytics/cdr_ops/systematic_scripts/height_weight_cleaning_rule_models.py, data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/metrics_over_time.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/data_after_death.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/duplicates.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/end_before_begin.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/visit_date_disparity.py
* Additions for h/w analyses that can be used to better understand the justifications for exclusion criteria
* Minor improvements in the documentation for metrics_over_time modules
=> [EDQ-458] Create Additional Analyses for Height/Weight

data_steward/cdr_cleaner/cleaning_rules/base_cleaning_rule.py, data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py, data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_consistency.py, data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi.py, data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression.py, data_steward/resources.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/base_cleaning_rule_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/clean_mapping_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression_test.py
=> [DC-712] Create Validation Framework for Individual Cleaning Rules

data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression_test.py
* Add new obs source concept
* Use Jinja Template instead of format
=> [DC-702] Add cleaning rule from DC-520 to the pipeline

data_steward/validation/app_errors.py, data_steward/validation/main.py, tests/unit_tests/data_steward/validation/app_errors_test.py, tests/unit_tests/data_steward/validation/main_test.py
* Fix logging message to include bucket
* Prefer f-strings over string format
* Fix Pylint errors
=> [DC-824] Correct alert message formatting

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv
* adding required site information to state generalization lookup csv
=> [DC-917] adding site to lookup csv

data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/metrics_over_time.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/unit_success_rate.py, data_steward/analytics/tools/dq_issue_tracker/class_definitions.py, data_steward/analytics/tools/dq_issue_tracker/create_dq_issue_site_dfs.py, data_steward/analytics/tools/dq_issue_tracker/cross_reference_functions.py, data_steward/analytics/tools/dq_issue_tracker/dictionaries_and_lists.py, data_steward/analytics/tools/dq_issue_tracker/general_functions.py, data_steward/analytics/tools/email_generator/dictionaries_and_lists.py, data_steward/analytics/tools/email_generator/email_generator.py
* DQ issue panel can now accommodate sites that appear in 'newer' analytics reports that do not exist in 'reference' analytics reports 
* Adds saou_uabhs to the dictionaries and lists
* Newer dates in applicable modules
* Docstring formatting in the DQ issue panel
=> [EDQ-522] Increase versatility of DQ issue panel reporter

data_steward/analytics/cdr_ops/systematic_scripts/covid_demographic_visualizations.py
* Shows the validity of the ancestor IDs for the different race categories.
* Includes general functions that can be used for Pandas df manipulation and/or visualization.
* Shows distribution of total, tested, and positive participants for different racial and ethnic categories.
* Includes query that shows the number of COVID tested/positive participants at each site. Query shows information based on both the measurement and condition tables.
* Current analyses are based on ehr_ops and RDR datasets but queries can be easily manipulated if needed.
=> [EDQ-535] COVID Demographics Notebook

data_steward/analytics/table_metrics/combined_deid_scripts/visit_date_disparity.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/visit_date_disparity.py
* Aligns the VDD metric with the specifications outlined in EDQ-514.
* Ensures the presence of all 8 logic points, looks only at before visit start times/after visit end times, always use the start date/datetime fields, etc.
* Implemented the VDD metric for both unioned_ehr and combined/deid scripts.
=> [EDQ-542] Fix Logical Inconsistencies within the VDD Metric

data_steward/analytics/table_metrics/combined_deid_scripts/visit_id_foreign_key_notebook.py, data_steward/analytics/table_metrics/metrics_over_time/constants.py, data_steward/analytics/table_metrics/metrics_over_time/dictionaries_and_lists.py, data_steward/analytics/table_metrics/metrics_over_time/functions_to_create_hpo_objects.py, data_steward/analytics/table_metrics/metrics_over_time/hpo_class.py, data_steward/analytics/table_metrics/metrics_over_time/messages.py, data_steward/analytics/tools/dq_issue_tracker/class_definitions.py, data_steward/analytics/tools/dq_issue_tracker/constants.py, data_steward/analytics/tools/dq_issue_tracker/create_dq_issue_site_dfs.py, data_steward/analytics/tools/dq_issue_tracker/dictionaries_and_lists.py, data_steward/analytics/tools/email_generator/constants.py, data_steward/analytics/tools/email_generator/dictionaries_and_lists.py, data_steward/analytics/tools/email_generator/functions_to_create_hpo_objects.py, data_steward/analytics/tools/email_generator/hpo_class.py, data_steward/analytics/tools/visualizations/conformance/visit_id_failure_rate.py
* Created metric notebooks (unioned_ehr/combined_deid) to see the percentage of valid visit_occurrence_id fields
* Integrated the VO_ID results into the metrics_over_time module
* Integrated the VO_ID results into the dq_issue_tracker module
* Integrated the VO_ID results into the email_generator module
* Created visualization notebook for the visit_id failure rate metric
=> [EDQ-515] VO_ID Failure Rate Metric and Integration

data_steward/analytics/table_metrics/combined_deid_scripts/concept_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/data_after_death.py, data_steward/analytics/table_metrics/combined_deid_scripts/date_datetime_disparity.py, data_steward/analytics/table_metrics/combined_deid_scripts/diabetes_completeness.py, data_steward/analytics/table_metrics/combined_deid_scripts/drug_integration_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/duplicates.py, data_steward/analytics/table_metrics/combined_deid_scripts/end_before_begin.py, data_steward/analytics/table_metrics/combined_deid_scripts/erroneous_dates.py, data_steward/analytics/table_metrics/combined_deid_scripts/measurement_integration_success_rate.py, data_steward/analytics/table_metrics/combined_deid_scripts/number_achilles_errors.py, data_steward/analytics/table_metrics/combined_deid_scripts/person_id_foreign_key_notebook.py, data_steward/analytics/table_metrics/combined_deid_scripts/route_success_rate.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/concept_success_rate.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/data_after_death.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/date_datetime_disparity.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/diabetes_completeness.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/drug_integration_success_rate.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/duplicates.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/end_before_begin.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/erroneous_dates.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/measurement_integration_success_rate.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/number_achilles_errors.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/person_id_foreign_key_notebook.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/route_success_rate.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/source_concept_success_rate.py, data_steward/analytics/table_metrics/unioned_ehr_scripts/unit_success_rate.py
* Naming convention change from the latest curation deployment
=> [EDQ-543] Fix HPO Site Mapping Table Names

data_steward/tools/add_hpo.py, tests/unit_tests/data_steward/tools/add_hpo_test.py
* Add functionality to increment display_orders and add tests
=> [DC-977] New site addition script fails to increment display order

data_steward/tools/add_hpo.py
* Fix lookup table_id in add_hpo.py script
=> [DC-978] Fix lookup table_id in add_hpo.py script

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv
* Add new site to deid state generalization
=> [DC-969] Add Alliance Chicago into the pipeline

data_steward/bq_utils.py, data_steward/requirements.txt, data_steward/tools/top_heel_errors.py, tests/integration_tests/data_steward/bq_utils_test.py, tests/integration_tests/data_steward/tools/top_heel_errors_test.py
* Update requirements
* Remove obsolete function and tests from bq_utils
=> [DC-966] Integration Tests are failing in CircleCI

data_steward/utils/auth.py, data_steward/utils/bq.py, data_steward/validation/email_notification.py, data_steward/validation/main.py, tests/integration_tests/data_steward/utils/bq_test.py, tests/integration_tests/data_steward/validation/email_notification_test.py, tests/integration_tests/data_steward/validation/main_test.py, tests/unit_tests/data_steward/validation/main_test.py
* Add logging for email client and stacktrace
* Use REST API to access spreadsheet linked table
=> [DC-964] Access issue preventing retrieval of HPO contact list via query

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/clean_height_weight.py, data_steward/cdr_cleaner/cleaning_rules/measurement_table_suppression.py, data_steward/cdr_cleaner/cleaning_rules/unit_normalization.py, data_steward/resource_files/fields/extension_tables/measurement_ext.json, data_steward/resources.py, data_steward/tools/snapshot_by_query.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/bigquery_tests_base.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_consistency_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/measurement_table_suppression_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/rdr_observation_source_concept_id_suppression_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/measurement_table_suppression_test.py, tests/unit_tests/data_steward/resources_test.py, tests/unit_tests/data_steward/utils/bq_test.py
cleans implausible measurements
updates how schema files are used to create tables.
=> [DC-699] clean implausible measurements. automate scripts from DC-481

data_steward/validation/main.py, data_steward/validation/metrics/completeness.py, tests/unit_tests/data_steward/validation/main_test.py, tests/unit_tests/data_steward/validation/metrics/completeness_test.py
* Fix is_hpo_col logic and update test
* Remove re-raising error due to failed metric
=> [DC-912] Fix table identification logic in completeness.py

data_steward/validation/app_errors.py, data_steward/validation/main.py, tests/unit_tests/data_steward/validation/app_errors_test.py, tests/unit_tests/data_steward/validation/main_test.py
* Add traceback log wrapper
* Also post error messages to slack
=> [DC-983] Errors not getting logged for Validation and Union EHR

data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded_test.py
* Modified `remove_fitbit_data_if_max_age_exceeded.py` module to use `combined_dataset_id` 
* Modified  both unit and integration tests `remove_fitbit_data_if_max_age_exceeded_test.py` modules to ensure `combined_dataset_id` fix is working properly.
=> [DC-1037] Modify remove_fitbit_data_if_max_age_exceeded.py Module

data_steward/resource_files/aou_vocab/concept.csv
Updated concept_ids in data_steward/resource_files/aou_vocab/concept.csv
- 3000000000 to 2100000000
- 3000000001 to 2100000001
=> [DC-1017] updated the custom concept ids to be within maximum allowed integers

.gitignore, data_steward/tools/clean_fitbit.sh
* Add clean_fitbit.sh to run clean deid rules on fitbit dataset
=> [DC-1038] Create bash script to clean Fitbit data

data_steward/tools/recreate_person.py, tests/integration_tests/data_steward/tools/recreate_person_test.py
* Create tool to update person table with new cols
=> [DC-1013] Create person table with state of residence columns using person_ext

data_steward/resource_files/aou_vocab/concept.csv
Added custom concept for "11+" household size
=> [DC-1060] Generalize Household Size

data_steward/resource_files/aou_vocab/concept.csv
Added custom concept for "6+" for house sizes of 6+ with members under the age of 18
=> [DC-1057] Create custom concept for "6+" and add to vocabulary

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/fix_unmapped_survey_answers.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/fix_unmapped_survey_answers_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/fix_unmapped_survey_answers_test.py
- completed the cleaning rule fix_unmapped_survey_answers
- added the unit test for fixed_unmapped_survey_answers
- added the integration test for fix_unmapped_survey_answers
=> [DC-1053] Cleaning Rule for fixing the unmapped survey answers

data_steward/tools/run_cleaning_rules.sh
creates a staging dataset and applies cleaning rules on the staging dataset.
=> [DC-1073] Updates run_cleaning_rules.sh

data_steward/tools/generate_combined_dataset.sh
Modified bash script, added labels to each created dataset
=> [DC-1069] Update Generate Combined Dataset

tests/integration_tests/data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info_test.py
* integration test needed to be updated after the clean engine update changes
=> [DC-1087] fix broken integration test

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_past_deactivation_date.py, data_steward/retraction/retract_deactivated_pids.py, data_steward/tools/generate_unioned_ehr_dataset.sh
Add apply cleaning rule step to generate_unioned_ehr_dataset.sh
=> [DC-1083] / [DC-1086] Move remove_ehr_data_post_deactivation cleaning rule from clean_cdr to generate_unioned_ehr_dataset.sh script

data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py
* Modified query to include new AOU concept code
* Modified integration test to properly test changes to cleaning rule
=> [DC-1058] Modify Numeric PPI response cleaning rule to include "6+" generalization

data_steward/tools/create_ehr_and_rdr_snapshot.sh
added labels to datasets created by create_ehr_and_rdr_snapshot.sh
=> [DC-1067] added labels to datasets in create_ehr_and_rdr_snapshot.sh

data_steward/cdr_cleaner/cleaning_rules/truncate_fitbit_data.py, data_steward/tools/truncate_fitbit.sh
* Created bash script `truncate_fitbit.sh` to run the `truncate_fitbit_data` cleaning rule
* Modified `TRUNCATE_FITBIT_DATA_QUERY` to account for participants who have submitted data before and after the cutoff date.
=> [DC-1078] Truncate FitBit Data

data_steward/cdr_cleaner/cleaning_rules/README.md, data_steward/cdr_cleaner/cleaning_rules/deid/fitbit_dateshift.py, data_steward/cdr_cleaner/cleaning_rules/deid/pid_rid_map.py, data_steward/tools/clean_fitbit.sh, data_steward/tools/create_ehr_and_rdr_snapshot.sh, data_steward/tools/deid_runner.sh, data_steward/tools/generate_combined_dataset.sh, data_steward/tools/run_cleaning_rules.sh
* Updated bash scripts to create sandbox with the appropriate labels
=> [DC-1088] Bash script sandbox update

data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/null_concept_ids_for_numeric_ppi_test.py
adds else clauses
updates integration test
=> [DC-1098] Add ELSE clauses to null_concept_ids_for_numeric_ppi

data_steward/tools/deid_runner.sh
=> [DC-1104] Fix HANDOFF_DATE error

data_steward/tools/create_ehr_and_rdr_snapshot.sh, data_steward/tools/generate_combined_dataset.sh
* Add env variable VALIDATION_RESULTS_DATASET_ID
* Add log file for rdr cleaning rules
=> [DC-1027] Prep RDR export

data_steward/cdr_cleaner/manual_cleaning_rules/remove_operational_pii_fields.py
*  Add backtick in query for table name
=> [DC-1105] Add backtick for remove_operational_pii_fields CR

data_steward/cdr_cleaner/manual_cleaning_rules/remove_operational_pii_fields.py
* Add backtick in DELETE query
=> [DC-1106] Add missing backtick in delete query for Operational PII field CR

data_steward/tools/generate_unioned_ehr_dataset.sh
* Needed by populate_route_ids CR
=> [DC-1112] Export VOCABULARY_DATASET in unioned script

data_steward/constants/tools/combine_ehr_rdr.py, tests/integration_tests/data_steward/tools/combine_ehr_rdr_test.py, tests/unit_tests/data_steward/tools/combine_ehr_rdr_test.py
* adds backticks to the combined script SQL statements
* updates the associated unit test
=> [DC-1121] add backticks to combined script SQL statements

data_steward/resource_files/templates/hpo_report.html
Updated the link in `hpo_report.html` file
=> [DC-1063] Fix Broken Link in results.html

.circleci/config.yml
* [DC-997] Add check for repo for builds on develop (prevents nightly clash)
[DC-997]: https://precisionmedicineinitiative.atlassian.net/browse/DC-997
=> [DC-997] Build conflicts due to nightly builds running on forks

data_steward/cdr_cleaner/cleaning_rules/README.md, data_steward/resource_files/fields/additional_rdr_tables/pid_rid_mapping.json, data_steward/resources.py, data_steward/tools/generate_rids_from_participantsummaryAPI.py, data_steward/tools/import_rdr_omop.sh, data_steward/tools/run_deid.py
* [DC-1124] Add pid_rid_mapping schema
* [DC-1124] Update pid_rid_mapping references to _deid_map
* [DC-1124] Update bash script to ingest pid_rid_mapping
* [DC-1124] Exclude pid_rid_mapping from CDM files
[DC-1124]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1124
[DC-1124]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1124
[DC-1124]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1124
[DC-1124]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1124
=> [DC-1124] Add capability to ingest pid_rid_mapping in import_rdr_omop

data_steward/cdr_cleaner/clean_cdr_engine.py
* [DC-1132] Extend timeout to accommodate long running jobs
[DC-1132]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1132
=> [DC-1132] Extend timeout to accommodate long running jobs

data_steward/validation/metrics/required_labs.py, tests/integration_tests/data_steward/metrics/required_labs_test.py
Added condition to `required_labs.py` to check if `MEASUREMENT_CONCEPT_SETS_DECENDANTS_TABLE` and `MEASUREMENT_CONCEPT_SETS_TABLE` exists which will be created if they do not.
=> [DC-916] required_labs.py assumes concept tables exists in target ehr dataset

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv
* updates the static state file for deid usage
=> [DC-1130]  add saou_cgmhs to pipeline

data_steward/tools/create_ehr_and_rdr_snapshot.sh
* Added command line argument for date in form of yyyy-mm-dd
* Updated the ehr dataset description to utilize the date
=> [DC-1154] Update Snapshot Description

data_steward/tools/generate_ext_tables.py, tests/unit_tests/data_steward/tools/generate_ext_tables_test.py
* Updated strings to f-strings
* Updated SQL to use JINJA_ENV
=> [DC-1167] generate_ext_tables Formatting Fix

data_steward/cdr_cleaner/clean_cdr_engine.py
* [DC-1180] Remove timeout arg
[DC-1180]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1180
=> [DC-1180] Remove timeout argument for clean engine

data_steward/analytics/cdr_ops/ad_hoc_analyses/height_weight_distribution.py, data_steward/analytics/cdr_ops/ad_hoc_analyses/unit_standardization.py, data_steward/notebooks/measurement_hist_utils.py
* moved the common functions for creating histgrams to measurement_hist_utils
* dded height_weight_distribution.py and refactored unit_standardization.py
=> [DC-1136] Create a notebook for visualizing height and weight distributions

data_steward/tools/generate_ehr_upload_pids.py, tests/integration_tests/data_steward/tools/generate_ehr_upload_pids_test.py, tests/unit_tests/data_steward/tools/generate_ehr_upload_pids_test.py
* [DC-1166] Add script to generate query
* [DC-1166] Add tests
* [DC-1166] Add docstrings
[DC-1166]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1166
[DC-1166]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1166
[DC-1166]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1166
=> [DC-1166] Simplify workflow for updating ehr_upload_pids

tests/integration_tests/data_steward/sandbox_test.py, tests/integration_tests/data_steward/utils/bq_test.py
* [DC-996] Update sandbox_test.py
* [DC-996] Update utils/bq_test.py
[DC-996]: https://precisionmedicineinitiative.atlassian.net/browse/DC-996
[DC-996]: https://precisionmedicineinitiative.atlassian.net/browse/DC-996
=> [DC-996] Dataset collisions while running integration tests

data_steward/resource_files/fields/cope_survey_semantic_version_map.json
* created cope_survey_semantic_version_map.json for rdr20201201 export
=> [DC-1251] Add cope_survey_semantic_version_map json file

data_steward/dev_requirements.txt, tests/run_tests.sh, tests/runner.py, tools/automate_all_tests.sh
* adds a developement requirement for python 3.6 needs
* sends test output to stdout isntead of stderr to prevent intermingling of stdout and stderr in the log file
* creates an automation script.  Script should be runnable from a cron job.
=> [DC-1020] Add script to run tests in GCE VM to curation repo

data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_past_deactivation_date.py, data_steward/retraction/retract_deactivated_pids.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_past_deactivation_date_test.py, tests/unit_tests/data_steward/retraction/retract_deactivated_pids_test.py
* [DC-1100] Update query and fix tests 
* [DC-1100] Fix tests in related cleaning rule
[DC-1100]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1100
[DC-1100]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1100
=> [DC-1100] Create get_date_columns utility for deactivation retraction

data_steward/constants/retraction/retract_utils.py, data_steward/retraction/retract_data_bq.py, data_steward/retraction/retract_utils.py, tests/integration_tests/data_steward/retraction/retract_data_bq_test.py, tests/unit_tests/data_steward/retraction/retract_data_bq_test.py, tests/unit_tests/data_steward/retraction/retract_utils_test.py
* [DC-1183] Update query and fix tests
[DC-1183]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1183
=> [DC-1183] Create get_dataset_list utility for deactivation retraction

data_steward/tools/set_path.sh, tests/README.md, tests/run_tests.sh
Minor changes to tests shell script and README
=> [DC-1274] Running Unit tests upgrade

.pylintrc
This is a fix for a bug in pylint that is triggered by exceeding maximum recursion depth.
=> [DC-956] Pylint Recursion Fix

data_steward/resource_files/achilles_heel_dml.sql
* changed code for rule 301 to use `provider` instead of `provider specialty` in `achilles_heel_dml.sql` file
=> [DC-946] Speciality error in ACHILLES Heel rule#301

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/rerpopulate_person_post_deid_test.py
* Refactors repopulate_person_post_deid CR to use base class
* adds unittests
* Fixes integration test
=> [DC-836] [DC-1194] Update Person Table Repopulation CR to New Base Class

data_steward/utils/bq.py, tests/integration_tests/data_steward/utils/bq_test.py, tests/unit_tests/data_steward/utils/bq_test.py
[DC-1297] Update bq.get_client() to require project and accept creds
[DC-1297]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1297
=> [DC-1297] Update get_client() in utils/bq.py

data_steward/tools/recreate_cope_concepts.py
=> [DC-1284] Adds script to recreate cope_concepts table

data_steward/resource_files/aou_vocab/concept.csv
=> [DC-1303] Add Custom Concepts for COPE Surveys

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv
* [DC-1344] Add hpo site SSHC to deid state lookup
[DC-1344]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1344
=> [DC-1344] Add Sixteenth Street Community Health Center to pipeline

data_steward/tools/generate_ehr_upload_pids.py
=> [DC-1389] Fixed missing pmids in view

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/null_person_birthdate.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/null_person_birthdate_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/null_person_birthdate_test.py
Creates a new Controlled Tier cleaning rule for nulling person birthdates.
=> [DC-1356] Null person table birth date fields

data_steward/cdr_cleaner/cleaning_rules/deid/fitbit_pid_rid_map.py, data_steward/cdr_cleaner/cleaning_rules/deid/pid_rid_map.py, data_steward/common.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/fitbit_pid_rid_map_test.py
* [DC-1333] Generalize PID RID map clean rule
* [DC-1333] Update tests and remove unnecessary methods
[DC-1333]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1333
[DC-1333]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1333
=> [DC-1333] Generalize pid_rid_map cleaning rule

data_steward/tools/load_vocab.py, tests/unit_tests/data_steward/tools/load_vocab_test.py
The limitations of this script will be noted in the associated ticket. Necessary adjustments will be in separate tickets.
=> [DC-1392] Refactor load_vocab script to python

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/ct_pid_rid_map.py, data_steward/cdr_cleaner/cleaning_rules/deid/pid_rid_map.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/ct_pid_rid_map_test.py
* [DC-1336] Add controlled tier pid-rid class
* [DC-1336] Add integration test for controlled tier pid-rid class
[DC-1336]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1336
[DC-1336]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1336
=> [DC-1336] Create controlled tier pid_rid_map cleaning rule

data_steward/tools/create_ehr_and_rdr_snapshot.sh
* validation_dataset is not needed to run ehr and rdr snapshots
* parameter requirement is removed
=> [DC-1433] remove unused parameter from ehr/rdr script

data_steward/analytics/cdr_ops/rdr_export_qc.py
* adding some missing backticks about fully qualified table names
* adding leading underscores to fields named based on dataset names.  field names cannot start with numbers.
* add smoking checks query
* add comment to numerics in `value_as_string` check
=> [DC-1434] updating the rdr evaluation notebook

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/cancer_concept_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/cancer_concept_suppression_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/cancer_concept_suppression_test.py
Suppresses a set of cancer related concept codes.
=> [DC-1381] Record Suppress some cancer condition concepts

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv
Updated src_hpo_to_allowed_states.csv
=> [DC-1383] Add Gundersen Health

data_steward/tools/create_tier.py, data_steward/utils/auth.py, tests/unit_tests/data_steward/tools/create_tier_test.py
* add ability to impersonate credentials with: end user credentials, service account referenced via environment variable, service account referenced via key file path
* add credentials getter to create_tier script
* require impersonation target in create_tier script
* make credentials filepath optional
=> [DC-1291] add ability to impersonate service account credentials

data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info.py, tests/integration_tests/data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info_test.py
* [DC-1304] Update query and test
[DC-1304]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1304
=> [DC-1304] COPE Survey Versions for 2021Q2 CDR

data_steward/cdr_cleaner/cleaning_rules/deid/concept_suppression.py
* Modified get_table_in_dataset function to properly check for errors
=> [DC-1440] Fix error reporting bug in concept_suppression.py

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/aggregate_zip_codes.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/aggregate_zip_codes_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/aggregate_zip_codes_test.py
This creates a cleaning rule for merge localized zip codes and states.
=> [DC-1379] Aggregate Some Generalized Zip Code Values

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables_test.py
Cleaning rule to remove extra tables at the end of the controlled tier generation pipeline.
=> [DC-1441] Remove any extra tables from the controlled tier deid dataset

data_steward/cdr_cleaner/cleaning_rules/null_person_birthdate.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/null_person_birthdate_test.py
* [DC-1448] Use UPDATE instead of SELECT *
=> [DC-1448] NullPersonBirthdate changes schema of person table

data_steward/cdr_cleaner/cleaning_rules/create_person_ext_table.py, data_steward/resource_files/fields/extension_tables/person_ext.json
Correcting a bug where person_ext table is not loaded from the staging dataset.
=> [DC-1140] Snapshot_by_query does not copy person_ext from staging

data_steward/cdr_cleaner/cleaning_rules/unit_normalization.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/unit_normalization_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/unit_normalization_test.py
* updates unit normalization code
* updates existing integration test
=> [DC-1458] unit normalization should store _unit_mapping in sandbox dataset

data_steward/tools/create_tier.py
* Added add_argument for qa_handoff_date which will default to today's
date
* Added *args to create_tier function
=> [DC-1459] Add _cdr_metadata table QA handoff date if creating deid_base dataset

data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py
* [DC-1513] Update mapping queries
* [DC-1513] Use single query template
=> [DC-1513] CleanMappingExtTables rule introduces duplicates

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid_test.py
Converted this integration to the new base class format.
=> [DC-1198] Integration Test for Missing Race Responses CR

data_steward/cdr_cleaner/clean_cdr_utils.py, data_steward/cdr_cleaner/cleaning_rules/deid/concept_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/string_fields_suppression.py, data_steward/cdr_cleaner/cleaning_rules/id_deduplicate.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/id_de_duplicate_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/id_deduplicate_test.py
* Add Integration test for id_deduplicate CR
* refactored get_tables_in_dataset to clean_cdr_utils.py to use in in setup_rule()
=> [DC-1202] Integration Test for Deduplication of ID Columns CR

data_steward/cdr_cleaner/cleaning_rules/temporal_consistency.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/temporal_consistency_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/temporal_consistency_test.py
* [DC-1204] Create integration test
* [DC-1204] Update integration test and fix CR
=> [DC-1204] Integration Test for Temporal Data Point CR

data_steward/cdr_cleaner/cleaning_rules/fill_source_value_text_fields.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/fill_source_value_text_fields_test.py
Restrict cleaning rule operation on zip code observations.
=> [DC-1510] Prevent overwriting generalized zip code data in CT deid_base

data_steward/common.py, data_steward/resource_files/fields/pipeline_tables/pid_rid_mapping.json, data_steward/resources.py, data_steward/tools/store_mappings.py, data_steward/utils/auth.py, tests/unit_tests/data_steward/utils/bq_test.py
Script saves only new mappings to primary mapping table and adds randomized shift integer between 1 and 365 inclusive.
Corrects an f-string in the auth module.
Adds variable definitions to common module.
Adds table definition for pipeline_tables.pid_rid_mapping.
updates unit test because of name clash with newly added table definition.
simplifies rdr_additional_table in resources module.
=> [DC-1518] [DC-1543] create primary pid/rid/shift storage script

data_steward/tools/import_rdr_omop.sh
* Add condition to prevent clustering for the `pid_rid_mapping` table
=> [DC-1551] Update import_rdr_omop.sh

data_steward/constants/validation/ehr_union.py, data_steward/validation/ehr_union.py, tests/integration_tests/data_steward/validation/ehr_union_test.py, tests/unit_tests/data_steward/validation/ehr_union_test.py
Adds an integer representing the HPO site to the observation id in order to eliminate duplicates.
=> [DC-1512] Person records are duplicated in observation and observation_ext table

tests/integration_tests/data_steward/utils/participant_summary_requests_test.py, tests/unit_tests/data_steward/utils/participant_summary_requests_test.py
* [DC-1075] Move integration test to unit test
[DC-1075]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1075
=> [DC-1075] Move contents of a participant summary integration test

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/organ_transplant_concept_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/organ_transplant_concept_suppression_test.py
Adds cleaning rule to suppress Organ transplant(other) concepts
=> [DC-1529] Record suppress two missed concepts(organ transplant - other)

data_steward/cdr_cleaner/cleaning_rules/deid/pid_rid_map.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/ct_pid_rid_map_test.py
* [DC-1537] Add delete statement and update warning log
[DC-1537]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1537
=> [DC-1537] Drop records without a valid pid/rid mapping

data_steward/tools/create_tier.py, tests/unit_tests/data_steward/tools/create_tier_test.py
* Updated `create_tier.create_datasets` to drop the tier from the sandbox_dataset_id
* Updated `create_tier_test.test_create_datasets` to test the changes
made in `create_tier.create_datasets`
=> [DC-1521] Shared Sandbox Name Fix

data_steward/tools/run_deid.py
* Removed `care_site` from `DEID_TABLES` list
* Added `care_site` to `SUPPRESSED_TABLES` list
=> [DC-1477] Suppress care_site table in RT deid

data_steward/tools/deid_runner.sh
* add --force flag to sandbox creation line.  will not throw an error if the dataset already exists
* moves sandbox creation prior to running cleaning rules
=> [DC-1404] do not fail if registered tier sandbox already exists

data_steward/cdr_cleaner/cleaning_rules/domain_alignment.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/domain_alignment_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/domain_alignment_test.py
* [DC-1589] Use single unioned query for domain alignment
[DC-1589]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1589
=> [DC-1589] Union domain alignment logging table queries to a single query

data_steward/init_env.sh
* [DC-1591] Update bash script to include project username
[DC-1591]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1591
=> [DC-1591] Use circle project in bucket and dataset creation to reduce conflicts

data_steward/retraction/retract_data_gcs.py, data_steward/utils/gcs.py, tests/integration_tests/data_steward/retraction/retract_data_gcs_test.py, tests/unit_tests/data_steward/utils/gcs_test.py
* [DC-1594] Add GCS helpers in utils
* [DC-1594] Update GCS script to use client library, f-strings
[DC-1594]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1594
[DC-1594]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1594
=> [DC-1594] Update GCS retraction to use client library

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_height_weight_test.py
* Added test_cleaning_results test to utilize subTests in order for
setUp to be called once
=> [DC-1532] Clean Height Weight Integration Test Fix

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/id_de_duplicate_test.py
* [DC-1590] Reduce table creation-drop instances to just once
[DC-1590]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1590
=> [DC-1590] Reduce table creation and drop for ID deduplicate test

data_steward/tools/run_deid.py
* Changed `DEID_MAP_TABLE` name to `primary_pid_rid_mapping`
=> [DC-1602] Incorrect Name for DEID_MAP_TABLE in run_deid.py

data_steward/deid/rules.py
* Changed logging message from error to info
=> [DC-1610] Miscategorized Error Message In rules.py

data_steward/tools/run_deid.py
* Changed `deid_map_table` f-string to be the `_deid_map` table
=> [DC-1608] _deid_map Table Should Be Created and Loaded Instead Of primary_pid_rid_mapping Table in run_deid.py

data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info.py, tests/integration_tests/data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info_test.py
* Updated `qrid_map_dataset_id` to be the shared sandbox dataset id
* Updated the integration test to reflect the changes in the module
=> [DC-1605] Use Shared Sandbox In `survey_version_info.py` Manual Cleaning Rule

data_steward/deid/config/ids/config.json
* Add compute logic back to config.json file
=> [DC-1609] Add `compute` Logic Back To config.json File

data_steward/resources.py
* Created new file path for mapping tables
* Updated the `mapping_schemas` to use `mapping_fields_path`
=> [DC-1603] Incorrect path for mapping tables in resources.mapping_schemas

data_steward/cdr_cleaner/cleaning_rules/remove_invalid_procedure_source_records.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_invalid_procedure_source_records_test.py
fix invalid_procedure_source references its own sandbox dataset id
=> [DC-1481] fix invalid_procedure_source references its own sandbox dataset id

data_steward/resources.py, data_steward/tools/create_rdr_snapshot.py, data_steward/tools/import_rdr_omop.py, data_steward/utils/bq.py
=> [DC-1600] converting bash to python scripts

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/string_fields_suppression.py
* Add cleaning rule to REGISTERED_TIER_DEID_CLEANING_CLASSES list
* Updated affected datasets in cleaning rule module
=> [DC-1698] observation_source_value Values Not Nulled In R2021q2r1_deid

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_without_consent.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_without_consent_test.py
* Added Cleaning rule to remove EHR data where EHR consent cannot be located
* Added Integration tests
=> [DC-1644] Remove EHR data where EHR consent cannot be located

data_steward/init_env.sh
* [DC-1669] Update to June vocabulary
[DC-1669]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1669
=> [DC-1669] Vocabulary Update - for PPI

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/registered_cope_survey_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/registered_cope_survey_suppression_test.py
* [RT - Deid] Record Suppress February COPE Question concepts
* Added Integration tests
=> [DC-1666] Record Suppress February COPE Question concepts

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/covid_ehr_vaccine_concept_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/concept_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/covid_ehr_vaccine_concept_suppression_test.py
Suppresses COVID EHR vaccine records in all CDM tables.
=> [DC-1692] Suppress Covid EHR vaccine records

data_steward/resource_files/schemas/rdr/pid_rid_mapping.json
Update pi_rid_mapping schema to add vibrent_id schema.
=> [DC-1701] [P0] raw `pid_rid_mapping` schema changed on RDR import

data_steward/cdr_cleaner/cleaning_rules/deid/repopulate_person_controlled_tier.py, data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid.py, data_steward/constants/cdr_cleaner/clean_cdr.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/repopulate_person_controlled_tier_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid_test.py
Expands the subgroups used in repopulation ethnicity person fields.
=> [DC-1664] CT is not repopulating `ethnicity_concept_id` the same as RT

data_steward/constants/validation/email_notification.py, data_steward/validation/email_notification.py, tests/unit_tests/data_steward/validation/email_notification_test.py
* [DC-1689] Update reply to in email body and improve formatting
[DC-1689]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1689
=> [DC-1689] Update email address on automated data submission emails

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/genaralize_cope_insurance_answers.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/generalize_cope_insurance_answers_test.py
*  Added cleaning rule to generalize answers to COPE Insurance Question
* Added integration test to test the generalization
=> [DC-1665] Generalize answers to COPE Insurance Question

data_steward/requirements.txt, data_steward/tools/copy_dataset_to_output_prod.py, tests/unit_tests/data_steward/tools/copy_dataset_to_output_prod_test.py
Created a python script from transferring tables from one project to another.
=> [DC-1580] Create python script to run dataset output process

data_steward/analytics/cdr_ops/rdr_export_qc.py
* Added code to check that participants with data in other survey modules also have data from the basics survey module to the RDR notebook
=> [DC-1319] RDR eval: Add check for basics survey module

data_steward/tools/generate_combined_dataset.sh
Update clean_cdr to use combined_sandbox instead of combined_staging_sandbox
* remove steps that drop staging and staging_sandbox datasets
=> [DC-1675] Remove usage of staging_sandbox and drop steps that delete staging datasets

data_steward/cdr_cleaner/cleaning_rules/temporal_consistency.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/temporal_consistency_test.py
* [DC-1733] Remove left joins
[DC-1733]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1733
=> [DC-1733] Simplify and fix query in temp_consistency

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/remove_row_duplicates.py
=> [DC-1732] Deduplicate rows based on columns except id

data_steward/tools/generate_combined_dataset.sh
* Commented out de_duplication cleaning rule in clean_cde.py
* updated generate_combined_dataset.sh to use correct sandbox_dataset name
[skip ci]
=> [DC-1675] updated generate_combined_dataset.sh to use correct sandbox_dataset name

data_steward/cdr_cleaner/cleaning_rules/deid/registered_cope_survey_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/registered_cope_survey_suppression_test.py
* suppressing 4 additional concepts: 1332742, 1333324, 1333014, 715711
=> [DC-1750] adding more registered tier cope survey suppressions

data_steward/cdr_cleaner/cleaning_rules/domain_alignment.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/domain_alignment_test.py
Excluded PPI concepts from being sandboxed during domain alignment.
=> [DC-1615] domain alignment rule is dropping some PPI concepts

data_steward/deid/config/ids/config.json, data_steward/deid/config/ids/tables/observation.json, data_steward/deid/rules.py
* generalize the answers for a question that is similar to a perviously generalized question
* treat COPE concept same as a Basics concept
=> [DC-1774] changes to generalize code 1332843

data_steward/analytics/cdr_ops/combined.py, data_steward/analytics/cdr_ops/ehr_snapshot_qc.py, data_steward/analytics/cdr_ops/utils.py, data_steward/utils/bq.py
[DC-1756] Add notebook with EHR snapshot checks
[DC-1756]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1756
=> [DC-1756] Create notebook for EHR snapshot validation

data_steward/tools/fitbit/clean_fitbit.sh
* [DC-1780] Update fitbit script to use clean_cdr.py
[DC-1780]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1780
=> [DC-1780] Update fitbit script to use clean_cdr

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/round_ppi_values_to_nearest_integer.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/round_ppi_values_to_nearest_integer_test.py
* Updated Cleaning rule to Base class to add integration tests
* Added Integration test
=> [DC-1276] Add Missing cope concepts in rounding free-numeric PPI values

data_steward/tools/create_tier.py, data_steward/utils/bq.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/domain_alignment_test.py
* [DC-1779] Remove usages of get_dataset
* [DC-1779] Update usages of get_dataset
[DC-1779]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1779
[DC-1779]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1779
=> [DC-1779] Remove `get_dataset` wrapper defined in `utils/bq.py`

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/remove_non_existing_pids.py, data_steward/tools/fitbit/clean_fitbit.sh, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/remove_non_existing_pids_test.py
* [DC-1787] Create CR to remove data for PIDs not in CDR
* [DC-1787] Update CR and add test
[DC-1787]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1787
[DC-1787]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1787
=> [DC-1787] Create cleaning rule to remove records for pids not in CDR

data_steward/retraction/create_deid_map.py, data_steward/retraction/retract_utils.py, data_steward/utils/bq.py, data_steward/utils/sandbox.py, tests/unit_tests/data_steward/retraction/create_deid_map_test.py, tests/unit_tests/data_steward/retraction/retract_utils_test.py, tests/unit_tests/data_steward/validation/main_test.py
* [DC-1778] Remove usages of list_datasets
[DC-1778]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1778
=> [DC-1778] Remove `list_datasets` wrapper defined in `utils/bq.py`

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv
Add vcu to src_hpos_to_allowed_states.csv
=> [DC-1818] Add Virginia Commonwealth University to pipeline

data_steward/participant_validation/validate_email.py, data_steward/tools/create_update_drc_id_match_table.py, data_steward/tools/store_participant_summary_results.py, data_steward/validation/participants/participant_validation_queries.py, data_steward/validation/participants/validate.py, tests/integration_tests/data_steward/participant_validation/validate_email_test.py, tests/integration_tests/data_steward/tools/create_update_drc_id_match_table_test.py, tests/integration_tests/data_steward/tools/store_participant_summary_results_test.py, tests/integration_tests/data_steward/utils/participant_summary_requests_test.py, tests/integration_tests/data_steward/validation/participants/validate_test.py
This is the first of several tickets for participant validation. It also includes some modifications to the `create_update_drc_id_match_table.py` script.
=> [DC-1235] Add structure for queries and DRC Email Comparisons

tests/integration_tests/data_steward/validation/achilles_heel_test.py, tests/integration_tests/data_steward/validation/export_test.py, tests/test_util.py
By loading csv files from a test bucket
=> [DC-1847] Fix broken achilles integration tests

data_steward/cdr_cleaner/reporter.py
* updating the reporter to better identify base classed cleaning rules with variable number of parameters.
* updates logging and displays how the class is instantiated
=> [DC-1861] reporter update

data_steward/validation/participants/participant_validation_queries.py, data_steward/validation/participants/validate.py, tests/integration_tests/data_steward/validation/participants/validate_test.py
* Add phone number comparison to participant validation
* add integration test cases
=> [DC-1236] Perform DRC Phone Number Comparisons

data_steward/cdr_cleaner/reporter.py
- moving much of the business logic for class-based cleaning rules into "get_class_info" func
- no longer relying on existence of "get_query_specs" to determine if instance is subclass of base cleaning rule
- no longer attempting to execute each function
@lrwb-aou I need guidance on two pieces:
1. What should be done in the scenario where an object _is_ provided but it is _not_ a subclass of the base cleaning rule?  Should it throw an exception?
2. What was the original intent behind executing each inspected method?  It triggered DC-1896 the same as the problem this PR was originally intending to fix.  I replaced it with `callable()`, but I don't think that is exactly what you had intended.
=> [DC-1897] Refactoring reporter.py:

tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/populate_route_ids_test.py, tests/unit_tests/data_steward/resources_test.py
Added missing fields in expected columns list.
=> [DC-1824] Update unit tests for CDM v5.3.1

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier.py, data_steward/analytics/cdr_ops/controlled_tier_qc/code/check_mapping.py, data_steward/analytics/cdr_ops/controlled_tier_qc/code/controlled_tier_qc.py, data_steward/analytics/cdr_ops/controlled_tier_qc/csv/Controlled_Tier_Check_Description.csv, data_steward/analytics/cdr_ops/controlled_tier_qc/csv/Controlled_Tier_Mapping.csv, data_steward/analytics/cdr_ops/controlled_tier_qc/sql/query_templates.py, data_steward/analytics/cdr_ops/controlled_tier_qc/utils/helpers.py, data_steward/cdr_cleaner/cleaning_rules/aggregate_zip_codes.py, data_steward/common.py
* [DC-1803] Update the query for zip generalization incl. transformation
[DC-1803]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-1803] zipcode generalization check fails in contorlled_tier_QC notebook

data_steward/gcs_utils.py, data_steward/validation/main.py, tests/unit_tests/data_steward/validation/app_errors_test.py, tests/unit_tests/data_steward/validation/main_test.py
* [DC-1927] Allow copy files to continue with missing buckets
[DC-1927]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-1927] Allow copy files to continue with missing buckets

data_steward/validation/main.py
* Add logging messages for skipping folders
=> [DC-1941] Validation can skip folders without logging cause

data_steward/cdr_cleaner/clean_cdr_engine.py
Updated add_console_logging function to use pipeline_logging.
=> [DC-1793] Update `clean_engine` to utilize `pipeline_logging` utility

data_steward/cdr_cleaner/cleaning_rules/update_invalid_zip_codes.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/update_invalid_zip_codes_test.py
Changed set field values of invalid zip code concepts.
=> [DC-1893] Invalid Zip Code concept code applied to wrong field

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/ppi_branching.py
* [DC-1890] Update order of cleaning rules
[DC-1890]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-1890] Create dependency between PPI branching and concept remap and reorder rules

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv
* [DC-1940] Add ut_health_tyler
[DC-1940]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-1940] Add UT-Houston to pipeline

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/cancer_concept_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/organ_transplant_concept_suppression.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/cancer_concept_suppression_test.py
added cancer and organTransplant concepts in data suppression list.
=> [DC-1810] Apply Additional Row Suppression Rules to RT CDR

data_steward/utils/participant_summary_requests.py
* [DC-1984] Fix pagination error
[DC-1984]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-1984] Participant summary fails during pagination

data_steward/tools/add_hpo.py
function utilizes IAM test permission checking instead of list access.
=> [DC-1965] updated bucket_access_configured(bucket_name) to use StorageClient()

data_steward/tools/load_vocab.py, tests/integration_tests/data_steward/tools/load_vocab_test.py, tests/unit_tests/data_steward/tools/load_vocab_test.py
* [DC-1978] Remove property file requirement
[DC-1978]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-1978] Remove dataset property file requirement for loading vocabulary

data_steward/validation/ehr_union.py
removed list to set conversion to retain list sequence.
=> [DC-1993] ehr_union_test failure

data_steward/validation/participants/participant_validation_queries.py, data_steward/validation/participants/validate.py, tests/integration_tests/data_steward/validation/participants/validate_test.py
Added checks for first, middle, and last name to the refactored participant validation module.
=> [DC-1234] Perform DRC Name Comparisons

data_steward/constants/validation/email_notification.py, data_steward/gcloud/gsm/__init__.py, data_steward/requirements.txt, data_steward/validation/email_notification.py
* initial commit creates the secret manager extension
* secondary commits use the secret manager to obtain and use the mandrill token
=> [DC-2020] secret manager

data_steward/tools/delete_stale_test_datasets.py
Please see the JIRA ticket for the details.
=> [DC-2064] [Circle CI] Fix NotFound error in delete_stale_test_datasets

data_steward/resources.py, data_steward/tools/migrate_cdm52_to_cdm531.py, data_steward/tools/snapshot_by_query.py, docker-compose.yml, tests/unit_tests/data_steward/resources_test.py, tests/unit_tests/data_steward/tools/migrate_cdm52_to_cdm531_test.py
* [DC-2073] Update script to handle site tables
* [DC-2073] Update tests
[DC-2073]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-2073]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2073] Convert hpo site tables from v52 to v531

data_steward/cdr_cleaner/cleaning_rules/aggregate_zip_codes.py, data_steward/cdr_cleaner/cleaning_rules/cancer_concept_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/birth_information_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/cope_survey_response_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/ct_pid_rid_map.py, data_steward/cdr_cleaner/cleaning_rules/deid/explicit_identifier_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/fitbit_pid_rid_map.py, data_steward/cdr_cleaner/cleaning_rules/deid/geolocation_concept_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/motor_vehicle_accident_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/organ_transplant_concept_suppression.py, data_steward/cdr_cleaner/cleaning_rules/deid/pid_rid_map.py, data_steward/cdr_cleaner/cleaning_rules/deid/questionnaire_response_id_map.py, data_steward/cdr_cleaner/cleaning_rules/deid/string_fields_suppression.py, data_steward/cdr_cleaner/cleaning_rules/free_text_survey_response_suppression.py, data_steward/cdr_cleaner/cleaning_rules/generalize_zip_codes.py, data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables.py, data_steward/cdr_cleaner/cleaning_rules/identifying_field_suppression.py, data_steward/cdr_cleaner/cleaning_rules/null_person_birthdate.py, data_steward/cdr_cleaner/cleaning_rules/race_ethnicity_record_suppression.py, data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables.py, data_steward/cdr_cleaner/cleaning_rules/section_participation_concept_suppression.py, data_steward/cdr_cleaner/cleaning_rules/table_suppression.py, data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info.py
update *Ct_deid cleaning rules to accept table_namer parameter
=> [DC-1949] Implements the `table_namer` parameter to `C*_deid` data stage cleaning rules.

data_steward/gcloud/gcs/__init__.py, data_steward/tools/add_hpo.py, data_steward/tools/delete_stale_test_buckets.py, data_steward/validation/main.py, data_steward/validation/participants/writers.py, tests/integration_tests/data_steward/bq_utils_test.py, tests/integration_tests/data_steward/gcloud/gcs_client_test.py, tests/integration_tests/data_steward/gcs_utils_test.py, tests/integration_tests/data_steward/metrics/required_labs_test.py, tests/integration_tests/data_steward/retraction/retract_data_gcs_test.py, tests/integration_tests/data_steward/tools/combine_ehr_rdr_test.py, tests/integration_tests/data_steward/tools/delete_stale_test_buckets_test.py, tests/integration_tests/data_steward/tools/top_heel_errors_test.py, tests/integration_tests/data_steward/validation/achilles_heel_test.py, tests/integration_tests/data_steward/validation/achilles_test.py, tests/integration_tests/data_steward/validation/ehr_union_test.py, tests/integration_tests/data_steward/validation/export_test.py, tests/integration_tests/data_steward/validation/main_test.py, tests/unit_tests/data_steward/tools/delete_stale_test_buckets_test.py, tests/unit_tests/data_steward/validation/main_test.py, tests/unit_tests/data_steward/validation/participants/writers_test.py
* [DC-2092] Use function to define default creds
[DC-2092]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2092] Update Client instantiations with correct scopes

data_steward/analytics/cdr_ops/rdr_export_qc.py
* changes f-strings to jinja2 template strings
* adds optional parameter to compare a cleaned export to a raw export
* adds a check to make sure cleaning rules don't entirely drop survey Q/A pairs
=> [DC-2061] update the rdr import qc notebook

data_steward/gcloud/gcs/__init__.py, data_steward/validation/app_errors.py, data_steward/validation/main.py, tests/integration_tests/data_steward/gcloud/gcs_client_test.py, tests/unit_tests/data_steward/validation/main_test.py
Draft to trigger integration tests.
=> [DC-2063] StorageClient's get_drc_bucket() and get_hpo_bucket() return buckets

tests/integration_tests/data_steward/validation/export_test.py
- Full removal of gcs_utils.py dependency
- Variable renaming
=> [DC-2079] Full Removal of gcs_utils from integration tests in export_test.py

tests/integration_tests/data_steward/bq_utils_test.py
- Fully removes gcs_utils from the file.
- Refactors code
=> [DC-2076] Modernize integration tests in bq_utils_test to use GCS

data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info.py, tests/integration_tests/data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info_test.py
* Updated integration test case
=> [DC-2103] Update the survey version mapping cleaning rule to include Minute survey concepts

data_steward/validation/main.py, tests/unit_tests/data_steward/validation/main_test.py
- Removes` upload_string_to_gcs(...)` function and replaces calls with `blob.upload_from_string(...)` in data_steward/validation/main.py.
- Removes `upload_string_to_gcs(...)` test cases in tests/unit_tests/data_steward/validation/main_test.py.
=> [DC-2039] Refactor upload_string_to_gcs to use blob.upload_from_string(...)

tests/integration_tests/data_steward/metrics/required_labs_test.py
- Remove uses of gcs_utils
- Restructure elements by topic
=> [DC-2082] Modernize integration tests in required_labs_tests.py

tests/integration_tests/data_steward/tools/combine_ehr_rdr_test.py
- Remove the use of gcs_utils in test and supporting functions.
- Update syntax, add type hints, linting
=> [DC-2080] Full removal of gcs_utils in intergration tests in combine_ehr_rdr_test.py

data_steward/validation/ehr_union.py, tests/integration_tests/data_steward/validation/ehr_union_test.py
Copy of https://github.com/all-of-us/curation/pull/1108 with shorter branch name.
=> [DC-1989] added ehr_cutoff_date parameter to ehr_union

data_steward/bq_utils.py, tests/integration_tests/data_steward/validation/achilles_heel_test.py, tests/unit_tests/data_steward/bq_utils_test.py
- Refactor integration test to use StorageClient.
- Minor changes to function `load_cdm_csv` in `bq_utils.py` to accommodate changes made to the integration test.
=> [DC-2085] Modernize integration tests in achilles_heel_test to use GCS

tests/integration_tests/data_steward/validation/ehr_union_test.py
- Removes gcs_utils from ehr_union_test.py completely.
=> [DC-2078] Modernize integration tests in ehr_union_test.py to use GCS

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier.py, data_steward/analytics/cdr_ops/controlled_tier_qc/code/controlled_tier_qc.py, data_steward/analytics/cdr_ops/controlled_tier_qc/csv/Controlled_Tier_Field_Level.csv
* Fic qualifier_source_value field name for v5.3.1
* Update messaging in result notebook to show when there is nothing to report.
=> [DC-2161] Fix `controlled_tier_qc` checks to work with v531 and fix final report messaging

data_steward/validation/main.py, tests/integration_tests/data_steward/validation/main_test.py
- Removes StorageClient instance from `_validation_done(...)` in data_steward/validation/main.py.
=> [DC-2124] Modify _get_submission_folder  and _validation_done to take Bucket objects as arguments.

data_steward/retraction/create_deid_map.py, data_steward/retraction/participant_row_counts.py, data_steward/retraction/retract_data_bq.py, data_steward/retraction/retract_deactivated_pids.py, data_steward/retraction/retract_utils.py, tests/unit_tests/data_steward/retraction/create_deid_map_test.py, tests/unit_tests/data_steward/retraction/retract_data_bq_test.py, tests/unit_tests/data_steward/retraction/retract_deactivated_pids_test.py, tests/unit_tests/data_steward/retraction/retract_utils_test.py
- Implements the new BigQueryClient by replacing bq.get_client(...) calls in data_steward/retraction files.
=> [DC-2196] Replace bq.get_client(...) calls in data_steward/retraction

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/update_cope_flu_concepts.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/update_cope_flu_concepts_test.py
* change incorrect concept to correct concept for selected surveys
* add to pipeline at rdr datastage
* integration test
=> [DC-1894] correct cope flu question concepts

data_steward/common.py, data_steward/constants/validation/participants/snapshot_validaiton_dataset.py, data_steward/validation/participants/snapshot_validation_dataset.py, tests/unit_tests/data_steward/validation/participants/snapshot_validation_dataset_test.py
- [DC-2238] Add script to generate snapshot of validation
- [DC-2238] Add test and consts file
[DC-2238]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-2238]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2238] Add pipeline script to generate validation dataset

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/year_of_birth_records_suppression.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/suppress_year_of_birth_records_test.py
- [DC-2205](https://precisionmedicineinitiative.atlassian.net/browse/DC-2205) Add cleaning rule for CT from DC-1977 for DOB related dates
=> [DC-2205] Add cleaning rule for CT from DC-1977 for DOB related dates

data_steward/utils/bq.py, data_steward/validation/ehr_union.py, data_steward/validation/metrics/required_labs.py, data_steward/validation/participants/create_update_drc_id_match_table.py, data_steward/validation/participants/store_participant_summary_results.py, data_steward/validation/participants/validate.py, tests/integration_tests/data_steward/validation/main_test.py, tests/integration_tests/data_steward/validation/participants/create_update_drc_id_match_table_test.py, tests/integration_tests/data_steward/validation/participants/store_participant_summary_results_test.py, tests/integration_tests/data_steward/validation/participants/validate_test.py, tests/unit_tests/data_steward/validation/ehr_union_test.py, tests/unit_tests/data_steward/validation/main_test.py
- Implements the new `BigQueryClient` by replacing `bq.get_client(...)` calls in data_steward/validation folder files.
=> [DC-2197] Replace bq.get_client(...) calls in data_steward/validation

data_steward/constants/validation/participants/snapshot_validaiton_dataset.py, data_steward/validation/participants/snapshot_validation_dataset.py
* [DC-2287] Snapshot validation bug fixes
[DC-2287]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2287] Snapshot validation script runs into errors

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/clean_digital_health_data.py, data_steward/utils/participant_summary_requests.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_digital_health_data_test.py
[DC-1910] Initial commit
[DC-1910] Use latest partition
[DC-1910] Add integration test
[DC-1910] Snapshot a copy of digital health sharing status to sandbox
[DC-1910]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-1910]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-1910]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-1910]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> [DC-1910] Create cleaning rule to remove data based on digitalHealthSharingStatus

data_steward/constants/tools/combine_ehr_rdr.py
* [DC-2303] Exclude null fact_id_1/2 rows
[DC-2303]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2303] Exclude rows with NULL fact_id_1 and fact_id_2

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/domain_alignment_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/generalize_state_by_population_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/ppi_branching_test.py, tests/integration_tests/data_steward/gcs_utils_test.py, tests/integration_tests/data_steward/retraction/retract_data_bq_test.py, tests/integration_tests/data_steward/utils/participant_summary_requests_test.py, tests/integration_tests/data_steward/validation/participants/create_update_drc_id_match_table_test.py
- Replaces all bq.get_table_schema(...) calls with BigQueryClient.get_table_schema(...) in test/integration_tests folder files.
=> [DC-2217] Replace bq.get_table_schema(...) calls in tests/integration_tests

data_steward/tools/snapshot_serology_dataset.py, tests/unit_tests/data_steward/tools/snapshot_serology_dataset_test.py
* [DC-2263] Add script to create serology dataset
[DC-2263]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2263] Create script to generate serology data

data_steward/cdr_cleaner/cleaning_rules/drop_participants_without_ppi_or_ehr.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/drop_participants_without_ppi_or_ehr_test.py
* [DC-2379] Use mapping_dataset_id as a parameter
[DC-2379]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2379] Drop PPI CR fails due to missing mapping_dataset parameter

data_steward/cdr_cleaner/cleaning_rules/deid/year_of_birth_records_suppression.py
* [DC-2378] Exclude death table and add tables from DC-1977
[DC-2378]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2378] Year of birth suppression fails due to death table

data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables_test.py
* [DC-2380] Use updated client and split queries
[DC-2380]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2380] Remove extra tables CR needs to use the new client

data_steward/admin/admin_api.py
* this should allow logging to occur
* logging will allow logging metrics to happen
* logging metrics will allow GCP notifications
=> [DC-2115] add api logging setup to the admin service

data_steward/validation/participants/snapshot_validation_dataset.py
* [DC-2325] Add dataset label and description and use release_tag
* [DC-2325] Add parser description
[DC-2325]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-2325]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2325] Add dataset labels to snapshot validation script

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_covid_concept_no_suppression.py
* [DC-2381] Remove hardcoded kernel
[DC-2381]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2381] CT covid concept suppression notebook fails due to kernel error

data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables_test.py
* [DC-2382] Use dynamic list of final tables
[DC-2382]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2382] visit_detail and note_nlp tables dropped by remove_extra_tables CR

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_covid_concept_no_suppression.py
* [DC-2386] Fix notebook check
[DC-2386]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2386] Covid un-suppression notebook does not show stats

data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables_test.py
* [DC-2380] Ignore last empty query
[DC-2380]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2380] [Fix] Remove extra tables CR has an extra empty query

data_steward/ci/test_datasets.py, data_steward/tools/copy_dataset_to_output_prod.py, data_steward/tools/create_rdr_snapshot.py, data_steward/tools/create_tier.py, data_steward/tools/fitbit/generate_fitbit_dataset.py, data_steward/tools/import_rdr_omop.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/bigquery_tests_base.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/birth_information_suppression_test.py, tests/unit_tests/data_steward/tools/create_tier_test.py
- Replaces all `bq.define_dataset(...)` calls in curation by invoking the function using the `BigQueryClient`
=> [DC-2347] Replace all bq.define_dataset(...) calls in curation

data_steward/tools/delete_stale_test_datasets.py
Added checks for routines and models to exclude from stale datasets.
=> [DC-2072] Add logic to omit datasets that are "in use" from delete_stale_test_datsets

data_steward/.gcloudignore
Added DS_Store in gitcloudignore.
=> [DC-2427] Ignore Unwanted DS_Store file added by macOS

data_steward/cdr_cleaner/cleaning_rules/identifying_field_suppression.py, data_steward/resources.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/bigquery_tests_base.py, tests/unit_tests/data_steward/cdr_cleaner/reporter_test.py
* [DC-2389] Identifying field suppression CR needs to use existing client
[DC-2389]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2389] Identifying field suppression CR needs to use existing client

data_steward/validation/main.py, tests/unit_tests/data_steward/validation/main_test.py
* [DC-2350] Send email for failed submission
* [DC-2350] Refactor functionality
[DC-2350]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-2350]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2350] Process submissions after fixed time interval

data_steward/retraction/retract_data_bq.py, data_steward/validation/achilles.py, data_steward/validation/achilles_heel.py, data_steward/validation/export.py, data_steward/validation/metrics/completeness.py, data_steward/validation/metrics/required_labs.py, data_steward/validation/participants/create_update_drc_id_match_table.py, data_steward/validation/sql_wrangle.py, tests/integration_tests/data_steward/tools/delete_stale_test_datasets_test.py, tests/integration_tests/data_steward/validation/ehr_union_test.py, tests/unit_tests/data_steward/validation/achilles_test.py, tests/unit_tests/data_steward/validation/metrics/completeness_test.py
*Updates all bq_utils.get_table_id calls in data_steward/validation folder files. Excludes data_steward/validation/main.py.
=> [DC-2442] Update all bq_utils.get_table_id calls in data_steward/validation

data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded_test.py
…amer for get_sandbox_tablenames
=> [DC-2429] Modify RemoveFitbitDataIfMaxAgeExceeded rule to use table_namer for get_sandbox_tablenames

data_steward/cdr_cleaner/cleaning_rules/remove_participants_under_18years.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/remove_participants_under_18years_test.py
Please see the following comment in the JIRA ticket for the age calculation:
https://precisionmedicineinitiative.atlassian.net/browse/DC-2260?focusedCommentId=121588
=> [DC-2260] CR for remove pts<18 should be based on age at consent

data_steward/tools/load_vocab.py, tests/integration_tests/data_steward/tools/load_vocab_test.py
[[DC-2543] Add impersonation to load_vocab](https://github.com/all-of-us/curation/pull/1299/commits/36f6970da73af6b470290cdbd5ab8277dd50fdc7)
[DC-2543]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2543] Add impersonation to load_vocab

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report3_col_suppression.py
- pylint automatically updated the script linting, but the only changes in the logic are the following:
- The SQL for `NOTE_NLP` is updated: https://github.com/all-of-us/curation/pull/1313/files#diff-51278d23d019b0eaecc3ebd75524d0adbd25ffe4121e952739f86cb63356fb13R362
- `import urllib` is removed since it is not used: https://github.com/all-of-us/curation/pull/1313/files#diff-51278d23d019b0eaecc3ebd75524d0adbd25ffe4121e952739f86cb63356fb13L20
=> [DC-2372] NOTE_NLP QC check falsely says NOT PASS

data_steward/gcloud/bq/__init__.py, data_steward/tools/copy_dataset_to_output_prod.py, tests/integration_tests/data_steward/gcloud/gcs_client_test.py, tests/unit_tests/data_steward/gcloud/bq/bq_test.py
* [DC-2463] Add serialize and wait on jobs functionality
* [DC-2463] Use wait on jobs for copy dataset functionality
* [DC-2463] Use if for serialize jobs
[DC-2463]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-2463]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-2463]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2462] `glcoud/bq/__init__.py` does not wait for all jobs to finish before returning

data_steward/utils/participant_summary_requests.py, data_steward/validation/participants/store_participant_summary_results.py, tests/unit_tests/data_steward/utils/participant_summary_requests_test.py
* [DC-2585] Use string all_hpo
* [DC-2585] Add pagination
[DC-2585]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-2585]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2585] Modify PS script to allow running on full participant summary data or specified hpo_id

data_steward/resource_files/schemas/extension_tables/survey_conduct_ext.json
Add an extension table for conduct_survey
=> [DC-2625] Add `survey_conduct_ext` extension table

data_steward/resource_files/schemas/extension_tables/survey_conduct_ext.json
Remove two schema fields (`value`, `type`) and add `language`
=> [DC-2705] Modify `survey_conduct_ext` extension table schema in extension_tables schema files

data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py
- No update in the main logic is necessary, because this cleaning rule runs against `survey_conduct_ext` as long as `survey_conduct.json` exists under `data_steward/resource_files/schemas/cdm/`. The corresponding line is [here](https://github.com/all-of-us/curation/blob/develop/data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py#L144).
- Replaced the local constants with references to the constants in `common`.
- Updated the SQL statements to JINJA2 format.
- Integration test does not exist for this cleaning rule.
=> [DC-2629] Update clean_mapping.py for survey_conduct_ext

data_steward/requirements.txt
* [DC-2469] Update requirements.txt
[DC-2469]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2469] Upgrade qgrid from 1.2.1 to 1.3.1 for compatability issues

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/deid/survey_conduct_dateshift.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/survey_conduct_dateshift_test.py
* [DC-2636] Date shift columns in survey_conduct table
[DC-2636]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2636] Date shift columns in survey_conduct table

data_steward/tools/run_deid.py
- See the comment in the JIRA ticket for more details.
=> [DC-2638] Add survey_conduct to deid_tables list

data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/no_data_30_days_after_death_test.py
* Add visit_detail to affected tables
* modify queries to delete instead of select replace
* make sandbox queries to create or replace
=> [DC-2771] Add missing tables and modify queries to DML in no_data_30_days_after_death

data_steward/analytics/cdr_ops/combined.py, data_steward/analytics/cdr_ops/notebook_utils.py, data_steward/analytics/cdr_ops/rdr_export_qc.py
- Moved `render_message()` from `rdr_export_qc.py` to `notebook_utils.py` as it's useful for other QC notebooks.
=> [DC-2754] Update the combined notebook to check for null or orphaned `survey_conduct_id`s

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/drop_extreme_measurements_test.py
The updates implemented in DC-849 are included in this ticket for testing purposes. The only updates that this branch will contribute will be the integration test.
=> [DC-1211] Integration Test for Height/Weight/BMI CR

data_steward/analytics/cdr_ops/qc_serology_ct_dataset.py
- Modified the get_table function query to correctly template variables.
- Functions require the client parameter (DI).
- Removed unused `pandas` import
- Some lines contained trailing white space.  I confirmed the removal has no side effect.
=> [DC-2674] Fix Serology QC notebook 

data_steward/gcloud/bq/__init__.py, data_steward/resources.py, data_steward/tools/copy_dataset_to_output_prod.py, data_steward/tools/create_tier.py, data_steward/tools/load_rdr_file.py, data_steward/utils/parameter_validators.py, tests/unit_tests/data_steward/resources_test.py, tests/unit_tests/data_steward/tools/create_tier_test.py, tests/unit_tests/data_steward/tools/load_rdr_file_test.py, tests/unit_tests/data_steward/utils/parameter_validators_test.py
* ability to load an ad hoc file from the RDR bucket
* Will require the user to impersonate a service account with the access
* will require a json schema file
* should be able to load any file from that bucket with no (or minimal) changes needed, even if it is the first time we have seen the file
=> [DC-2964] load ad hoc file from RDR bucket

.circleci/config.yml
CircleCI config update with new slack-orb version.
=> [DC-2981] CircleCI Security Alert: update gcloud_cred and slack_webhook

data_steward/admin/admin_api.py, data_steward/admin/prod_pid_detection.py, data_steward/resource_files/scheduled_queries/monitor_nonprod_person_id_violation.txt, tests/integration_tests/data_steward/admin/prod_pid_detection_test.py, tests/unit_tests/data_steward/admin/admin_api_test.py
- After this branch is merged to `develop` and deployed, I will create GCP alerting policies to catch [these three log messages](https://github.com/all-of-us/curation/pull/1458/files#diff-55244244d8407609fe3cb9c4721d9290c6531afe54aa8d0fe67558a627c13858R26).
- [Scheduled query was updated to loop with a smaller size,](data_steward/resource_files/scheduled_queries/monitor_nonprod_person_id_violation.txt) to avoid BigQuery's resource limit.
=> [DC-2704] Set up a GCP alert for the curation slack channel if any disallowed values are found

data_steward/admin/prod_pid_detection.py
- Updated the logic to find any violation of the day, even when there is one record that says `No violation found`.
- Updated the description of the arg parser.
=> [DC-2704] Bug fix

data_steward/analytics/cdr_ops/incremental_load_qc.py, data_steward/cdr_cleaner/manual_cleaning_rules/remediate_basics.py, data_steward/resources.py, data_steward/retraction/retract_utils.py, data_steward/tools/run_basics_remediation.py, tests/integration_tests/data_steward/cdr_cleaner/manual_cleaning_rules/remediate_basics_test.py
- See the comment section in the JIRA ticket for what the generated HTML file looks like.
=> [DC-3079] Create a validation notebook for the hot-fix "missing basics"

data_steward/bq_utils.py, data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py, data_steward/constants/cdr_cleaner/clean_cdr.py, data_steward/constants/global_variables.py, data_steward/retraction/retract_data_bq.py, data_steward/validation/main.py
* [DC-3044] Update retraction to skip based on type
* [DC-3044] Add env vars for datasets table
* [DC-3044] Update retraction cron to also clean
[DC-3044]: https://precisionmedicineinitiative.atlassian.net/browse/DC-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-3044]: https://precisionmedicineinitiative.atlassian.net/browse/DC-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DC-3044]: https://precisionmedicineinitiative.atlassian.net/browse/DC-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-3044] Update cron jobs for retraction to retract in place

data_steward/tools/historical_retraction.py
* [DC-3057] Add retraction prototype script
[DC-3057]: https://precisionmedicineinitiative.atlassian.net/browse/DC-3057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-3057] Run prototype to test retraction on a single dataset

data_steward/deid/config/internal_tables/src_hpos_to_allowed_states.csv, data_steward/tools/add_hpo.py, tests/unit_tests/data_steward/tools/add_hpo_test.py
Script update to add hpo sites in pipeline.
=> [DC-3078] Add Waianae to the Curation Pipeline

data_steward/tools/add_hpo.py, tests/unit_tests/data_steward/tools/add_hpo_test.py
=> [DC-3116] Bug Fix add_hpo script.

data_steward/bq_utils.py, data_steward/constants/bq_utils.py, data_steward/tools/add_hpo.py, data_steward/validation/participants/store_participant_summary_results.py, tests/unit_tests/data_steward/tools/add_hpo_test.py
automate bucket_name csv update.
=> [DC-3117] Automate csv file update for hpo_id_bucket_name

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py
According to the [ticket](https://precisionmedicineinitiative.atlassian.net/browse/DC-2846), the RT notebook, which determines a participant's age, is flawed:
- The age threshold is hard coded to 89. A more flexible solution would be to parameterize this and default to using 89 with papermill parameters.
- The day we run the CDR is unimportant. We need to determine the age at the cutoff date. CURRENT_DATE should be parameterized to a value that represents the CDR cutoff date.
This PR addresses these issues.
=> [DC-2846] Update the RT notebook determining a participant's age

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_base_qa_report1.py
Only lines 254 and 258 were updated for this PR. The rest of the changes were automatically applied because of python linting.
=> [DC-3055] `cdr_deid_base_qa_report1.py` needs to use `AoUDRC_NoneIndicated` for check 1.5 instead of `None Indicated`

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report1_generalization_rule.py
Only lines 255, 457, and 505 were updated for this PR. The rest of the changes were automatically applied because of python linting.
=> [DC-3059] `cdr_deid_qa_report1_generalization_rule.py` references `pipeline` variable

data_steward/bq_utils.py
=> [DC-3087] Add COSSMA to the Curation Pipeline

data_steward/analytics/cdr_ops/clean_rdr_export_qc.py
- I also removed the misguiding comment for the parameter `raw_rdr` in the notebook.
=> [DC-3121] Update clean_rdr_export_qc.py to correctly handle the updated backfill logic

data_steward/admin/prod_pid_detection.py, data_steward/resource_files/scheduled_queries/monitor_nonprod_person_id_violation.txt
I updated the scheduled query. The previous version's loop logic was incomplete.
=> [DC-3009] Update scheduled query for prod ID prevention

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report4_dateshift.py
updated dateshift notebook for errors.
=> [DC-3073] the notebook, `analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report4_dateshift.py` needs several updates

data_steward/analytics/cdr_ops/controlled_tier_qc/sql/query_templates.py
updated site_masking table to be used from pipeline tables.
=> [DC-3048] `site_maskings` is not available at expected location for CT notebook, `analytics/cdr_ops/controlled_tier_qc/check_controlled_tier.py`

data_steward/constants/validation/email_notification.py, data_steward/validation/email_notification.py
* [DC-2724] Update link to transfer data to the DRC
[DC-2724]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DC-2724] Update the link to instructions in the results.html emails

data_steward/validation/ehr_union.py, tests/integration_tests/data_steward/validation/ehr_union_test.py, tests/unit_tests/data_steward/validation/ehr_union_test.py
- `death` table is already suppressed with https://github.com/all-of-us/curation/pull/1560
- Updated `import common` and `import resources` for better readability
=> [DC-3134] Update `ehr_union.py` to accommodate `aou_death`

data_steward/analytics/cdr_ops/clean_rdr_export_qc.py
PR from branch bg/dc_1520 was replaced with this PR.
=> [DC-1520] Add primary_pid_rid_mapping checks to clean rdr qc notebook

data_steward/analytics/cdr_ops/vocabulary_upload_qc.py
=> [DC-3175] Add checks to vocabulary_upload_qc.py

data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/deid/remove_fitbit_data_if_max_age_exceeded_test.py
Update remove_fitbit_data_if_max_age_exceeded.py and tests for the new device
=> [DC-3165] Update remove_fitbit_data_if_max_age_exceeded.py for device

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_clean_qa_report1.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report3_col_suppression.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report4_dateshift.py
- Most of the changes are automatically done by pylint. The only meaningful changes are updating the references for `death` to `aou_death`
=> [DC-3215] Update QC `cdr_deid_xyz.py` for `aou_death`

data_steward/resource_files/scheduled_queries/monitor_nonprod_person_id_violation.txt
- I already updated the scheduled query in our BigQuery. This PR is to update the reference SQL file to the latest
=> [DC-3278] Update PROD ID violation check SQL to handle partitioned tables without error

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/generate_research_device_ids.py, data_steward/common.py, data_steward/resource_files/schemas/pipeline_tables/wearables_device_id_masking.json, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/generate_research_device_ids_test.py
This CR updates the `wearables_device_id_masking` pipeline table.
=> [DC-3229] Create generate_research_device_ids CR

data_steward/resource_files/schemas/wearables/fitbit/activity_summary.json, data_steward/resource_files/schemas/wearables/fitbit/heart_rate_minute_level.json, data_steward/resource_files/schemas/wearables/fitbit/heart_rate_summary.json, data_steward/resource_files/schemas/wearables/fitbit/sleep_daily_summary.json, data_steward/resource_files/schemas/wearables/fitbit/sleep_level.json, data_steward/resource_files/schemas/wearables/fitbit/steps_intraday.json
A helpful reference link is documented in the ticket.
=> [DC-3257] Update the fitbit schema field descriptions

data_steward/analytics/cdr_ops/raw_rdr_export_qc.py, data_steward/resources.py
=> [DC-3338] Update the 'not mapping to concept_id` check 

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/dedup_measurement_value_as_concept_id_test.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/store_new_duplicate_measurement_concept_ids_test.py
store_new_duplicate_measurement_concept_ids_test
=> [DC-3372] Correct failing integration test

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/calculate_bmi.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/calculate_bmi_test.py
NOTE:
- Queenie confirmed `measurement_type_concept_id` must be `32865`. See the ticket's comment section (DC2791)
=> [DC-3239] Add CR to calculate BMI

data_steward/admin/key_rotation.py, data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_part2.py, data_steward/analytics/cdr_ops/cross_ct_rt/CDR_QC_RT_vs_CT.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py, data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/create_person_ext_table.py, data_steward/resource_files/schemas/wearables/fitbit/activity_summary.json, data_steward/resource_files/schemas/wearables/fitbit/device.json, data_steward/resource_files/schemas/wearables/fitbit/heart_rate_minute_level.json, data_steward/resource_files/schemas/wearables/fitbit/heart_rate_summary.json, data_steward/resource_files/schemas/wearables/fitbit/sleep_daily_summary.json, data_steward/resource_files/schemas/wearables/fitbit/sleep_level.json, data_steward/resource_files/schemas/wearables/fitbit/steps_intraday.json, data_steward/tools/add_hpo.py, data_steward/validation/sql_wrangle.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/create_person_ext_table_test.py, tests/integration_tests/data_steward/tools/fitbit/generate_fitbit_dataset_test.py, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/create_person_ext_table_test.py, tests/unit_tests/data_steward/validation/sql_wrangle_test.py
=> [DC-3333] Upgrade to python version 3.10

data_steward/constants/tools/create_combined_backup_dataset.py, data_steward/tools/create_combined_backup_dataset.py, tests/unit_tests/data_steward/tools/create_combined_backup_dataset_test.py
Update combined dataset generation script to add data origins for PPI data in _mapping tables.
=> [DC-3258] Update create_combined_backup_dataset.py to include rdr origin flags in mapping tables

data_steward/resources.py, data_steward/tools/import_rdr_dataset.py, tests/integration_tests/data_steward/tools/import_rdr_dataset_test.py
- While testing, I encountered the error that says the label can be only up to 63 letters. I updated this line as a result: https://github.com/all-of-us/curation/pull/1712/files#diff-6ecbf63270b1fe0210a08915e522c72d8d164fdb10460211699a92511fb6e929R812
=> [DC-3383] Update `import_rdr_dataset.py` to import death data into `aou_death`

data_steward/analytics/cdr_ops/fitbit_qc.py
Dear reviewer,
- Please review https://github.com/all-of-us/curation/pull/1737 and https://github.com/all-of-us/curation/pull/1738 before this PR.
=> [DC-3464] Update `fitbit_qc.py` to reference `HEART_RATE_INTRADAY` instead of `HEART_RATE_MINUTE_LEVEL`

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report6_fitdata.py
Dear reviewer,
- Please review https://github.com/all-of-us/curation/pull/1737 and https://github.com/all-of-us/curation/pull/1738 before this PR.
=> [DC-3465] Update `cdr_deid_qa_report6_fitdata.py` to reference `HEART_RATE_INTRADAY` instead of `HEART_RATE_MINUTE_LEVEL`

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_part2.py, data_steward/analytics/cdr_ops/cross_ct_rt/CDR_QC_RT_vs_CT.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py, data_steward/cdr_cleaner/cleaning_rules/deid/year_of_birth_records_suppression.py, data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables.py, data_steward/resource_files/schemas/cdm/clinical/survey_conduct.json, tests/unit_tests/data_steward/cdr_cleaner/cleaning_rules/remove_extra_tables_test.py
Controlled Tier related changes
=> [DC-3518] Fixes for CT run

data_steward/cdr_cleaner/cleaning_rules/deid/recent_concept_suppression.py, data_steward/deid/aou.py, data_steward/deid/parser.py, data_steward/deid/press.py, data_steward/tools/deid_runner.sh, data_steward/tools/run_deid.py, tests/unit_tests/data_steward/deid/parser_test.py, tests/unit_tests/data_steward/tools/run_deid_test.py
=> [DC-3517] Fixes for RT run

data_steward/cdr_cleaner/cleaning_rules/deid/survey_version_info.py, data_steward/cdr_cleaner/cleaning_rules/generate_ext_tables.py, data_steward/cdr_cleaner/cleaning_rules/populate_survey_conduct_ext.py, data_steward/cdr_cleaner/cleaning_rules/remove_participant_data_past_deactivation_date.py, data_steward/constants/tools/create_combined_backup_dataset.py, data_steward/resource_files/schemas/cdm/clinical/survey_conduct.json, data_steward/tools/create_combined_backup_dataset.py, data_steward/utils/participant_summary_requests.py, tests/integration_tests/data_steward/tools/create_combined_backup_dataset_test.py, tests/integration_tests/data_steward/utils/participant_summary_requests_test.py, tests/unit_tests/data_steward/tools/create_combined_backup_dataset_test.py, tests/unit_tests/data_steward/utils/participant_summary_requests_test.py
fixes made during combined step run.
=> [DC-3516] Fixes for combined run

data_steward/common.py, data_steward/tools/create_rdr_snapshot.py
create mapping tables during snapshot.
=> [DC-3544] Updates to include and exclude new mapping tables at Raw RDR stage

data_steward/deid/config/ids/config.json, data_steward/tools/deid_runner.sh
* use correct PPI scr_hpo_ids instead of 'rdr'
* update key file parser to use correct project_id key in `deid_runner.sh`.
=> [DC-3533] Fix race and gender deduplication query in legacy RT code

data_steward/analytics/cdr_ops/raw_rdr_export_qc.py, data_steward/tools/import_rdr_dataset.py
=> [DC-3552] RDR Notebooks update

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report12_extra.py, data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report7_cope_survey.py
=> [DC-3493] Update the RT deid notebooks 7-8 + 10-12

data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_without_consent.py, data_steward/tools/create_ehr_snapshot.sh, data_steward/tools/generate_unioned_ehr_dataset.sh, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/remove_ehr_data_without_consent_test.py
=> [DC-3553] Update scripts for running unioned stage

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_part2.py, data_steward/analytics/cdr_ops/cross_ct_rt/CDR_QC_RT_vs_CT.py
Controlled tier notebook updates.
=> [DC-3543] Notebook Updates for CT checks

data_steward/cdr_cleaner/cleaning_rules/create_aian_lookup.py
updated aian lookup to have table in sandbox.
=> [DC-3593] 'aian_list' table does not exist in rdr sandbox

data_steward/cdr_cleaner/clean_cdr.py, data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_consistency.py, data_steward/cdr_cleaner/cleaning_rules/temporal_consistency.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/ensure_date_datetime_consistency_test.py
- Added a test case just to double-check `EnsureDateDatetimeConsistency` works for `visit_occurrence`
=> [DC-3561] Add `EnsureDateDatetimeConsistency` after `TemporalConsistency`

data_steward/cdr_cleaner/cleaning_rules/date_unshift_cope_responses.py, tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/date_unshift_cope_responses_test.py
updated cleaning rule to not use hardcoded list.
=> [DC-3613] Change Hardcoded Cope Survey Concept_id in Unshifting Date CR

data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py
CT notebook update for site_maskings.
=> [DC-3649] Update CT notebook 10 to use updated site_maskings location

data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid.py
updated repopulate_person query for aouDRC indicator.
=> [DC-3647] Update repopulate person post deid CR to account for custom concept

data_steward/resources.py
updated git tag fetch function.
=> [DC-3646] Update git tag function to sort by version correctly

tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/repopulate_person_post_deid_test.py
repopulate_person_post_deid_test fix.
=> [DC-3653] Integration Test fix for Parent ticket

data_steward/analytics/cdr_ops/participant_validation_qc.py
Updated Participant validation QC check.
=> [DC-3658] Update Participant Validation QC check for excluded sites

data_steward/analytics/cdr_ops/controlled_tier_qc/check_controlled_tier_part2.py
=> [DC-3659] Update check controlled tier part 2 to include standard classifications

data_steward/validation/participants/snapshot_validation_dataset.py
validation dataset script to validate Hpo instead of cron job.
=> [DC-3650] Include PII Validation in Snapshot script

data_steward/tools/create_combined_backup_dataset.py
=> [DC-3651] Fix Combined Backup script for git_version

data_steward/analytics/cdr_ops/combined.py
=> [DC-3660] Update Combined QC notebook to include CE
